import { defToDamageReduction, DEF_DIMINISHING_RETURNS_FLOOR, levelStatScale } from './formulas.js';
export { defToDamageReduction, DEF_DIMINISHING_RETURNS_FLOOR };

// ============================================================================
// Updated gear-tier system (2026-07-11). ADDITIVE model:
//   effective = base * (1 + gear_pct + account_pct)   for HP/ATK/DEF
//   effective = base + gear_flat + account_flat        for SPD/ACC/RES
// Two independent inputs:
//   • gear_tier         (starter/fair/good/endgame) — per champion
//   • account_development(poor/fair/good)            — Great Hall + Arena bundle,
//                                                      account-wide (profile field)
// Masteries (none/partial/full) are a CLAN-BOSS DAMAGE modifier, not a stat change
// — see masteryDamageModifier(). PLACEHOLDER numbers; calibrate against 10-15 real
// accounts before shipping. gear_tier_config holds the DB copy of GEAR_TIERS.
//
// NOTE: applied ONLY to manual rosters. Gestal rosters carry real effective_stats
// (actual gear, which already includes Great Hall/Arena), so mapRoster prefers those
// and never calls this — account_development must not be double-counted there.
// ============================================================================

// HP/ATK/DEF are percentage bonuses; SPD/ACC/RES are flat; CRATE/CDMG are fractions.
const GEAR_TIERS = {
  starter: { hp: 0.30, atk: 0.30, def: 0.30, spd: 15,  acc: 30,  res: 20,  crate: 0.20, cdmg: 0.20 },
  fair:    { hp: 0.60, atk: 0.60, def: 0.60, spd: 35,  acc: 80,  res: 50,  crate: 0.45, cdmg: 0.50 },
  good:    { hp: 1.00, atk: 1.00, def: 1.00, spd: 60,  acc: 150, res: 80,  crate: 0.70, cdmg: 0.80 },
  endgame: { hp: 2.00, atk: 2.00, def: 2.00, spd: 100, acc: 220, res: 120, crate: 0.90, cdmg: 1.30 },
};

/* ── PER-TYPE GEAR TIERS — the measured baseline (2026-07-20) ────────────────────────────────
 * GENERATED by `tools/fit-gear-tiers.mjs` from teams that ACTUALLY CLEARED each stage band, then
 * pasted here. Re-run that tool after any Gestal sync; these numbers are EXPECTED TO MOVE and are
 * a starting point taken with eyes open, not a settled constant (Mike, 2026-07-20).
 *
 * WHY PER TYPE: the single GEAR_TIERS table above is calibrated to an ATTACKER and over-credits
 * supports catastrophically. Measured against DonThor's real Dragon team the error was
 *   Attack   ACC  -3%  ·  C.RATE  -3%      (accurate)
 *   Support  ACC +130% ·  C.RATE +240%     (a healer credited 85% crit when she runs 25%)
 * A support does not buy crit, and a DoT carrier cannot use it at all (damage-mechanics.js §1:
 * %maxHP DoT cannot crit). One table cannot serve them.
 *
 * FITTED AT THE MEDIAN (PCTL=0.5), and that choice is load-bearing. There are TWO different
 * questions and they want DIFFERENT percentiles:
 *   ESTIMATOR (this table): "the player said 'good' — what stats do they PROBABLY have?"  -> MEDIAN
 *   THRESHOLDS/floors:      "what does the content actually REQUIRE?"                      -> p25/min
 * Fitting this table at p25 was tried first and produced a systematic UNDER-estimate (Attack ACC
 * error went -3% -> -27% on a real team), because p25 answers the floor question, not this one.
 * Do NOT reuse these numbers as thresholds; re-run the fitter with PCTL=0.25 for that.
 *
 * MONOTONIC BY CONSTRUCTION (running max up the tiers). The raw fit was not — attack hp came out
 * 0.73/0.91/0.99/0.91 — because bands are separated by which champions appear in them, not purely
 * by gear. A flattened cell means "no evidence this tier needs more", NOT "measured to be equal".
 *
 * ONLY attack/support/dot ARE FITTED (n=10-16). `defense`, `hp` and `hybrid` came out as one or two
 * champions repeated across bands (defense was byte-identical in three tiers — it was Gnut, three
 * times), so they are deliberately ABSENT and fall back to the generic GEAR_TIERS row.
 *
 * ⚠ KNOWN ODDITY: `dot.starter.spd = 7`. Early-game DoT champions in the corpus are genuinely
 * barely geared for speed, but the jump to 45 at `fair` is abrupt enough to be worth re-checking
 * once there are more low-stage clears. Left as measured rather than smoothed by hand. */
export const GEAR_TIERS_BY_TYPE = {
  starter: {
    attack:  { hp: 0.99, atk: 1.05, def: 0.65, spd: 73, acc: 125, res: 27, crate: 0.74, cdmg: 0.19 }, // n=16
    support: { hp: 0.90, atk: 0.52, def: 0.88, spd: 77, acc: 61,  res: 23, crate: 0.20, cdmg: 0.19 }, // n=13
    dot:     { hp: 0.39, atk: 1.01, def: 0.73, spd: 49, acc: 44,  res: 6,  crate: 0.20, cdmg: 0.65 }, // n=12
  },
  fair: {
    attack:  { hp: 0.99, atk: 1.17, def: 0.67, spd: 73, acc: 125, res: 27, crate: 0.74, cdmg: 0.19 }, // n=13
    support: { hp: 1.04, atk: 0.52, def: 0.88, spd: 82, acc: 61,  res: 23, crate: 0.20, cdmg: 0.29 }, // n=13
    dot:     { hp: 0.52, atk: 1.01, def: 0.87, spd: 93, acc: 58,  res: 10, crate: 0.21, cdmg: 0.65 }, // n=10
  },
  good: {
    attack:  { hp: 1.05, atk: 1.41, def: 0.67, spd: 74, acc: 152, res: 27, crate: 0.74, cdmg: 0.19 }, // n=15
    support: { hp: 1.04, atk: 0.84, def: 1.08, spd: 97, acc: 61,  res: 30, crate: 0.25, cdmg: 0.50 }, // n=12
    dot:     { hp: 0.84, atk: 1.01, def: 0.87, spd: 93, acc: 72,  res: 10, crate: 0.32, cdmg: 0.73 }, // n=3 THIN
  },
  /* ⚠ ENDGAME SPD IS RULED, NOT FITTED (Mike, 2026-07-20): "endgame speed should be 200."
   * Stored as a BONUS OVER BASE — typical base SPD is ~95-105, so a 200 TOTAL is a bonus of ~100.
   * The fitted value was 74 (total ~173), and the gap is a LABELLING error in the bands, not a
   * disagreement about the game: the `endgame` row is fitted from stages 20-25 NORMAL, and Mike's
   * own gear test showed stage 20 is cleared on a median of 3.1/6 pieces at 5*+16 — i.e. that band
   * is "good" territory, not endgame. True endgame content (Hard mode, CB Nightmare/Ultra Nightmare,
   * Doom Tower) has NO captures in the corpus, so the top of this scale cannot be measured yet; it
   * is UNANCHORED rather than mis-measured.
   *
   * Applied to all three types because SPD is the one stat with no meaningful role split — measured
   * at 152-224 across every role, and the only stat that converges across accounts.
   *
   * ⚠ CONSEQUENCE: the ladder now steps 73 -> 73 -> 74 -> 100, i.e. nothing between "good" and
   * "endgame". That is the gap Mike's proposed 5-tier scheme (fair/good/strong/god) would fill, and
   * it is an OPEN decision. Also unresolved: how this 200 relates to the earlier "god tier speeds are
   * over 300" — the current vocabulary has only four keys, so 200 and 300 cannot both be the top.
   * Re-running tools/fit-gear-tiers.mjs will NOT reproduce this value; it is deliberately hand-set. */
  endgame: {
    attack:  { hp: 1.05, atk: 1.41, def: 0.67, spd: 100, acc: 160, res: 34, crate: 0.74, cdmg: 0.19 }, // spd RULED
    support: { hp: 1.04, atk: 0.84, def: 1.13, spd: 100, acc: 74,  res: 30, crate: 0.25, cdmg: 0.50 }, // spd RULED
    dot:     { hp: 0.89, atk: 1.01, def: 0.87, spd: 100, acc: 116, res: 10, crate: 0.32, cdmg: 0.73 }, // spd RULED
  },
};

const DOT_TAG_NAMES = new Set(['Poison', 'HP Burn', 'Necrosis', 'Enemy Max HP Damage']);

/**
 * Which per-type gear row applies to this champion. Returns null when no fitted row exists, so the
 * caller falls back to the generic GEAR_TIERS table (defense/HP-role/hybrid champions).
 *
 * DoT DETECTION IS A KNOWN-IMPERFECT PROXY. Ideally "is DoT their PRIMARY damage", which needs a
 * magnitude model we do not have (INS-0031). Tags alone cannot separate Ninja from Ezio — both are
 * role=Attack carrying a DoT tag plus AoE Damage, yet one is a DoT carrier and the other an
 * attacker who happens to poison. Here we only claim `dot` for a NON-Attack-role champion carrying
 * a DoT tag, which is the conservative subset: it catches Narma and Orn without ever mis-labelling
 * a crit attacker. Attack-role DoT carriers are estimated as attackers — an accepted, named error.
 */
export function championGearType(champion) {
  const role = String(champion?.role ?? '').toLowerCase();
  if (role === 'attack') return 'attack';
  const tags = (champion?.champion_tags ?? [])
    .filter(t => t.status === 'approved').map(t => t.tags?.name);
  if (tags.some(t => DOT_TAG_NAMES.has(t))) return 'dot';
  if (role === 'support') return 'support';
  return null;   // defense / hp / unknown -> generic table
}

const ACCOUNT_DEV = {
  poor: { hp: 0.05, atk: 0.05, def: 0.05, acc: 5,  res: 5,  cdmg: 0.02 },
  fair: { hp: 0.14, atk: 0.14, def: 0.14, acc: 20, res: 15, cdmg: 0.06 },
  good: { hp: 0.28, atk: 0.28, def: 0.28, acc: 40, res: 30, cdmg: 0.15 },
};

// DEPRECATED (2026-07-12): the account-wide flat masteries modifier. Superseded by the
// per-champion boss-mastery model in lib/masteries.js (bossMasteryDamageModifier) — the boss
// masteries (Warmaster/Giant Slayer) live on SPECIFIC champions, not the whole account, and a
// flat +15% badly under-counts a Warmaster carrier's %-max-HP damage. Kept only so any legacy
// caller still resolves; no longer used by the match engine.
const MASTERY_DAMAGE = { none: 1.00, partial: 1.075, full: 1.15 };

// Base C.Rate 15% / C.DMG 50% are universal RSL defaults (percent units, matching
// the rest of the engine). Gear/account fractions are converted to percent here.
const BASE_CRIT_RATE = 15;
const BASE_CRIT_DMG  = 50;

const DEFAULT_GEAR_TIER = 'starter';
const DEFAULT_ACCOUNT_DEV = 'fair';

// CANONICAL gear-tier scale = the GEAR_TIERS keys (starter/fair/good/endgame). Three
// vocabularies existed and did NOT map: the account selector + engine tables use
// starter/fair/good/endgame; the Gestal per-champ classifier (gearTierFromArtifacts) and
// the champ-detail UI use RSL-flavored Starter/Dungeon/Strong/God Tier. So a God-Tier
// champ's tier missed every GEAR_WEIGHT/GEAR_TIERS lookup and silently read as Starter
// (weight 1) — flattening real gear and capping confidence at the "dungeon gear" band.
// normalizeGearTier() maps EVERY variant to canonical. Positional: Dungeon≈fair,
// Strong≈good, God Tier≈endgame. Apply it wherever a gear_tier string is consumed.
const GEAR_TIER_ALIASES = {
  starter: 'starter',
  dungeon: 'fair',      fair: 'fair',
  strong:  'good',      good: 'good',
  'god tier': 'endgame', godtier: 'endgame', god_tier: 'endgame', endgame: 'endgame',
};
export function normalizeGearTier(t) {
  const k = String(t ?? '').trim().toLowerCase();
  return GEAR_TIER_ALIASES[k] ?? DEFAULT_GEAR_TIER;
}

// Resolve the gear tier to a canonical GEAR_TIERS key. prefer opts.gearTier (account
// selector, manual rosters), else the champion's own tier (Gestal per-champ), normalized.
function tierOf(userChampion, opts) {
  return normalizeGearTier(opts?.gearTier ?? userChampion?.gear_tier);
}
function devOf(opts) {
  const d = String(opts?.accountDev ?? '').toLowerCase();
  return ACCOUNT_DEV[d] ? d : DEFAULT_ACCOUNT_DEV;
}

// Add the Great Hall / Arena estimate to an already-computed effective-stats object
// (the Gestal path). Gestal exports real gear but NOT Great Hall levels, and
// effectiveStats() has no account-wide term — so a developed account's champs were
// missing the flat ACC/RES the Great Hall grants (ACC especially gates content). We add
// only the FLAT, base≈0 stats (ACC/RES) from the account_development bundle — the same
// coarse source the manual estimator uses. HP/ATK/DEF Great-Hall bonuses are flat in-game
// (not % of base), so the ACCOUNT_DEV %-model would mis-apply them here; left out
// deliberately until we can source real Great Hall levels.
export function applyAccountBonus(eff, accountDev) {
  if (!eff) return eff;
  const a = ACCOUNT_DEV[String(accountDev ?? '').toLowerCase()] ?? ACCOUNT_DEV[DEFAULT_ACCOUNT_DEV];
  return { ...eff, acc: (eff.acc ?? 0) + a.acc, res: (eff.res ?? 0) + a.res };
}

export function masteryDamageModifier(masteries) {
  return MASTERY_DAMAGE[String(masteries ?? '').toLowerCase()] ?? MASTERY_DAMAGE.none;
}

export function estimatedDamageReduction(champion, userChampion, opts = {}) {
  const gear = GEAR_TIERS[tierOf(userChampion, opts)];
  const acct = ACCOUNT_DEV[devOf(opts)];
  const estimatedDef = Math.round((champion.base_def ?? 0) * (1 + gear.def + acct.def));
  return defToDamageReduction(estimatedDef);
}

/**
 * Estimate a champion's effective stats from base stats + gear tier + account dev.
 * @param {object} champion     - DB champions row (base_hp, base_atk, ...).
 * @param {object} userChampion - user_champions row (legacy per-champion fields).
 * @param {object} [opts]       - account-level gear context from the profile:
 *   { gearTier: 'starter'|'fair'|'good'|'endgame', accountDev: 'poor'|'fair'|'good' }.
 * @returns {{ hp, atk, def, spd, acc, res, crit_rate, crit_dmg }} (crit in percent).
 */
export function estimateStats(champion, userChampion, opts = {}) {
  const tier = tierOf(userChampion, opts);
  // Prefer the fitted per-type row; fall back to the generic table for types we could not fit
  // (defense / HP-role / hybrid — one or two champions each, not a sample).
  const type = championGearType(champion);
  const gear = (type && GEAR_TIERS_BY_TYPE[tier]?.[type]) || GEAR_TIERS[tier];
  const acct = ACCOUNT_DEV[devOf(opts)];
  // HP/ATK/DEF scale with the champion's level (base stats are the 6★/60 max); SPD/ACC/RES/crit
  // are level-independent. Without this, under-leveled manual champs were over-estimated ~3×.
  const lvl = levelStatScale(userChampion?.level, userChampion?.stars);
  return {
    hp:  Math.round((champion.base_hp  ?? 0) * lvl * (1 + gear.hp  + acct.hp)),
    atk: Math.round((champion.base_atk ?? 0) * lvl * (1 + gear.atk + acct.atk)),
    def: Math.round((champion.base_def ?? 0) * lvl * (1 + gear.def + acct.def)),
    spd: (champion.base_spd ?? 0) + gear.spd,
    acc: (champion.base_acc ?? 0) + gear.acc + acct.acc,
    res: (champion.base_res ?? 0) + gear.res + acct.res,
    crit_rate: Math.min(100, (champion.base_crit_rate ?? BASE_CRIT_RATE) + gear.crate * 100),
    crit_dmg:  (champion.base_crit_dmg ?? BASE_CRIT_DMG) + (gear.cdmg + acct.cdmg) * 100,
  };
}

// Exported for the gear_tier_config reseed + tests to stay in sync with the DB copy.
export const GEAR_TIER_TABLE = GEAR_TIERS;
export const ACCOUNT_DEV_TABLE = ACCOUNT_DEV;
