-- ============================================================================
-- 102 - Backfill champions present in the master Champions tab but missing from
-- the live champions table (base forms only). Identity from worksheet. type_id
-- left null (Gestal mapping is a separate follow-up). Guarded by NOT EXISTS.
-- Requires seed 101 (Mythical rarity) applied first. Idempotent.
-- ============================================================================
insert into champions (name, faction, affinity, rarity, role, game_id, source_citation)
select v.name, v.faction, v.affinity, v.rarity, v.role, 'raid_shadow_legends',
       'master Champions tab (2026-07-11 migration backfill)'
from (values
  ('Ashnar Dragonsoul','Orcs','Force','Mythical','HP'),
  ('Admiral Blacktusk','Dwarves','Spirit','Legendary','Support'),
  ('Authoratrix Lamasu','Demonspawn','Void','Legendary','Support'),
  ('Acolyte of the Slither','Argonites','Spirit','Rare','Support'),
  ('Boughsmith Flannan','Sylvan Watchers','Force','Rare','Defense'),
  ('Branch-Arm Lasair','Sylvan Watchers','Void','Rare','HP'),
  ('Crimson Pegason','Argonites','Force','Rare','HP'),
  ('Drowned Bloatwraith','Undead Hordes','Void','Rare','Attack'),
  ('Glensage Cithrel','Sylvan Watchers','Void','Rare','Support'),
  ('Hidestitcher Boorn','Skinwalkers','Magic','Rare','Support'),
  ('Loneblade Riab','Sylvan Watchers','Force','Rare','Attack'),
  ('Meatcarver Tolog','Skinwalkers','Force','Rare','HP'),
  ('Ogryn Jailer','Ogryn Tribes','Force','Rare','Attack'),
  ('Pathfinder Cait','Sylvan Watchers','Magic','Rare','Attack'),
  ('Redcloak Taneko','Shadowkin','Magic','Rare','Defense'),
  ('Shadowbow Tirlac','Sylvan Watchers','Spirit','Rare','Defense'),
  ('Treeshield Knott','Sylvan Watchers','Void','Rare','Support'),
  ('Tribuck Colwyn','Sylvan Watchers','Magic','Rare','Defense'),
  ('Dawncaller Sabitha','Knights Revenant','Void','Epic','Support'),
  ('Deephook Nagis','Argonites','Void','Epic','Defense'),
  ('Frenzi the Cackler','Skinwalkers','Void','Epic','Defense'),
  ('Fyr-Gun Isbeil','Dwarves','Force','Epic','Attack'),
  ('Lightward Siendra','High Elves','Void','Epic','Attack'),
  ('Lionsguard Galatea','Argonites','Spirit','Epic','Attack'),
  ('Mistrider Daithi','Sylvan Watchers','Force','Epic','Attack'),
  ('Old Ghrukkus','Ogryn Tribes','Force','Epic','Support'),
  ('Old Hermit Jorrg','Orcs','Magic','Epic','Support'),
  ('Sandlashed Survivor','Orcs','Spirit','Epic','Defense'),
  ('Stonebound Thisbe','Argonites','Magic','Epic','Attack'),
  ('Tidemaster Dexikos','Argonites','Magic','Epic','Support'),
  ('White Dryad Nia','Sylvan Watchers','Void','Epic','Defense'),
  ('Basileus Roanas','High Elves','Force','Legendary','Attack'),
  ('Bladechorister Caldor','Sylvan Watchers','Spirit','Legendary','Attack'),
  ('Brewguard Jeroboam','Ogryn Tribes','Force','Legendary','Defense'),
  ('Chronicler Adelyn','Banner Lords','Force','Legendary','Support'),
  ('Dune Herald Zaharis','Barbarians','Force','Legendary','Support'),
  ('Dune Lord Greggor','Barbarians','Force','Legendary','Defense'),
  ('First Ax Tuskkor','Ogryn Tribes','Force','Legendary','Attack'),
  ('Gracchos Turn Drake','Demonspawn','Spirit','Legendary','HP'),
  ('Grand Oak Padraig','Sylvan Watchers','Spirit','Legendary','Support'),
  ('Greathoof Loriaca','Skinwalkers','Spirit','Legendary','Support'),
  ('Greenwarden Ruarc','Sylvan Watchers','Force','Legendary','Defense'),
  ('High Keeper Prysma','High Elves','Spirit','Legendary','Support'),
  ('Highmother Maud','Sacred Order','Force','Legendary','Support'),
  ('Iudex Artor','Sacred Order','Spirit','Legendary','Support'),
  ('KrokMar the Devourer','Lizardmen','Spirit','Legendary','HP'),
  ('Krokhad the Throatripper','Orcs','Magic','Legendary','Attack'),
  ('Lady Noelle','Sacred Order','Void','Legendary','Support'),
  ('Legate Teox','Lizardmen','Spirit','Legendary','Attack'),
  ('Lord Entertainer Fabian','Undead Hordes','Spirit','Legendary','Support'),
  ('Losan KLeth','Knights Revenant','Force','Legendary','Defense'),
  ('MaShalled','Undead Hordes','Spirit','Legendary','Attack'),
  ('Mad Hatter','Knights Revenant','Force','Legendary','Support'),
  ('Matriarch Zarguna','Orcs','Force','Legendary','HP'),
  ('Onryo Ieyasu','Shadowkin','Void','Legendary','Attack'),
  ('Packmaster Shyek','Orcs','Force','Legendary','HP'),
  ('Pontiff Augustin','Knights Revenant','Void','Legendary','Support'),
  ('Queen Eva','Dark Elves','Spirit','Legendary','Attack'),
  ('Sanguine Maria','Undead Hordes','Force','Legendary','Attack'),
  ('Storm Herald Hekaton','Argonites','Void','Legendary','Defense'),
  ('Strategos Islin','High Elves','Magic','Legendary','Defense'),
  ('Swarmspeaker Zyclic','Dark Elves','Force','Legendary','Attack'),
  ('Tribune Herakletes','Undead Hordes','Spirit','Legendary','Defense'),
  ('Vault Keeper Wixwell','Sacred Order','Force','Legendary','Defense'),
  ('Wallmaster Othorion','High Elves','Magic','Legendary','Attack'),
  ('Wight King Narses','Knights Revenant','Void','Legendary','HP'),
  ('Wight Queen Ankora','Knights Revenant','Magic','Legendary','Support'),
  ('Blood Marchioness Mina','Undead Hordes','Magic','Mythical','Attack'),
  ('Hierophant Lazarius','Lizardmen','Magic','Mythical','Support'),
  ('Night Queen Krixia','Knights Revenant','Spirit','Mythical','Support'),
  ('Starsage Galathir','High Elves','Force','Mythical','Support'),
  ('The Calamitus','Undead Hordes','Spirit','Mythical','Attack'),
  ('Vallaryn the Equalizer','Undead Hordes','Magic','Legendary','Attack')
) as v(name, faction, affinity, rarity, role)
where not exists (select 1 from champions c where c.game_id='raid_shadow_legends' and c.name=v.name);
