-- ============================================================================
-- 138 - Correct tags.description from the authoritative keyword glossary
-- (data/keyword-glossary.json). Auto-replaced 45 THIN/WRONG descriptions with the
-- game-encyclopedia definitions (Mike-provided, Tier-1). Substantial existing
-- descriptions that carry TAGGING GUIDANCE were left untouched (review-only).
-- Source: tools/tag-desc-from-glossary.mjs. See INS-0028.
-- ============================================================================
update tags set description = 'The Caster takes 25/50% of DIRECT damage inflicted upon a protected ally. Self-inflicted damage, Poison, and HP Burn do NOT trigger it.' where name = 'Ally Protection' and game_id = 'raid_shadow_legends';
update tags set description = 'Cannot act for N turns; cooldowns do NOT refresh while active; the Champion only takes 75% of incoming damage — applied to ALL targets.' where name = 'AoE Freeze' and game_id = 'raid_shadow_legends';
update tags set description = 'Cannot act for N turns; cooldowns do NOT refresh; ANY incoming damage removes Sleep — applied to ALL targets.' where name = 'AoE Sleep' and game_id = 'raid_shadow_legends';
update tags set description = 'Cannot act for N turns; cooldowns do NOT refresh while active — applied to ALL targets.' where name = 'AoE Stun' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases damage inflicted AND damage received by 50%.' where name = 'Berserk' and game_id = 'raid_shadow_legends';
update tags set description = 'Makes the Champion immune to ALL forms of damage.' where name = 'Block Damage' and game_id = 'raid_shadow_legends';
update tags set description = 'While active, the Champion is immune to all debuffs. Instant negative effects (e.g. Decrease Turn Meter) are NOT affected and work as normal.' where name = 'Block Debuffs' and game_id = 'raid_shadow_legends';
update tags set description = 'Prevents the affected Champion from using PASSIVE skills (other than their default and active skills) for the duration. Cooldowns refresh as normal. Does NOT work on bosses (→ useless vs a dungeon boss; only vs minions/waves/PvP).' where name = 'Block Passive Skills' and game_id = 'raid_shadow_legends';
update tags set description = 'When attacked, strikes back at the attacker with their Default Skill for 75% damage. Only counters once vs a multi-hit skill. Does not counter a counterattack. Does not count as a turn. Extra-Turn-on-kill default skills do NOT grant the extra turn during a counter.' where name = 'Counterattack' and game_id = 'raid_shadow_legends';
update tags set description = 'A Champion under Deathbrand receives Block Revive when killed.' where name = 'Deathbrand' and game_id = 'raid_shadow_legends';
update tags set description = 'Decreases Battle Attack by 25/50%.' where name = 'Decrease Attack' and game_id = 'raid_shadow_legends';
update tags set description = 'Decreases Critical Rate by 15% or 30%.' where name = 'Decrease C.Rate' and game_id = 'raid_shadow_legends';
update tags set description = 'Decreases Battle Defense by 30/60%. (Amplifies ATTACK damage only — NOT DoT; see damage-mechanics §1.)' where name = 'Decrease Defense' and game_id = 'raid_shadow_legends';
update tags set description = 'Decreases Battle Resistance by 25% or 50% — makes landing debuffs easier (less ACC required).' where name = 'Decrease RES' and game_id = 'raid_shadow_legends';
update tags set description = 'Decreases Battle Speed by 15/30%.' where name = 'Decrease Speed' and game_id = 'raid_shadow_legends';
update tags set description = 'Any Turn Meter INCREASE the Champion receives is reduced by 50% or 100%.' where name = 'Ensnare' and game_id = 'raid_shadow_legends';
update tags set description = 'After using an active skill, the Champion receives a 1-turn Sleep. If they use a debuff-removing skill, Fatigue is removed and no Sleep is placed.' where name = 'Fatigue' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases damage inflicted by 10% and reduces damage received by 10%.' where name = 'Fervor' and game_id = 'raid_shadow_legends';
update tags set description = 'Reduces any enemy Ignore DEF effects by 15% or 25%. (Defensive counter to Shatter/Ignore-DEF.)' where name = 'Fortify' and game_id = 'raid_shadow_legends';
update tags set description = 'Cannot act for N turns; cooldowns do NOT refresh while active; the Champion only takes 75% of incoming damage.' where name = 'Freeze' and game_id = 'raid_shadow_legends';
update tags set description = 'At the start of the affected Champion''s turn, they and all allies take 3% of their respective MAX HP. Only ONE HP Burn can be active on a Champion at a time.' where name = 'HP Burn' and game_id = 'raid_shadow_legends';
update tags set description = 'Damage from skills to this Champion cannot be decreased/blocked/redirected/transferred and BYPASSES Unkillable, Block Damage, Increase DEF, Strengthen, Ally Protection, Veil, Perfect Veil, Shield. Applies only to direct skill damage (not debuffs/passives/masteries). The target can still Evade.' where name = 'Hunter''s Gaze' and game_id = 'raid_shadow_legends';
update tags set description = 'Prevents any attempt to INCREASE a Champion''s skill cooldown. Each stack fully blocks one such attempt then is consumed. No duration (can''t be extended/reduced/spread). If immune to cooldown increases, stacks aren''t consumed; if the effect cannot be resisted, one stack is removed. Fewer stacks won''t overwrite a higher total. If stolen, all stacks transfer.' where name = 'Immutable' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases the recipient''s ACC by 25% or 50%.' where name = 'Increase ACC' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases Battle Attack (current ATK incl. all modifiers) by 25% or 50%.' where name = 'Increase Attack' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases Battle Defense by 30% or 60%.' where name = 'Increase Defense' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases Battle Resistance by 25% or 50%.' where name = 'Increase RES' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases Battle Speed by 15% or 30%.' where name = 'Increase Speed' and game_id = 'raid_shadow_legends';
update tags set description = 'When an enemy under Infest is SLAIN, all remaining enemies take PURE damage equal to 50% of the dead enemy''s MAX HP (cannot crit). Against Bosses or their minions, capped at 10% of MAX HP. (→ weak in dungeons; an Arena/multi-enemy tool.)' where name = 'Infest' and game_id = 'raid_shadow_legends';
update tags set description = 'Blocks any attempt to apply CROWD-CONTROL debuffs — even ones that ''cannot be blocked'': Stun, Sleep, Freeze, Provoke, Fear, True Fear, Petrification, Sheep. Each stack negates one such attempt then is consumed. No duration (can''t be extended/reduced/transferred). vs Block Debuffs: if the CC is blockable an Intercept stack is NOT consumed (even if immune); if the CC cannot be blocked, a stack IS always removed (even if immune). Gaining fewer stacks won''t lower the current count. If stolen, the thief gains the exact stack count.' where name = 'Intercept' and game_id = 'raid_shadow_legends';
update tags set description = 'Reinforces HP for N turns. Damage hits the Magma Shield first (unless the attack ignores Shields); on expiry/0 the buff is removed. Also REFLECTS an equal amount of damage back to the attacker.' where name = 'Magma Shield' and game_id = 'raid_shadow_legends';
update tags set description = 'Like Seal, and ADDITIONALLY blocks Blessings (except stat boosts).' where name = 'Master Seal' and game_id = 'raid_shadow_legends';
update tags set description = 'When an enemy dies, 1 Necrosis stack is applied to all surviving enemies (accumulates per death). At the start of their turn, each Champion takes 5% of MAX HP per Necrosis stack.' where name = 'Necrosis' and game_id = 'raid_shadow_legends';
update tags set description = 'The Champion cannot have skills activated, join Ally Attacks, gain Extra/Instant Turns, have cooldowns decreased, have Shield increased, have destroyed HP restored, have HP swapped/balanced, Evade, or have Turn Meter equalized.' where name = 'Nullify' and game_id = 'raid_shadow_legends';
update tags set description = 'Damages the target by 2.5/5% of MAX HP at the beginning of their turn. Not affected by other effects; scales only off the target''s MAX HP.' where name = 'Poison' and game_id = 'raid_shadow_legends';
update tags set description = 'Blocks damage from Poison debuffs. If an HP Burn was placed before Poison Cloud, the Cloud won''t work (but isn''t removed). Not affected by Steal/Remove/Spread/Increase/Decrease Buff Duration.' where name = 'Poison Cloud' and game_id = 'raid_shadow_legends';
update tags set description = 'If the Champion dies, they are immediately revived with 30% HP and 0% Turn Meter.' where name = 'Revive on Death' and game_id = 'raid_shadow_legends';
update tags set description = 'Blocks effects from Gear Sets and Masteries (except stat boosts). Effects activated before placement aren''t blocked.' where name = 'Seal' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases the Champion''s Ignore DEF effects by 7.5% or 15%. (Offensive; countered by Fortify.)' where name = 'Shatter' and game_id = 'raid_shadow_legends';
update tags set description = 'Reinforces HP for N turns; damage hits the Shield first (unless the attack ignores Shields); removed on expiry/0. Damage to the Shield does NOT count as damage to the Champion, so Lifesteal does not benefit from it.' where name = 'Shield' and game_id = 'raid_shadow_legends';
update tags set description = 'Cannot act for N turns; cooldowns do NOT refresh; ANY incoming damage removes Sleep.' where name = 'Sleep' and game_id = 'raid_shadow_legends';
update tags set description = 'When the Champion uses an Active Skill, a meteorite hits for 25% of their MAX HP + 5% of all other enemies'' MAX HP. Only one Smite per team at a time.' where name = 'Smite' and game_id = 'raid_shadow_legends';
update tags set description = 'Decreases damage (except from Bombs and HP Burn), removes all debuffs except Bombs/HP Burn, grants immunity to all debuffs except Bombs/HP Burn, and gives extra Stone Skin HP. Also immune to Decrease MAX HP and Decrease Turn Meter effects.' where name = 'Stone Skin' and game_id = 'raid_shadow_legends';
update tags set description = 'Each stack increases damage by 5% (max 5). At 5 stacks, attacking applies an IRRESISTIBLE Stun to the target and all stacks are removed.' where name = 'Stormcall' and game_id = 'raid_shadow_legends';
update tags set description = 'Increases damage received by the target by 15/25%.' where name = 'Weaken' and game_id = 'raid_shadow_legends';
