-- ============================================================================
-- Seed 153 — Dark Elves in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 2. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Arachoa Moonspinner (Mythical, Dark Elves)
-- NAME: in-game reads "Arachoa Moonspinner"; our row is "Arachoa". Not renamed (belongs in champion_aliases).
update champions set base_hp=22635, base_atk=881, base_def=1465, base_spd=110, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20
where id='c815fd25-fe29-4295-8848-d75a1cbb4bc6' and base_hp is null;

-- Mavara the Web Diviner (Legendary, Dark Elves)
update champions set base_hp=22305, base_atk=892, base_def=1200, base_spd=110, base_crit_rate=15, base_crit_dmg=50, base_res=40, base_acc=0
where id='d0faf818-5d29-4530-8ab0-aee9edfab8aa' and base_hp is null;
