-- ============================================================================
-- Seed 154 — Dark Elves in-game 2 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 3. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Noldua the Gloaming (Legendary, Dark Elves)
-- NAME: in-game reads "Noldua the Gloaming"; our row is "Noldua". Not renamed (belongs in champion_aliases).
update champions set base_hp=20640, base_atk=914, base_def=1288, base_spd=108, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20
where id='285ccf18-77b5-4731-982a-34961e800ea7' and base_hp is null;

-- Sydax King-killer (Legendary, Dark Elves)
-- NAME: in-game reads "Sydax King-killer"; our row is "Sydax". Not renamed (belongs in champion_aliases).
update champions set base_hp=18825, base_atk=859, base_def=1465, base_spd=99, base_crit_rate=15, base_crit_dmg=50, base_res=40, base_acc=20
where id='f69c408d-e48a-4439-b15b-645403c22b70' and base_hp is null;

-- Varkos Headsplitter (Legendary, Dark Elves)
-- NAME: in-game reads "Varkos Headsplitter"; our row is "Varkos". Not renamed (belongs in champion_aliases).
update champions set base_hp=19485, base_atk=760, base_def=1520, base_spd=101, base_crit_rate=15, base_crit_dmg=63, base_res=40, base_acc=0
where id='94826114-c84b-4adc-b1d4-23ab05eb6672' and base_hp is null;
