-- ============================================================================
-- Seed 155 — Dwarves in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Cinda Forgeheart (Mythical, Dwarves)
-- NAME: in-game reads "Cinda Forgeheart"; our row is "Cinda". Not renamed (belongs in champion_aliases).
update champions set base_hp=17175, base_atk=1707, base_def=1002, base_spd=100, base_crit_rate=15, base_crit_dmg=63, base_res=50, base_acc=0
where id='3aa9cc69-dd9e-4100-b75a-951e34497761' and base_hp is null;
