-- ============================================================================
-- Seed 156 — Dwarves in-game 2 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Granyt Doorkeep (Legendary, Dwarves)
-- NAME: in-game reads "Granyt Doorkeep"; our row is "Granyt". Not renamed (belongs in champion_aliases).
update champions set base_hp=24780, base_atk=804, base_def=1123, base_spd=105, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=10
where id='8cb6b080-afbe-451c-ad74-f231dd37f09e' and base_hp is null;
