-- ============================================================================
-- Seed 157 — Dwarves in-game 3 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Hilvi the Rime-called (Legendary, Dwarves)
-- NAME: in-game reads "Hilvi the Rime-called"; our row is "Hilvi". Not renamed (belongs in champion_aliases).
update champions set base_hp=20475, base_atk=826, base_def=1387, base_spd=110, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20
where id='b4ee7163-16ac-4e5b-8558-15c0c2ae38cc' and base_hp is null;
