-- ============================================================================
-- Seed 158 — Dwarves in-game 4 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Hilda Arnorndottr (Epic, Dwarves)
-- NAME: in-game reads "Hilda Arnorndottr"; our row is "Hilda". Not renamed (belongs in champion_aliases).
update champions set base_hp=15690, base_atk=1421, base_def=837, base_spd=99, base_crit_rate=15, base_crit_dmg=60, base_res=30, base_acc=0
where id='a279d3c1-e007-490a-a870-32d4b0972b16' and base_hp is null;
