-- ============================================================================
-- Seed 159 — Dwarves in-game 5 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Maddak, Eyes of Skyiron (Epic, Dwarves)
-- NAME: in-game reads "Maddak, Eyes of Skyiron"; our row is "Maddak". Not renamed (belongs in champion_aliases).
update champions set base_hp=14535, base_atk=1365, base_def=969, base_spd=97, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=15
where id='ff31d162-33e8-4a01-b89e-9b5eac3a644b' and base_hp is null;
