-- ============================================================================
-- Seed 160 — Lizardmen in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 3. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Anaxia the Reborn (Mythical, Lizardmen)
-- NAME: in-game reads "Anaxia the Reborn"; our row is "Anaxia". Not renamed (belongs in champion_aliases).
update champions set base_hp=20145, base_atk=936, base_def=1575, base_spd=100, base_crit_rate=15, base_crit_dmg=50, base_res=50, base_acc=20
where id='3ad705d5-3b32-4f36-9997-9a7e98b05bed' and base_hp is null;

-- Kosk of Two Skins (Legendary, Lizardmen)
-- NAME: in-game reads "Kosk of Two Skins"; our row is "Kosk". Not renamed (belongs in champion_aliases).
update champions set base_hp=15690, base_atk=1542, base_def=991, base_spd=99, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=10
where id='677f9085-f120-46db-85c8-65f32298d153' and base_hp is null;

-- Predator (Legendary, Lizardmen)
update champions set base_hp=25770, base_atk=716, base_def=1145, base_spd=98, base_crit_rate=15, base_crit_dmg=63, base_res=40, base_acc=0
where id='3a2201b8-91ef-4a9c-aeef-9f181d84b92e' and base_hp is null;
