-- ============================================================================
-- Seed 162 — Lizardmen in-game 2 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 2. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Galapo the Recluse (Epic, Lizardmen)
-- NAME: in-game reads "Galapo the Recluse"; our row is "Galapo". Not renamed (belongs in champion_aliases).
update champions set base_hp=17340, base_atk=881, base_def=1266, base_spd=98, base_crit_rate=15, base_crit_dmg=50, base_res=45, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='fdc456cf-e6a4-4cf1-bb94-c842a91ac8e9' and base_hp is null;

-- Xiloco the Encrusted (Legendary, Lizardmen)
-- NAME: in-game reads "Xiloco the Encrusted"; our row is "Xiloco". Not renamed (belongs in champion_aliases).
update champions set base_hp=17835, base_atk=925, base_def=1465, base_spd=101, base_crit_rate=15, base_crit_dmg=50, base_res=50, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='ba782124-c3b1-4b06-87d0-0cb78ca282bf' and base_hp is null;
