-- ============================================================================
-- Seed 167 — Sylvan Watchers in-game 2 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 2. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Gladewulf (Rare, Sylvan Watchers)
update champions set base_hp=16185, base_atk=716, base_def=1233, base_spd=99, base_crit_rate=15, base_crit_dmg=50, base_res=40, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='c95aa0a3-0f2b-4da5-84b9-497c92c7e298' and base_hp is null;

-- Vestele Riverthorn (Legendary, Sylvan Watchers)
-- NAME: in-game reads "Vestele Riverthorn"; our row is "Vestele". Not renamed (belongs in champion_aliases).
update champions set base_hp=14700, base_atk=1729, base_def=870, base_spd=103, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='d6595122-41cc-467c-b734-5eccc1a7dd6a' and base_hp is null;
