-- ============================================================================
-- Seed 172 — Banner Lords in-game 2 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Edward Kenway (Legendary, Banner Lords)
-- NAME: in-game reads "Edward Kenway"; our row is "Edward". Not renamed (belongs in champion_aliases).
update champions set base_hp=15195, base_atk=1575, base_def=991, base_spd=101, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=10,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='6d6389f5-dbd3-42e1-ad99-5a81717a59bc' and base_hp is null;
