-- ============================================================================
-- Seed 173 — Banner Lords in-game 3 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 2. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Cecilia the Red Hope (Legendary, Banner Lords)
-- NAME: in-game reads "Cecilia the Red Hope"; our row is "Cecilia". Not renamed (belongs in champion_aliases).
update champions set base_hp=18825, base_atk=804, base_def=1520, base_spd=107, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='7d3d35c6-0513-4f52-a44f-aa9c861e0c8c' and base_hp is null;

-- Silvain the Paramour (Rare, Banner Lords)
-- NAME: in-game reads "Silvain the Paramour"; our row is "Silvain". Not renamed (belongs in champion_aliases).
update champions set base_hp=14865, base_atk=1321, base_def=716, base_spd=101, base_crit_rate=15, base_crit_dmg=57, base_res=30, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='fec20400-2a84-4aac-820f-785462937fb9' and base_hp is null;
