-- ============================================================================
-- Seed 176 — Shadowkin in-game 3 (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Masahiro the Bell Monk (Legendary, Shadowkin)
-- NAME: in-game reads "Masahiro the Bell Monk"; our row is "Masahiro". Not renamed (belongs in champion_aliases).
update champions set base_hp=24450, base_atk=782, base_def=1167, base_spd=109, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='4998b81b-27a7-49c2-9c5c-feeaa3699bf4' and base_hp is null;
