-- ============================================================================
-- Seed 178 — Undead Hordes in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Gaspard the Accused (Legendary, Undead Hordes)
-- NAME: in-game reads "Gaspard the Accused"; our row is "Gaspard". Not renamed (belongs in champion_aliases).
update champions set base_hp=18495, base_atk=749, base_def=1597, base_spd=104, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=10,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='627c3f19-9d78-4c71-a89a-284b1c67d880' and base_hp is null;
