-- ============================================================================
-- Seed 183 — Ogryn Tribes + Barbarians in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 5. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Grugtha Darkseer (Legendary, Ogryn Tribes)
-- NAME: in-game reads "Grugtha Darkseer"; our row is "Grugtha". Not renamed (belongs in champion_aliases).
update champions set base_hp=17340, base_atk=1398, base_def=1024, base_spd=102, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='d2f1c322-4d5c-4030-a9d0-dc1cc10aadc5' and base_hp is null;

-- Kroz Wallbreaker (Legendary, Ogryn Tribes)
-- NAME: in-game reads "Kroz Wallbreaker"; our row is "Kroz". Not renamed (belongs in champion_aliases).
update champions set base_hp=16350, base_atk=1454, base_def=1035, base_spd=110, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='4969ec7f-5ab6-46fe-acae-0b1bb4f76917' and base_hp is null;

-- Klaazag Keyhulk (Legendary, Ogryn Tribes)
-- NAME: in-game reads "Klaazag Keyhulk"; our row is "Klaazag". Not renamed (belongs in champion_aliases).
update champions set base_hp=18165, base_atk=771, base_def=1597, base_spd=100, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=10,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='6d6ca3ef-877b-4fec-b855-b1a3e981be51' and base_hp is null;

-- Arne the White (Mythical, Barbarians)
-- NAME: in-game reads "Arne the White"; our row is "Arne". Not renamed (belongs in champion_aliases).
update champions set base_hp=17505, base_atk=1707, base_def=980, base_spd=115, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='c0d73b3a-8236-4e9a-afe2-bb4c762b736e' and base_hp is null;

-- Bayek (Legendary, Barbarians)
update champions set base_hp=18330, base_atk=683, base_def=1674, base_spd=103, base_crit_rate=15, base_crit_dmg=50, base_res=40, base_acc=20,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='83c1a971-cffb-4835-82e0-f7c32e733a09' and base_hp is null;
