-- ============================================================================
-- Seed 184 — High Elves in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 2. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Talenna Soulseer (Legendary, High Elves)
-- NAME: in-game reads "Talenna Soulseer"; our row is "Talenna". Not renamed (belongs in champion_aliases).
update champions set base_hp=19815, base_atk=980, base_def=1277, base_spd=110, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='2b57245a-5510-4c26-934f-a4dafce80c65' and base_hp is null;

-- Solanar the Gleaming (Legendary, High Elves)
-- NAME: in-game reads "Solanar the Gleaming"; our row is "Solanar". Not renamed (belongs in champion_aliases).
update champions set base_hp=14700, base_atk=1608, base_def=991, base_spd=105, base_crit_rate=15, base_crit_dmg=63, base_res=30, base_acc=0,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='a5086d2c-351b-46dc-a59c-9e4ca1b36477' and base_hp is null;
