-- ============================================================================
-- Seed 185 — Knights Revenant in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 2. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Venalicia Thrallmother (Legendary, Knights Revenant)
-- NAME: in-game reads "Venalicia Thrallmother"; our row is "Venalicia". Not renamed (belongs in champion_aliases).
update champions set base_hp=22140, base_atk=892, base_def=1211, base_spd=108, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='351986f9-9140-4c05-8451-a7b2d6b1351a' and base_hp is null;

-- Pontiff Augustin (Legendary, Knights Revenant)
update champions set base_hp=21810, base_atk=947, base_def=1178, base_spd=110, base_crit_rate=15, base_crit_dmg=50, base_res=30, base_acc=20,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='af36750e-4916-4543-b669-ea1b80e373f4' and base_hp is null;
