-- ============================================================================
-- Seed 186 — Orcs in-game (TIER-1)
--
-- SOURCE: Mike's own in-game champion screens, 6* Lvl 60, 2026-07-17.
-- TIER-1 under the CLAUDE.md source hierarchy — the game client's own numbers.
-- Generated by tools/seed-base-stats.mjs, which refuses to emit a row that fails
-- the HP-multiple-of-15 rule, a plausibility band, or the exactly-one-row check.
--
-- FILLS 1. CRIT written as PERCENT, matching seeds 146/149-152.



--
-- FILL-ONLY, REPLAY-SAFE: guarded `and base_hp is null`, keyed on champions.id.
-- ============================================================================

-- Gaellut, Son of the Pact (Legendary, Orcs)
-- NAME: in-game reads "Gaellut, Son of the Pact"; our row is "Gaellut". Not renamed (belongs in champion_aliases).
update champions set base_hp=23460, base_atk=914, base_def=1101, base_spd=99, base_crit_rate=15, base_crit_dmg=50, base_res=50, base_acc=10,
  base_stat_reference_rank=6, base_stat_reference_level=60,
  source_citation='in-game Index 6★ L60 Total Stats (Mike screenshot 2026-07-17); HP ✓ multiple-of-15'
where id='9c54a7cb-717b-4896-b625-909b105b95b5' and base_hp is null;
