-- ============================================================================
-- 195 — Relink 84 champion portraits to their EXISTING storage images.
--
-- 84 of the 91 Rare+ champions with a NULL portrait_url already have a
-- portrait file in the 'portraits' bucket, stored under the champion's SHORT/alias
-- name (e.g. 'Packmaster Shy'ek' -> legendary/shy_ek.jpg, 'Kro'khad the Throatripper'
-- -> legendary/kro_khad.jpg). The link broke because the DB carries the long name.
-- The alias registry (this session) bridges them: match champion + every alias against
-- the storage filenames, set portrait_url to the existing public URL. No re-crop, no
-- vision — a pure relink. Guarded to only touch rows still NULL. Idempotent.
-- The remaining 7 with no stored image at all need grid recovery (recover-portraits.js).
-- ============================================================================
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/shy_ek.jpg', updated_at=now() where id='a91a584c-68b1-48dc-809e-214eeef0cebf' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/var_gall.jpg', updated_at=now() where id='0f0090d8-504e-4e58-8124-aaf2a028d51c' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/fearmonger.jpg', updated_at=now() where id='88357d25-bd09-4838-a84a-1ebb7161b310' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/elder.jpg', updated_at=now() where id='519fe176-9074-40d6-9fe0-33001d9539c4' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/goon.jpg', updated_at=now() where id='032752ee-6049-435b-b488-653d313a2dbb' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/mythical/mina.jpg', updated_at=now() where id='1ef6e374-67e7-49da-b9ff-210d78a7fe47' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/grachos.jpg', updated_at=now() where id='4a8175bd-6029-4456-b35d-6ee637f20c67' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/kro_khad.jpg', updated_at=now() where id='20e18b74-2edb-403e-8e4f-5899d868f651' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/sentinel.jpg', updated_at=now() where id='0cf63721-e5b7-40da-b955-4902069c8cc6' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/sabitha.jpg', updated_at=now() where id='0465daca-89f5-4f27-9d9e-d8589d3725c7' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/cithrel.jpg', updated_at=now() where id='09e530d2-2652-41c9-9b0d-5e2e828b779a' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/boorn.jpg', updated_at=now() where id='d24cb41a-9ef4-4a8a-87cd-9f29c204eff5' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/eva.jpg', updated_at=now() where id='486e289a-35a9-4b35-a17f-0cbd37aeb50e' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/hekaton.jpg', updated_at=now() where id='b6106249-f2b4-4fc6-a478-d72b4d7bc28c' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/dexikos.jpg', updated_at=now() where id='3dfbfd27-2a35-49ee-a26b-638336684954' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/survivor.jpg', updated_at=now() where id='b7cad312-8504-4ff7-96bc-95b45fd56ebd' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/maria.jpg', updated_at=now() where id='f73b6bcd-1935-4bd0-9195-a6c41be632cd' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/k_leth.jpg', updated_at=now() where id='597f0699-f70e-4842-9398-959fcbef5a38' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/noelle.jpg', updated_at=now() where id='90ce7b2d-a332-4472-895e-1b46b4893884' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/siendra.jpg', updated_at=now() where id='141546c8-6658-46f5-80f1-6f128a5afe5b' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/ma_shalled.jpg', updated_at=now() where id='300db846-f7c2-471d-9565-9eaf4a9aaba8' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/hatter.jpg', updated_at=now() where id='67ca14b7-f3c0-48a5-bbf7-2f0110eac8f2' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/nagis.jpg', updated_at=now() where id='d7113da8-d4b3-4503-9bd7-f450cadb1ced' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/pegason.jpg', updated_at=now() where id='e0146a87-d355-4677-ac3b-4e4f4cc2459f' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/ghrukkus.jpg', updated_at=now() where id='b77b5f3f-4671-4195-a982-ba5914bd6cf0' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/blacktusk.jpg', updated_at=now() where id='ccb6bf0b-43f0-4bab-98f9-627ea623749e' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/caldor.jpg', updated_at=now() where id='6b45498c-3b72-450e-ac9d-76bc873ac411' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/jeroboam.jpg', updated_at=now() where id='abd75824-5d35-4428-a061-c2da2903af76' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/zaharis.jpg', updated_at=now() where id='3fd85f24-33c1-46af-bdb9-845dc30b42f2' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/prysma.jpg', updated_at=now() where id='00ad5079-3462-457d-b894-c67efaaf898d' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/zarguna.jpg', updated_at=now() where id='843385e2-f70d-4590-a2b1-ce5238a0602c' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/ieyasu.jpg', updated_at=now() where id='7930353a-a4e3-4006-8561-ad71df807c55' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/zyclic.jpg', updated_at=now() where id='12fe8718-e769-40a4-bb92-3f2c69a51324' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/roanas.jpg', updated_at=now() where id='d0ec94e3-3d90-4898-99db-92a208ba8ae0' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/galatea.jpg', updated_at=now() where id='e7cf2b73-12fb-46ec-8b17-da8abef0a44a' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/ukko.jpg', updated_at=now() where id='55954ec6-16b4-4174-b3a6-e8e181b2335b' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/ruarc.jpg', updated_at=now() where id='40ea0168-897b-4c59-85f4-60e1e8771c35' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/daithi.jpg', updated_at=now() where id='ccf19498-0d1f-4705-99ad-834b9e1c5f55' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/nia.jpg', updated_at=now() where id='c4627bee-de4d-488f-b51b-deb582e247cc' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/cait.jpg', updated_at=now() where id='68208c87-65c1-498c-8434-434bef86a3a4' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/corvis.jpg', updated_at=now() where id='5ae9262c-b74a-4cda-aab3-8b65fafc3b4f' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/lasair.jpg', updated_at=now() where id='9e606a70-8cef-4ce3-b0fe-0557bdf159e8' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/tuskkor.jpg', updated_at=now() where id='ab9bad3d-2b0c-4c2b-8b8d-50252f23a4a9' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/artor.jpg', updated_at=now() where id='d1d50cc9-2da8-4138-bad6-7e05c2a536f9' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/thisbe.jpg', updated_at=now() where id='c67dbcad-af36-49ef-90b7-67c9618a3745' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/loriaca.jpg', updated_at=now() where id='f6928807-a4ac-42b5-a6a8-f03b15162ba1' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/fren_zi.jpg', updated_at=now() where id='ffa31167-a5e6-4625-b75a-5743694a7ca7' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/riab.jpg', updated_at=now() where id='85dcabf7-7bbc-41c1-902f-3f7486684abd' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/knott.jpg', updated_at=now() where id='498e029e-c0ae-4ede-87ed-d8f4c509bdb0' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/fabian.jpg', updated_at=now() where id='adb6e11c-4e72-49ab-b096-91904ae9ecb9' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/isbeil.jpg', updated_at=now() where id='55e03ed1-b948-4f69-9430-52b5b44b56c9' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/tolog.jpg', updated_at=now() where id='3f4c7d33-ee28-4813-a96a-25b5d0a67fd2' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/islin.jpg', updated_at=now() where id='ab825a40-6c22-4d40-ac9b-bea7972799d9' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/mythical/krixia.jpg', updated_at=now() where id='0d775c36-6b4d-4903-82f1-606fcd0ffb0a' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/mythical/lazarius.jpg', updated_at=now() where id='6989047d-12f6-4d0a-a550-4dd0a9d87833' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/jorrg.jpg', updated_at=now() where id='ef5332a8-1b8f-4588-8518-cd02360c85ba' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/krok_mar.jpg', updated_at=now() where id='a6b23b96-ffc6-44a8-aca6-a04e5d9fa60c' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/jailer.jpg', updated_at=now() where id='3f3d4b68-99f2-4892-acdf-14189dd59b21' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/tirlac.jpg', updated_at=now() where id='8eb852bb-6324-4cee-a5cd-034b908fc553' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/colwyn.jpg', updated_at=now() where id='697fc243-40df-4d25-a6b5-511ac67d9a1a' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/ankora.jpg', updated_at=now() where id='1eed375c-b9a6-45f2-95c7-545559efea5b' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/mythical/galathir.jpg', updated_at=now() where id='d4964e4c-67af-4137-87cd-d31687bfe007' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/maud.jpg', updated_at=now() where id='7b5d14fe-a162-46cf-93ca-27cb06634731' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/narses.jpg', updated_at=now() where id='7023ffea-67b9-42e8-9b46-87d9aac33a08' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/flannan.jpg', updated_at=now() where id='214270e2-e447-434e-b866-1019fe8a494b' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/padraig.jpg', updated_at=now() where id='19904ab2-c6b2-4d47-bc25-8a5960766493' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/rare/taneko.jpg', updated_at=now() where id='76a2e8db-7f4d-4717-916b-2e80ea8a011a' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/adelyn.jpg', updated_at=now() where id='e367d6c7-30c5-4991-95f9-b57130c7b22d' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/othorion.jpg', updated_at=now() where id='0a442031-0625-4684-bacb-565c9ee5617f' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/wixwell.jpg', updated_at=now() where id='bcf948cb-ef87-4a46-b5ed-ac5e296548e4' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/greggor.jpg', updated_at=now() where id='2989fb5a-a1f5-473b-9b13-315e660afc2e' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/teox.jpg', updated_at=now() where id='6962ee3d-07e6-47fb-8e1e-6a41ba8e3509' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/lamasu.jpg', updated_at=now() where id='a9504e74-b2cc-4a3a-aa41-0fea63d09d0e' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/mythical/ash_nar.jpg', updated_at=now() where id='bcaef84c-eaf3-4894-97ae-a1cc10dab6ea' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/herakletes.jpg', updated_at=now() where id='6d374e05-a1c6-4225-af82-a33fba40c15a' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/mikey.jpg', updated_at=now() where id='fc4ad157-66c8-431a-a925-5ad23cf0db64' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/orn.jpg', updated_at=now() where id='cc745173-52ca-4a02-871c-b899a0f27fb0' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/marius.jpg', updated_at=now() where id='1085daa2-1eec-44d1-a6fe-8c9635b44bb5' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/epic/quargan.jpg', updated_at=now() where id='159c7242-8d9c-4086-baf1-6b071325c654' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/lanakis.jpg', updated_at=now() where id='6421ae45-0c1b-4cf8-af69-c8f53905544c' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/mavara.jpg', updated_at=now() where id='d0faf818-5d29-4530-8ab0-aee9edfab8aa' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/gnishak.jpg', updated_at=now() where id='7da92236-f47c-46a6-9e84-6b332de8e7b0' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/drexthar.jpg', updated_at=now() where id='1a2878c0-4245-4476-82df-87447035c416' and portrait_url is null;
update champions set portrait_url='https://bmuugbrevcukaeayqqwb.supabase.co/storage/v1/object/public/portraits/legendary/tholin.jpg', updated_at=now() where id='cd705c45-37b2-4943-9e77-a1d6775a2dc7' and portrait_url is null;
