-- ============================================================================
-- 2026-08-07 — NAME-ONLY corruption batch fix (30 champions) — APPLIED 2026-08-07 (119 rows, all rowCount=1)
--
-- Source: bad-bulk skill-name corruption audit. These champions were flagged ALL_WRONG by
-- tools/ayumilove-name-diff.mjs (DB skill NAMES from the raid.guide-derived "worksheet Skills
-- tab 2026-07-11" bulk = invented) but the MECHANICS DIFF classified them NAME-ONLY (jac >= 0.5:
-- DB skill_summary effects MATCH AyumiLove, so the kit is right and only the names are wrong).
-- Each skill is mapped to its AyumiLove counterpart by mechanic-token overlap (not blind position);
-- champions that did not map cleanly are NOT here (see the flagged list below) and need manual work.
--
-- Refreshes BOTH skill_name and skill_summary from AyumiLove (Tier-2 factual skill text; also closes
-- the minor mechanic gaps at the lower-jac end). verification_status=proposed (HUMAN REVIEW before
-- promoting to verified). Old (invented) name kept in review_notes. Worksheet writeback DONE 2026-08-07
-- (master Skills tab, 119 rows → name+summary+status 'Needs Review'; backup BACKUP-2026-08-07-preNameOnlyBatch.xlsx).
-- APPLIED to live DB 2026-08-07 via tools/apply-seed-pooler.mjs (verified: Keberon → Fiery Rend /
-- Searing Brand / Pyrenei Power / Underflame's Protection; Fu-Shan → Howl / Frightful Claws / Shred).
-- ============================================================================
begin;

-- Boragar  (jac 0.57, 4 skills)  id=849e49ac-6770-49f2-8de1-9d6fff502873
update champion_skills set skill_name='Antique Staff', skill_summary='Attacks 1 enemy. Has a 50% chance of placing a 60% [Increase DEF] buff for 1 turn on the ally with the lowest HP. Will not be placed on this Champion. Has a 100% chance instead if this attack is critical.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Ancient Staff" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='849e49ac-6770-49f2-8de1-9d6fff502873' and slot='A1';
update champion_skills set skill_name='Souls of Old Stone', skill_summary='Removes 1 random debuff from all allies, then places a [Shield] buff on all allies for 2 turns equal to 20% of this Champion''s MAX HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Rune of Shielding" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='849e49ac-6770-49f2-8de1-9d6fff502873' and slot='A2';
update champion_skills set skill_name='Rune of Energy', skill_summary='Places a 50% [Increase RES] buff and a 30% [Increase SPD] buff on all allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Rune of Warding" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='849e49ac-6770-49f2-8de1-9d6fff502873' and slot='A3';
update champion_skills set skill_name='Boragar''s Blazon', skill_summary='Allies receive 10% less damage from Champions whose RES is lower than or equal to theirs.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Elder''s Wisdom" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='849e49ac-6770-49f2-8de1-9d6fff502873' and slot='Passive';

-- Claidna  (jac 0.88, 4 skills)  id=50a681fc-8e03-4357-9867-ba9bc823eb22
update champion_skills set skill_name='Touch of Slumber', skill_summary='Attacks 1 enemy. Has a 80% chance of placing a [Sleep] debuff for 1 turn. Fills this Champion''s Turn Meter by 15% if the [Sleep] debuff is placed.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Whispering Slumber" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='50a681fc-8e03-4357-9867-ba9bc823eb22' and slot='A1';
update champion_skills set skill_name='Lost In The Woods', skill_summary='Has a 75% chance of placing a 30% [Decrease SPD] debuff and a [Leech] debuff on all enemies for 2 turns. Restores 100% of each ally''s destroyed MAX HP, then heals all allies by 20% of this Champion''s MAX HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Verdant Restoration" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='50a681fc-8e03-4357-9867-ba9bc823eb22' and slot='A2';
update champion_skills set skill_name='Otherworld Infusion', skill_summary='Removes all debuffs from all allies, then places a [Block Debuffs] buff and a [Revive on Death] buff on them for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Grovewarden''s Blessing" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='50a681fc-8e03-4357-9867-ba9bc823eb22' and slot='A3';
update champion_skills set skill_name='Fey Monarch', skill_summary='Has a 30% chance of completely blocking the incoming damage of the first hit of an attack on a random ally. Occurs once per turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Sylvan Aegis" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='50a681fc-8e03-4357-9867-ba9bc823eb22' and slot='A4';

-- Cromax  (jac 0.71, 4 skills)  id=4c181d46-8efb-4c6a-a5f6-c7b17468f3f7
update champion_skills set skill_name='Lunar Lance', skill_summary='Attacks 1 enemy. Has a 60% chance of placing a 50% [Decrease ATK] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Moonlit Edge" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4c181d46-8efb-4c6a-a5f6-c7b17468f3f7' and slot='A1';
update champion_skills set skill_name='Moonlight Bonds', skill_summary='Attacks 1 enemy. Has a 75% chance of placing a [Block Buffs] debuff for 2 turns. Also fills this Champion''s Turn Meter by 30%', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Umbral Curse" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4c181d46-8efb-4c6a-a5f6-c7b17468f3f7' and slot='A2';
update champion_skills set skill_name='Blood Moon', skill_summary='Attacks all enemies. Has a 75% chance of placing a [Provoke] debuff for 1 turn and a 50% [Decrease ACC] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Lunar Eclipse" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4c181d46-8efb-4c6a-a5f6-c7b17468f3f7' and slot='A3';
update champion_skills set skill_name='Silver Fear', skill_summary='When attacked, has a 35% chance of placing a [Hex] debuff on the attacker for 1 turn after each hit.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Blood Hex" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4c181d46-8efb-4c6a-a5f6-c7b17468f3f7' and slot='Passive';

-- Deephook Nagis  (jac 0.91, 4 skills)  id=d7113da8-d4b3-4503-9bd7-f450cadb1ced
update champion_skills set skill_name='Catching Prey', skill_summary='Attacks 1 enemy. Has a 40% chance of placing a [Provoke] debuff for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Hooking Jab" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='d7113da8-d4b3-4503-9bd7-f450cadb1ced' and slot='A1';
update champion_skills set skill_name='Tidal Cleanse', skill_summary='Removes all debuffs from this Champion and a single target ally. Places a 50% [Ally Protection] buff, a 25% [Strengthen] buff, and a 50% [Increase ATK] buff on that target ally for 2 turns. Then fills the Turn Meters of this Champion and the target ally by 15%.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Serpent''s Embrace" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='d7113da8-d4b3-4503-9bd7-f450cadb1ced' and slot='A2';
update champion_skills set skill_name='Sea Snake Surge', skill_summary='Attacks all enemies. Has an 80% chance of placing a 25% [Weaken] debuff for 2 turns. Also has a 40% chance of placing a [Stun] debuff for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Tidal Crash" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='d7113da8-d4b3-4503-9bd7-f450cadb1ced' and slot='A3';
update champion_skills set skill_name='Tritonean Might', skill_summary='[Active Effect] Whenever an enemy attacks this Champion, heals all allies by 10% of their MAX HP and fills their Turn Meters by 10%. Whenever an enemy attacks this Champion, also places a 30% [Increase SPD] buff on all allies for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Reactive Scales" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='d7113da8-d4b3-4503-9bd7-f450cadb1ced' and slot='A4';

-- Djamarsa  (jac 0.50, 4 skills)  id=c08a341d-0269-4875-864f-c68272a5eaa0
update champion_skills set skill_name='Night''s Finger', skill_summary='Attacks 1 enemy. Has a 30% chance of placing a [Sleep] debuff for 1 turn. If Crohnam is on the same team, and the [Sleep] debuff was resisted or blocked, place a 30% [Decrease SPD] debuff instead for 2 turns. This debuff cannot be blocked.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Mystic Touch" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='c08a341d-0269-4875-864f-c68272a5eaa0' and slot='A1';
update champion_skills set skill_name='Radiant Moon', skill_summary='Heals a target ally by 30% of their MAX HP and fills their Turn Meter by 30%. If this skill is used on Crohnam , he will instantly activate his Berserker''s Delight Skill.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Soothing Ritual" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='c08a341d-0269-4875-864f-c68272a5eaa0' and slot='A2';
update champion_skills set skill_name='Moonlit March', skill_summary='Revives all dead allies with 30% HP and 30% Turn Meter', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Mass Rebirth" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='c08a341d-0269-4875-864f-c68272a5eaa0' and slot='A3';
update champion_skills set skill_name='Phasing', skill_summary='Whenever an ally uses an Active Skill, has a 20% chance of decreasing the cooldown of that skill by 1 turn', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Fateful Twist" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='c08a341d-0269-4875-864f-c68272a5eaa0' and slot='A4';

-- Enda  (jac 0.67, 4 skills)  id=28175d91-7434-41b8-8028-cddbbe60bc2b
update champion_skills set skill_name='Silvern Slash', skill_summary='Attacks 1 enemy. Has a 30% chance of placing a 60% [Decrease DEF] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Glimmering Edge" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='28175d91-7434-41b8-8028-cddbbe60bc2b' and slot='A1';
update champion_skills set skill_name='Glimmer', skill_summary='Attacks 3 times at random. Each hit has a 75% chance of increasing the duration of a random debuff on the target by 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Lunar Flurry" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='28175d91-7434-41b8-8028-cddbbe60bc2b' and slot='A2';
update champion_skills set skill_name='Chain of Delusion', skill_summary='Attacks all enemies. Has a 75% chance of placing a [Leech] debuff on all enemies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Moonlit Sustenance" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='28175d91-7434-41b8-8028-cddbbe60bc2b' and slot='A3';
update champion_skills set skill_name='Lunar Cycle', skill_summary='Increases this champion''s SPD by 2 for each enemy under a [Leech] debuff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Lunar Swiftness" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='28175d91-7434-41b8-8028-cddbbe60bc2b' and slot='A4';

-- Fu-Shan  (jac 1.00, 3 skills)  id=e19dbba0-3d6f-41da-a94e-f3b62a2a51a2
update champion_skills set skill_name='Howl', skill_summary='Attacks 1 enemy. Has a 25% chance of placing an extra hit.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Pummel" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='e19dbba0-3d6f-41da-a94e-f3b62a2a51a2' and slot='A1';
update champion_skills set skill_name='Frightful Claws', skill_summary='Attacks all enemies 2 times. Each hit has a 20% chance of placing a [Stun] debuff for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Quake Stomp" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='e19dbba0-3d6f-41da-a94e-f3b62a2a51a2' and slot='A2';
update champion_skills set skill_name='Shred', skill_summary='Attacks 4 times at random. Each hit has a 50% chance of placing a 60% [Decrease DEF] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Shatter Defenses" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='e19dbba0-3d6f-41da-a94e-f3b62a2a51a2' and slot='A3';

-- Galapo  (jac 1.00, 4 skills)  id=fdc456cf-e6a4-4cf1-bb94-c842a91ac8e9
update champion_skills set skill_name='Roll with the Times', skill_summary='Attacks all enemies. Heals this Champion by 5% of their MAX HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Sewer Lash" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='fdc456cf-e6a4-4cf1-bb94-c842a91ac8e9' and slot='A1';
update champion_skills set skill_name='Reclusive Sage', skill_summary='Heals all allies by 15% of this Champion''s MAX HP, and fills the Turn Meters of all allies by 15%. Also places a 25% [Increase RES] buff on all allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Mending Mist" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='fdc456cf-e6a4-4cf1-bb94-c842a91ac8e9' and slot='A2';
update champion_skills set skill_name='You''ve Much to Learn', skill_summary='Revives an ally with 75% HP and 50% Turn Meter. Places an [Unkillable] buff and a 30% [Reflect Damage] buff on that ally for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Dragonkin''s Gift" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='fdc456cf-e6a4-4cf1-bb94-c842a91ac8e9' and slot='A3';
update champion_skills set skill_name='Outliver of Empires', skill_summary='Heals this Champion by 25% of their MAX HP whenever an ally dies. Heals all allies by 50% of this Champion''s MAX HP whenever this Champion dies. Heal Multiplier: 0.25 HP', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Final Wish" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='fdc456cf-e6a4-4cf1-bb94-c842a91ac8e9' and slot='Passive';

-- Kassandra  (jac 0.92, 5 skills)  id=db839513-9cb3-42a7-8a0b-2463d4785350
update champion_skills set skill_name='West Wind Rush', skill_summary='Attacks 1 enemy 3 times. Attacks 1 enemy 6 times instead if this Champion has 50% HP or less. Each hit decreases the enemy''s Turn Meter by 7.5% and increases this Champion''s Turn Meter by 7.5%. This effect cannot be resisted if this Champion is under a [Veil] or [Perfect Veil] buff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Piercing Strikes" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='db839513-9cb3-42a7-8a0b-2463d4785350' and slot='A1';
update champion_skills set skill_name='Spear Of Leonidas', skill_summary='Attacks 1 enemy. Before attacking, places a 60% [Decrease DEF] debuff and a [HP Burn] debuff on the target for 3 turns. These debuffs cannot be resisted if this Champion is under a [Veil] or [Perfect Veil] buff. Places a [Stun] debuff on all enemies for 1 turn if the damage dealt by this skill is more than 50% of target''s MAX HP. This debuff cannot be resisted if this Champion is under a [Veil] or [Perfect Veil] buff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Debilitating Blow" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='db839513-9cb3-42a7-8a0b-2463d4785350' and slot='A2';
update champion_skills set skill_name='Isu''s Blessing', skill_summary='Removes all debuffs from this Champion, heals them by 50% of their MAX HP, and fills their Turn Meter by 50%. Places a 50% [Increase ATK] buff, a 15% [Shatter] buff, and a 30% [Increase SPD] buff on this Champion for 2 turns. [Passive Effect] Prevents this Champion''s death and keeps them alive on 1 HP if they are under an [Increase ATK] buff, [Shatter] buff, and [Increase SPD] buff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Warrior''s Resolve" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='db839513-9cb3-42a7-8a0b-2463d4785350' and slot='A3';
update champion_skills set skill_name='Everything Is Permitted', skill_summary='Whenever an enemy''s HP drops below 25% after receiving damage from any Assassin, they receive additional bonus damage proportional to this Champion''s ATK. This bonus damage will ignore 100% of the target''s DEF and cannot be critical.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Combat Prowess" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='db839513-9cb3-42a7-8a0b-2463d4785350' and slot='A5';
update champion_skills set skill_name='Blood Of Sparta', skill_summary='Whenever this Champion attacks an enemy, increases this Champion''s ATK by an amount equal to 50% of the target''s DEF. Whenever an enemy attacks this Champion, increases this Champion''s DEF by an amount equal to 50% of the attacker''s ATK.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Assassin''s Cunning" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='db839513-9cb3-42a7-8a0b-2463d4785350' and slot='Passive';

-- Keberon  (jac 0.56, 4 skills)  id=4ff3953d-6213-4f49-b9e7-b746ec939010
update champion_skills set skill_name='Fiery Rend', skill_summary='Attacks 1 enemy 2 times. Has a 75% chance of placing a 60% [Decrease DEF] debuff for 2 turns. Has a 50% chance of attacking with this skill whenever an enemy has a [HP Burn] debuff activated on them. Occurs once per turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Searing Mark" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4ff3953d-6213-4f49-b9e7-b746ec939010' and slot='A1';
update champion_skills set skill_name='Searing Brand', skill_summary='Attacks 1 enemy 2 times. Before attacking, places a [Deathbrand] debuff on the target for 2 turns. Will ignore [Unkillable] and [Shield] buffs, as well as 25% of the target''s DEF. Activates this Champion''s Pyrenei Power skill if the target is killed. If the target survives, fills this Champion''s Turn Meter by 50% instead.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Brand of Damnation" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4ff3953d-6213-4f49-b9e7-b746ec939010' and slot='A2';
update champion_skills set skill_name='Pyrenei Power', skill_summary='Attacks all enemies. Before attacking, places a 50% [Increase ACC] buff on all allies for 2 turns. Has a 75% chance of placing a [HP Burn] debuff on all enemies for 2 turns. Fills this Champion''s Turn Meter by 20% for each [HP Burn] debuff placed on enemies, and fills this Champion''s Turn Meter by 10% for each [HP Burn] debuff resisted by enemies.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Infernal Eruption" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4ff3953d-6213-4f49-b9e7-b746ec939010' and slot='A3';
update champion_skills set skill_name='Underflame''s Protection', skill_summary='[Active Effect] Activates a [Delay] effect on this Champion whenever they receive a fatal hit. [Passive Effect] Heals this Champion by 20% of their MAX HP whenever a [HP Burn] debuff is activated on an enemy. Whenever a [HP Burn] debuff on an enemy expires or is removed, places a [True Fear] debuff on that enemy for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Underflame''s Resilience" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4ff3953d-6213-4f49-b9e7-b746ec939010' and slot='A4';

-- King Gallcobar  (jac 0.71, 4 skills)  id=1f83da97-dd65-4beb-bb4a-8e62b4910656
update champion_skills set skill_name='Tanglestaff', skill_summary='Attacks 1 enemy. Places a [Shield] buff for 2 turns on the ally with the lowest HP. The value of the [Shield] is equal to 15% of the ally''s MAX HP', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Cobra Lash" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='1f83da97-dd65-4beb-bb4a-8e62b4910656' and slot='A1';
update champion_skills set skill_name='Vitriolic Thorns', skill_summary='Attacks all enemies. Has an 80% chance of removing all buffs. Places a 5% [Poison] debuff for 2 turns on each enemy for every buff removed from them. Also has an 80% chance of placing a [Block Buffs] debuff on all enemies for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Venomous Overload" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='1f83da97-dd65-4beb-bb4a-8e62b4910656' and slot='A2';
update champion_skills set skill_name='Hypertrophy', skill_summary='Removes all debuffs from all allies. Places a 15% [Continuous Heal] buff for 1 turn on each ally for every debuff removed from them. Also places a [Shield] buff on all allies for 2 turns. The value of the [Shield] is equal to 25% of this Champion''s MAX HP', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "King''s Protection" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='1f83da97-dd65-4beb-bb4a-8e62b4910656' and slot='A3';
update champion_skills set skill_name='Bramble Shaman', skill_summary='Whenever an enemy under a [Poison] debuff attacks an ally under a [Shield] buff, instantly activates 1 [Poison] debuff on that enemy. Also instantly activates 1 [Continuous Heal] buff on the attacked ally.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Serpent''s Spite" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='1f83da97-dd65-4beb-bb4a-8e62b4910656' and slot='Passive';

-- Klaazag  (jac 0.90, 4 skills)  id=6d6ca3ef-877b-4fec-b855-b1a3e981be51
update champion_skills set skill_name='Dreadtone', skill_summary='Attacks 1 enemy. Transfers all debuffs from this Champion to the target before the attack. Has a 75% chance of placing a [True Fear] debuff for 1 turn. This debuff cannot be resisted by Bosses.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Fearful Exchange" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6d6ca3ef-877b-4fec-b855-b1a3e981be51' and slot='A1';
update champion_skills set skill_name='Seismic Dissonance', skill_summary='Attacks all enemies 2 times. After the first hit, has a 75% chance of placing a 60% [Decrease DEF] debuff and a 25% [Weaken] debuff on all enemies for 2 turns. These debuffs cannot be resisted by Bosses. After the second hit, has a 75% chance of placing a 50% [Decrease ACC] debuff and a 50% [Decrease RES] debuff on all enemies for 2 turns. These debuffs cannot be resisted by Bosses.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Overwhelming Curse" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6d6ca3ef-877b-4fec-b855-b1a3e981be51' and slot='A2';
update champion_skills set skill_name='Mindless Muscle', skill_summary='Places a [Counterattack] buff on all allies for 2 turns, and an [Unkillable] buff on allies for 1 turn. Also places a [Taunt] buff on this Champion for 2 turns. If a Boss is present in the current Round, these buffs are protected.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Keyhulk''s Guard" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6d6ca3ef-877b-4fec-b855-b1a3e981be51' and slot='A3';
update champion_skills set skill_name='Drone of Agony', skill_summary='Whenever this Champion places a debuff on an enemy, deals damage equal to 1% of their MAX HP for each debuff they are currently under. (Stacks up to 10%). Occurs once per skill and once per target.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Debilitating Force" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6d6ca3ef-877b-4fec-b855-b1a3e981be51' and slot='Passive';

-- Knosson  (jac 0.75, 4 skills)  id=da03cf65-2178-4a80-8369-8ec87dfa5e8f
update champion_skills set skill_name='Strength of Lakon', skill_summary='Attacks 1 enemy. Destroys 10% of the target''s MAX HP. Destroys 20% of the target''s MAX HP instead if the target is under a [Provoke] debuff (stacks up to 50%). Increases this Champion''s Turn Meter by 20%. Increases this Champion''s Turn Meter by 40% instead if the target is under a [Provoke] debuff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Crushing Horns" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='da03cf65-2178-4a80-8369-8ec87dfa5e8f' and slot='A1';
update champion_skills set skill_name='By The Horns', skill_summary='Attacks 1 enemy. Will ignore 50% of the target''s DEF and any [Stone Skin] buffs if this Champion''s MAX HP is greater than the target''s. If the target is killed, instantly activates the Hard-earned Confidence skill. If the target survives, heals all allies by an amount equal to the difference between the target''s current HP and MAX HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Unstoppable Charge" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='da03cf65-2178-4a80-8369-8ec87dfa5e8f' and slot='A2';
update champion_skills set skill_name='Hard-earned Confidence', skill_summary='Attacks all enemies. Has a 80% chance of placing a [Provoke] debuff on all enemies for 1 turn. Will ignore 50% RES against targets whose MAX HP is lower than this Champion''s. Places a [Counterattack] buff on this Champion for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Bronze Rage" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='da03cf65-2178-4a80-8369-8ec87dfa5e8f' and slot='A3';
update champion_skills set skill_name='Is That All You''ve Got?', skill_summary='Enemies under [Provoke] debuffs deal 50% less damage. Allies deal 20% more damage against enemies under [Provoke] debuffs. If there are multiple Champions on the team with this skill, only one will activate. This skill will not activate on duplicate copies of this Champion, if this particular Champion is dead.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Goring Presence" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='da03cf65-2178-4a80-8369-8ec87dfa5e8f' and slot='A4';

-- Korugar  (jac 0.50, 4 skills)  id=5d428674-0a8d-4cdd-8607-97d9ce67c9ce
update champion_skills set skill_name='Strange Animus', skill_summary='Attacks 1 enemy. Heals this champion by 10% of their MAX HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Molten Axe" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='5d428674-0a8d-4cdd-8607-97d9ce67c9ce' and slot='A1';
update champion_skills set skill_name='Bell''s Toll', skill_summary='Attacks all enemies. Has a 75% chance of filling the Turn Meters of all allies by 30%. Also has a 75% chance of removing all debuffs from all allies.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Cleanse and Boost" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='5d428674-0a8d-4cdd-8607-97d9ce67c9ce' and slot='A2';
update champion_skills set skill_name='Conduit of Agonies', skill_summary='Places a 50% [Ally Protection] buff on all allies except this champion for 2 turns. Also places a 25% [Strengthen] buff on all allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Team Protection" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='5d428674-0a8d-4cdd-8607-97d9ce67c9ce' and slot='A3';
update champion_skills set skill_name='Violence Locus', skill_summary='Increases this champion''s RES by 20 and DEF by 10% for each [Ally Protection] buff on allies. Also increases ally RES by 15 and DEF by 5% for each [Ally Protection] buff on allies. If there are multiple Champions on the team with this skill, only one will activate. Counterattacks whenever an ally under an [Ally Protection] buff is attacked. Can occur once per enemy turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Stat Boost" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='5d428674-0a8d-4cdd-8607-97d9ce67c9ce' and slot='A4';

-- Kroz  (jac 0.67, 4 skills)  id=4969ec7f-5ab6-46fe-acae-0b1bb4f76917
update champion_skills set skill_name='Pulverizing Pummel', skill_summary='Attacks 1 enemy 3 times. Each hit has a 30% chance of decreasing the detonation countdown of all [Bomb] debuffs on the target by 1 turn. Also has a 30% chance of placing a [Stun] debuff on the target for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Skull Sunder" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4969ec7f-5ab6-46fe-acae-0b1bb4f76917' and slot='A1';
update champion_skills set skill_name='Battlefield Sapper', skill_summary='Has a 75% chance of placing 2 [Bomb] debuffs on each enemy that detonate after 2 turns. Fills this Champion''s Turn Meter by 25% for each enemy with a [Bomb] debuff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Bombardment Plan" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4969ec7f-5ab6-46fe-acae-0b1bb4f76917' and slot='A2';
update champion_skills set skill_name='Mangonel Maul', skill_summary='Attacks all enemies. Has a 75% chance of decreasing the detonation countdown of all [Bomb] debuffs by 1 turn. Also has a 75% chance of placing a [Block Active Skills] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Triggering Charge" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4969ec7f-5ab6-46fe-acae-0b1bb4f76917' and slot='A3';
update champion_skills set skill_name='Bomb Breacher', skill_summary='Fills all allies'' Turn Meters by 5% each time a [Bomb] debuff detonates. Has a 20% chance of activating an [Instant Turn] effect on this Champion whenever an ally or an enemy is killed by a [Bomb] debuff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Chain Reaction" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='4969ec7f-5ab6-46fe-acae-0b1bb4f76917' and slot='Passive';

-- Lady Noelle  (jac 0.60, 4 skills)  id=90ce7b2d-a332-4472-895e-1b46b4893884
update champion_skills set skill_name='Icecrack staff', skill_summary='Attacks 1 enemy. Has an 80% chance of placing a [Block Buffs] debuff for 2 turns. Also decreases the target''s Turn Meter by 20% if they are under a [Freeze] debuff. These effects cannot be resisted if Sir Nicholas is on the same team.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Frigid Judgment" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='90ce7b2d-a332-4472-895e-1b46b4893884' and slot='A1';
update champion_skills set skill_name='Invigorating Chill', skill_summary='Target an ally. if the target ally is under a [Sheep] debuff, removes it. If the target ally is not under a [Sheep] debuff, removes all debuffs instead. If the target ally is not under a [Sheep] debuff, heals them by 50% of this Champion''s MAX HP. Also heals all allies equal to 50% of any surplus heal. If the target ally is Sir Nicholas, instantly activates his Goodwill skill. Then places a 30% [Increase SPD] buff on all allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Winter''s Solace" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='90ce7b2d-a332-4472-895e-1b46b4893884' and slot='A2';
update champion_skills set skill_name='Hearthkeeper', skill_summary='Revives all dead allies with 50% HP and 50% Turn Meter. Then has a 75% chance of placing a [Freeze] debuff on all enemies for 1 turn. Will place the [Freeze] debuff even if there are no dead allies. This debuff cannot be resisted or blocked if Sir Nicholas is on the same team.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Noelle''s Gift" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='90ce7b2d-a332-4472-895e-1b46b4893884' and slot='A3';
update champion_skills set skill_name='Cyromatic Queen', skill_summary='Decreases the SPD of enemies under [Freeze] debuffs by 10%. When a [Sheep] debuff expires on an ally, fills their Turn Meter by 50%. If there are multiple Champions on the team with the skill, these effects will only activate once.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Grandmother''s Favor" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='90ce7b2d-a332-4472-895e-1b46b4893884' and slot='A4';

-- Leminisi  (jac 1.00, 4 skills)  id=07f240e5-739c-4dbd-af04-77abc07b3ccf
update champion_skills set skill_name='Auric Talons', skill_summary='Attacks 1 enemy 2 times. If the target is under a [Shield] buff, each hit has a 25% chance of decreasing the value of the [Shield] by 10%. Will also ignore 50% of the target''s RES if the target is from the Corrupted Alliance. If the target is not under any [Shield] buffs, each hit will ignore 10% of the target''s DEF instead.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Gilded Blades" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='07f240e5-739c-4dbd-af04-77abc07b3ccf' and slot='A1';
update champion_skills set skill_name='Intercept The Threat', skill_summary='Attacks 1 enemy 2 times. Each hit has a 100% chance of removing 2 random buffs from the target. Will also ignore 50% of the target''s RES if the target is from the Corrupted Alliance. This skill deals more damage equal to the value of the target''s current Turn Meter (stacks up to 100%).', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Winged Fury" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='07f240e5-739c-4dbd-af04-77abc07b3ccf' and slot='A2';
update champion_skills set skill_name='Venerated Warrior', skill_summary='Attacks all enemies 2 times. The first hit has a 75% chance of placing a 100% [Heal Reduction] debuff for 2 turns. The second hit has a 50% chance of placing a [Block Buffs] debuff for 2 turns. Will also ignore 50% of the target''s RES if the target is from the Corrupted Alliance.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Celestial Rebuke" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='07f240e5-739c-4dbd-af04-77abc07b3ccf' and slot='A3';
update champion_skills set skill_name='Scourge Of Evil', skill_summary='Receives 15% less damage from enemies under [Heal Reduction] debuffs. Fills this Champion''s Turn Meter by 5% whenever an enemy receives a [Shield] buff or is healed.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Spirit''s Aegis" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='07f240e5-739c-4dbd-af04-77abc07b3ccf' and slot='Passive';

-- Liburga  (jac 1.00, 4 skills)  id=6ed80ef6-c258-498a-90a8-ae324775c31c
update champion_skills set skill_name='Dripping Down', skill_summary='Attacks 1 enemy. Has a 50% chance of placing a 5% [Poison] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Noxious Bite" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6ed80ef6-c258-498a-90a8-ae324775c31c' and slot='A1';
update champion_skills set skill_name='Boil From Within', skill_summary='Attacks 1 enemy. Has a 75% chance of placing two 5% [Poison] debuffs and a 25% [Poison Sensitivity] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Corrupting Touch" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6ed80ef6-c258-498a-90a8-ae324775c31c' and slot='A2';
update champion_skills set skill_name='Vigor Bloom', skill_summary='Places a 60% [Increase DEF] buff and a 50% [Increase ATK] buff on all allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "War Leader" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6ed80ef6-c258-498a-90a8-ae324775c31c' and slot='A3';
update champion_skills set skill_name='Irradiate', skill_summary='When attacked, has a 50% chance of increasing the duration of all [Poison] debuffs on the attacker by 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Venomous Skin" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='6ed80ef6-c258-498a-90a8-ae324775c31c' and slot='Passive';

-- Lord Entertainer Fabian  (jac 0.56, 4 skills)  id=adb6e11c-4e72-49ab-b096-91904ae9ecb9
update champion_skills set skill_name='Service In Death', skill_summary='Attacks 1 enemy 2 times. Each hit steals 10% of the target''s Turn Meter. Places a [True Fear] debuff for 2 turns if the target''s Turn Meter is fully depleted.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Disrupting Flourish" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='adb6e11c-4e72-49ab-b096-91904ae9ecb9' and slot='A1';
update champion_skills set skill_name='Unwelcome Guest', skill_summary='Attacks 1 enemy. Places a [Petrification] debuff for 1 turn. Has a 75% chance of placing a [True Fear] debuff for 2 turns on all other enemies who are not under a [Fear] or [True Fear] debuff. [Passive Effect] Activates this skill whenever an enemy under a [Fear] or [True Fear] debuff successfully uses a skill. If there are multiple Champions on the team with this skill, only one will activate.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Chilling Performance" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='adb6e11c-4e72-49ab-b096-91904ae9ecb9' and slot='A2';
update champion_skills set skill_name='Spectral Flourish', skill_summary='Attacks all enemies. Before attacking, has a 75% chance of decreasing the duration of all enemy buffs by 3 turns. Has a 75% chance of increasing the cooldowns of all enemy skills by 3 turns. Grants an Extra Turn if there are no buffs on the enemy team after this attack.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Grand Finale" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='adb6e11c-4e72-49ab-b096-91904ae9ecb9' and slot='A3';
update champion_skills set skill_name='Ghost With The Most', skill_summary='Whenever an enemy is revived, places a [True Fear] debuff on that enemy for 2 turns. If there are multiple Champions on the team with this skill, this effect will only activate once. Removes any [Stun], [Freeze], [Provoke], [Fear], [True Fear], and [Petrification] debuffs from this Champion before the start of their turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Unending Encore" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='adb6e11c-4e72-49ab-b096-91904ae9ecb9' and slot='Passive';

-- Losan K'Leth  (jac 0.55, 4 skills)  id=597f0699-f70e-4842-9398-959fcbef5a38
update champion_skills set skill_name='Atrophic Ax', skill_summary='Attacks 1 enemy. Has an 80% chance of placing a 25% [Weaken] debuff for 2 turns. This debuff cannot be resisted if the target has attacked this Champion before this turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Astropic Axe" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='597f0699-f70e-4842-9398-959fcbef5a38' and slot='A1';
update champion_skills set skill_name='Spirit Calculus', skill_summary='The HP levels of all allies will be brought up to the level of the ally with the highest HP. The Turn Meter levels of all allies will be brought up to the level of the ally with the highest Turn Meter. The HP levels of all enemies will be brought down to the level of the enemy with the lowest HP. The Turn Meter levels of all enemies will be brought down to the level of the enemy with the lowest Turn Meter. Then places a [Taunt] buff on this Champion for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Unity''s Equilibrium" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='597f0699-f70e-4842-9398-959fcbef5a38' and slot='A2';
update champion_skills set skill_name='Finality Disc', skill_summary='Attacks 1 enemy. Before attacking, transfers all debuffs from this Champion to the target and heals this Champion by 10% of their MAX HP. Heals by an additional 10% of their MAX HP for each debuff transferred. Will always use this skill instead of the default skill when counterattacking.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Spirit Siphon" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='597f0699-f70e-4842-9398-959fcbef5a38' and slot='A3';
update champion_skills set skill_name='The Representation', skill_summary='Every time this Champion loses 25% HP or more from a single hit, places a [Block Damage] buff on this Champion for 1 turn. ★★★ Knights Revenant Unity ★★★ 1 Faction Ally: When attacked, has a 15% chance of placing a [True Fear] debuff on the attacker for 1 turn. This debuff cannot be resisted. 2 Faction Ally: Ignore DEF effects against this Champion are decreased by 100%. 3 Faction Ally: When attacked, has a 20% chance of activating an [Instant Turn] effect on this Champion. Occurs once per skill.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Grand Protector" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='597f0699-f70e-4842-9398-959fcbef5a38' and slot='Passive';

-- Maranix  (jac 1.00, 4 skills)  id=3ebdc6d9-7999-498d-a6b8-ae3671143527
update champion_skills set skill_name='Reaper''s Due', skill_summary='Attacks 1 enemy 2 times. Has a 50% chance to place up to 2 extra hits if the target is under [Hex] Debuff. The chance to place an extra hit is calculated individually per hit.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Slicing Gale" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='3ebdc6d9-7999-498d-a6b8-ae3671143527' and slot='A1';
update champion_skills set skill_name='Excruciate', skill_summary='Attacks all enemies. Has a 75% chance of placing a [Hex] Debuff and 60% [Decrease DEF] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Witching Blades" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='3ebdc6d9-7999-498d-a6b8-ae3671143527' and slot='A2';
update champion_skills set skill_name='Inexortable End', skill_summary='Attacks all enemies. Will ignore [Unkillable] buffs and [Shield] buffs if the target is under [Hex] debuff. Places a [Unkillable] buff on this Champion for 1 turn if this attack kills an enemy without a [Hex] debuff. Places a [Unkillable] buff for 2 turns instead if this attack kills an enemy under a [Hex] Debuff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Hex-Reaper" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='3ebdc6d9-7999-498d-a6b8-ae3671143527' and slot='A3';
update champion_skills set skill_name='Death''s Collector', skill_summary='Resets the cooldown of the Inexorable End Skill whenever this champion kills an enemy under a [Hex] Debuff. Increases this Champion''s ATK by 5% for each enemy under a [Hex] debuff.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Witchlight Barrier" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='3ebdc6d9-7999-498d-a6b8-ae3671143527' and slot='A4';

-- Marichka  (jac 0.75, 4 skills)  id=f36fc02d-fa99-4111-a751-ddc711de9741
update champion_skills set skill_name='United We Triumph', skill_summary='Attacks 1 enemy. One random ally will team up and join the attacks. The ally joining the attack will always use their default skill. If Taras the Fiece is on the same team, they will always be the ones to join this Champion''s attack.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Joint Strike" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='f36fc02d-fa99-4111-a751-ddc711de9741' and slot='A1';
update champion_skills set skill_name='Font of Tenacity', skill_summary='Fully restores any allies'' decreased MAX HP, then heals all allies by 40% of this Champion''s MAX HP. Places a [Shield] buff and a protected [Strengthen] buff on all allies for 2 turns. The value of the [Shield] buff is equal to 20% of this Champion''s MAX HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Unbreakable Bulwark" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='f36fc02d-fa99-4111-a751-ddc711de9741' and slot='A2';
update champion_skills set skill_name='Nurtured Friendship', skill_summary='Removes all debuffs from all allies, then fills the Turn Meters of all allies by 15%. Fills the Turn Meters of each ally by an extra 5% for each debuff removed from them. Increases the RES of allies by 5 for each debuff removed. Grants an Extra Turn if 5 or more debuffs were removed.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Resolute Cleanse" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='f36fc02d-fa99-4111-a751-ddc711de9741' and slot='A3';
update champion_skills set skill_name='Giving All', skill_summary='[Passive Effect] Revives all dead allies with 50% HP and 75% Turn Meter whenever this Champion is killed. [Active Effect] Places a [Block Damage] buff on all allies for 1 turn whenever an ally receives a [Bomb], [Poison], or [HP Burn] debuff. If there are multiple Champions on the team with this Skill, only one will activate. This skill''s cooldown only applies to its Active Effect', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Last Stand" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='f36fc02d-fa99-4111-a751-ddc711de9741' and slot='Passive';

-- Old Ghrukkus  (jac 1.00, 3 skills)  id=b77b5f3f-4671-4195-a982-ba5914bd6cf0
update champion_skills set skill_name='Beating Staff', skill_summary='Attack 1 enemy 3 times. Each hit has a 15% chance of placing a [Leech] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Skull Rattle" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='b77b5f3f-4671-4195-a982-ba5914bd6cf0' and slot='A1';
update champion_skills set skill_name='Toe the Line', skill_summary='Attacks 1 enemy. Has a 60% chance of placing a 30% [Decrease SPD] debuff for 2 turns. Also has a 40% chance of decreasing the target''s Turn Meter by 30%.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Ghastly Chimes" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='b77b5f3f-4671-4195-a982-ba5914bd6cf0' and slot='A2';
update champion_skills set skill_name='Harsh Discipline', skill_summary='Attacks all enemies. Has an 80% chance of placing a 50% [Decrease ATK] debuff and a 100% [Heal Reduction] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Cacophonous Dirge" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='b77b5f3f-4671-4195-a982-ba5914bd6cf0' and slot='A3';

-- Pontiff Augustin  (jac 0.77, 4 skills)  id=af36750e-4916-4543-b669-ea1b80e373f4
update champion_skills set skill_name='Edenic Blades', skill_summary='Attacks 1 enemy. Has a 75% chance of placing a [Block Active Skills] debuff for 2 turns. Steals 5% of the target''s Turn Meter for each buff on them.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Holy Strike" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='af36750e-4916-4543-b669-ea1b80e373f4' and slot='A1';
update champion_skills set skill_name='Shackle The Unjust', skill_summary='Removes all buffs from all enemies. Has a 75% chance of placing a 100% [Ensnare] debuff on all enemies for 2 turns. This debuff will ignore any [Block Debuffs] buffs on enemies under 3 or more buffs. Also decreases the Turn Meters of all enemies by 25%. If an enemy is under 3 or more buffs, will decrease their Turn Meter by 40% instead.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Divine Intervention" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='af36750e-4916-4543-b669-ea1b80e373f4' and slot='A2';
update champion_skills set skill_name='Ethereal Benediction', skill_summary='Places a 50% [Increase ACC] buff for 2 turns and 1 [Intercept] stack on all allies. Also fills the Turn Meters of all allies by 25%. Then grants an Extra Turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Sacred Rite" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='af36750e-4916-4543-b669-ea1b80e373f4' and slot='A3';
update champion_skills set skill_name='Your Eminence', skill_summary='Allies receive 25% less damage from enemies under [Block Damage], [Unkillable], [Veil], [Perfect Veil], or [Stone Skin] buffs. Each time an enemy receives a buff, is healed, or has their Turn Meter filled, has a 50% chance to decrease the duration of all their buffs by 1 turn. Occurs once per skill and once per target. If there are multiple Champions on the team with this skill, only one will activate. This skill will not activate on duplicate copies of this Champion, if this particular Champion is dead.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Vigilant Protector" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='af36750e-4916-4543-b669-ea1b80e373f4' and slot='A4';

-- Taras  (jac 0.63, 5 skills)  id=93ce1922-3ef0-4fff-aafb-9ae5c48032d2
update champion_skills set skill_name='Shatter Upon Us', skill_summary='Attacks 1 enemy 2 times. Has a 40% chance of placing a 50% [Decrease ATK] debuff for 2 turns. Each critical hit fills the Turn Meters of all allies by 5%', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Attack 1" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='93ce1922-3ef0-4fff-aafb-9ae5c48032d2' and slot='A1';
update champion_skills set skill_name='Hero''s Intercession', skill_summary='Attacks 1 enemy. Places a [Stun] debuff for 2 turns. Deals double damage to enemies whose ATK is equal to or higher than this Champion''s ATK. [Passive Effect] Whenever an enemy attacks Marichka the Unbreakable, attacks that enemy using this skill.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Attack 2" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='93ce1922-3ef0-4fff-aafb-9ae5c48032d2' and slot='A2';
update champion_skills set skill_name='Constant Pressure', skill_summary='Attacks all enemies. Damage increases by 15% for each buff on allies. Then increases the duration of all ally buffs by 1 turn. Heals this Champion by 5% for every buff that had its duration increased. Restores decreased MAX HP equal to the amount of any surplus heal.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Attack 3" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='93ce1922-3ef0-4fff-aafb-9ae5c48032d2' and slot='A3';
update champion_skills set skill_name='Fierce Battler', skill_summary='[Passive Effect] When attacked, decreased the enemy''s ATK by 10% (up to 50%; 25% against Bosses). Occurs once per skill. ATK Reduction resets after each Round. [Active Effect] Places a [Fear] debuff on all enemies from the Orcs, Ogryn Tribes, Undead Hordes, and Demonspawn Factions at the beginning of each Round. This debuff cannot be resisted.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Passive 1" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='93ce1922-3ef0-4fff-aafb-9ae5c48032d2' and slot='A4';
update champion_skills set skill_name='Poise', skill_summary='All incoming damage from skills is reduced by 50%. When attacked, this Champion''s MAX HP will be decreased by 25% of the attack''s initial damage (before the damage reduction).', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Passive 2" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='93ce1922-3ef0-4fff-aafb-9ae5c48032d2' and slot='A5';

-- Tatura  (jac 0.88, 4 skills)  id=2e96c545-5aa1-4dd4-8223-db5dcf64c8ee
update champion_skills set skill_name='Solar Ray', skill_summary='Attacks 1 enemy. Has an 80% chance of placing a 50% [Decrease ACC] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Skill 1" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='2e96c545-5aa1-4dd4-8223-db5dcf64c8ee' and slot='A1';
update champion_skills set skill_name='Wings of Shelter', skill_summary='Places a [Block Debuffs] buff and a 60% [Increase DEF] buff on all allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Skill 2" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='2e96c545-5aa1-4dd4-8223-db5dcf64c8ee' and slot='A2';
update champion_skills set skill_name='Otherworld Breach', skill_summary='Attacks all enemies. Places a [Perfect Veil] buff on all allies except this Champion for 2 turns. Also places a [Shield] buff on this Champion for 2 turns equal to 20% of the damage inflicted.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Skill 3" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='2e96c545-5aa1-4dd4-8223-db5dcf64c8ee' and slot='A3';
update champion_skills set skill_name='Glimmer Hide', skill_summary='When attacked, reflects 30% of the damage this Champion receives back to the attacker. Also has a 30% chance of placing a [Freeze] debuff on the attacker for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Passive Skill" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='2e96c545-5aa1-4dd4-8223-db5dcf64c8ee' and slot='A4';

-- Thorn  (jac 0.80, 4 skills)  id=9455f0bb-61ef-4365-9e17-c04e25dd786c
update champion_skills set skill_name='Vineblades', skill_summary='Attacks 1 enemy 2 times. Each hit has a 25% chance of placing a [Leech] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Barbed Lash" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='9455f0bb-61ef-4365-9e17-c04e25dd786c' and slot='A1';
update champion_skills set skill_name='Horrifying Visage', skill_summary='Attacks all enemies 2 times. The first hit has a 75% chance of placing a [Fear] debuff for 1 turn. The second hit has a 75% chance of placing a 50% [Decrease ACC] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Dreadful Splinters" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='9455f0bb-61ef-4365-9e17-c04e25dd786c' and slot='A2';
update champion_skills set skill_name='One With Corruption', skill_summary='Places a 60% [Increase DEF] buff on all allies for 2 turns. Also places a [Counterattack] buff and a 50% [Increase RES] buff on this Champion for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Bulwark of Thorns" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='9455f0bb-61ef-4365-9e17-c04e25dd786c' and slot='A3';
update champion_skills set skill_name='Dark Sustenance', skill_summary='Before this Champion uses a skill to deal damage, heals this Champion. The value of the heal is proportional to this Champion''s DEF. Heal Multiplier: 0.5 DEF', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Living Wood" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='9455f0bb-61ef-4365-9e17-c04e25dd786c' and slot='A4';

-- Tomoe  (jac 0.88, 4 skills)  id=7531ef09-1cfe-4774-86c6-af00df366ef8
update champion_skills set skill_name='Stab and Grab', skill_summary='Attacks 1 enemy. Has a 30% chance of stealing 1 random buff from the target.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Elegant Cut" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='7531ef09-1cfe-4774-86c6-af00df366ef8' and slot='A1';
update champion_skills set skill_name='Bamboozle', skill_summary='Attacks all enemies. Has a 75% chance of placing a 50% [Decrease ATK] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Fan Dance" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='7531ef09-1cfe-4774-86c6-af00df366ef8' and slot='A2';
update champion_skills set skill_name='Thick as Thieves', skill_summary='Places a [Counterattack] buff on a target ally for 2 turns. Places a [Counterattack] buff for 3 turns instead if the ally is from the Shadowkin Faction. Then fills the Turn Meters of all allies by 15% and place a 30% [Increase C.DMG] buff on all allies for 2 turns. Also places a 30% [Increase C.RATE] buff for 2 turns on all allies from the Shadowkin Faction', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Poised for Glory" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='7531ef09-1cfe-4774-86c6-af00df366ef8' and slot='A3';
update champion_skills set skill_name='Brethren', skill_summary='Increases all heals and Turn Meter fill effects by 20% when used on allies from the Shadowkin Faction. If there are multiple champions on the team with this skill, only one will activate.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Sensei''s Focus" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='7531ef09-1cfe-4774-86c6-af00df366ef8' and slot='A4';

-- Yaga  (jac 0.50, 3 skills)  id=20897abc-bbd2-4f4f-8880-58a2dd6fe1e9
update champion_skills set skill_name='Virulent Cleaver', skill_summary='Attacks 1 enemy. Has a 40% chance of placing a 5% [Poison] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Gaping Maw" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='20897abc-bbd2-4f4f-8880-58a2dd6fe1e9' and slot='A1';
update champion_skills set skill_name='Hungering Plague', skill_summary='Attacks 1 enemy 2 times. Each hit has a 50% chance of placing a 5% [Poison] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Ravenous" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='20897abc-bbd2-4f4f-8880-58a2dd6fe1e9' and slot='A2';
update champion_skills set skill_name='Rot From Within', skill_summary='Attacks 1 enemy. Damage increases by 25% against targets under [Poison] debuffs.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Insatiable" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='20897abc-bbd2-4f4f-8880-58a2dd6fe1e9' and slot='A3';

-- Yelagirna  (jac 0.83, 4 skills)  id=32f15445-208a-409e-b7c4-515f5aa6c715
update champion_skills set skill_name='Breath Taker', skill_summary='Attacks 1 enemy 2 times. Places a 50% [Increase ATK] buff on this Champion for 2 turns if this attack kills an enemy.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Foehammer" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='32f15445-208a-409e-b7c4-515f5aa6c715' and slot='A1';
update champion_skills set skill_name='Mortify', skill_summary='Attacks all enemies. Has a 75% chance of placing a 50% [Decrease ATK] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "War Cry" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='32f15445-208a-409e-b7c4-515f5aa6c715' and slot='A2';
update champion_skills set skill_name='Sword of Loss', skill_summary='Attacks 1 enemy. Has a 75% chance of placing a [Block Buffs] debuff and a [Block Active Skills] debuff for 2 turns. This attack is always critical.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Skull Sunder" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='32f15445-208a-409e-b7c4-515f5aa6c715' and slot='A3';
update champion_skills set skill_name='Great Cycle', skill_summary='Revives 1 random ally with 50% HP every time this Champion kills an enemy.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Life for a Life" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary refreshed from AyumiLove; mechanics matched in the audit.' where champion_id='32f15445-208a-409e-b7c4-515f5aa6c715' and slot='A4';

commit;

-- FLAGGED for manual review (did not map cleanly — count/slot mismatch): Chani(3db/4ay), Demytha(4db/3ay), Karato(4db/4ay), Lady Eresh(3db/4ay), Lonatharil(3db/4ay), Rakka(3db/4ay), Scion(3db/4ay)
