-- Wire SKELETON goal_solutions → tags + approve them, so computeTagCoverage can satisfy the goal.
-- Generated by tools/wire-goal-solutions.mjs from mechanically-clear label→tag mappings; REVIEW
-- before applying. Idempotent. 150 solution(s) across 69 goal(s). 2026-07-12.

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'da3b0417-0291-44c3-a591-d5f8a25a36a4', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'da3b0417-0291-44c3-a591-d5f8a25a36a4');
update goal_solutions set status = 'approved' where id = 'da3b0417-0291-44c3-a591-d5f8a25a36a4';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '433054d5-05b6-419f-92ec-60f633d23eee', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '433054d5-05b6-419f-92ec-60f633d23eee');
update goal_solutions set status = 'approved' where id = '433054d5-05b6-419f-92ec-60f633d23eee';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '5c577884-ad9b-4042-aea4-6e42f378be09', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '5c577884-ad9b-4042-aea4-6e42f378be09');
update goal_solutions set status = 'approved' where id = '5c577884-ad9b-4042-aea4-6e42f378be09';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "Block Cooldowns"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'bf8da100-568b-4835-8846-c781f579f227', id from tags where name in ('Block Cooldowns')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'bf8da100-568b-4835-8846-c781f579f227');
update goal_solutions set status = 'approved' where id = 'bf8da100-568b-4835-8846-c781f579f227';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '12230f75-a2b1-496f-bb39-daeec43e508b', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '12230f75-a2b1-496f-bb39-daeec43e508b');
update goal_solutions set status = 'approved' where id = '12230f75-a2b1-496f-bb39-daeec43e508b';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'aadf7a4d-05f3-49b5-bbba-574678fc4a91', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'aadf7a4d-05f3-49b5-bbba-574678fc4a91');
update goal_solutions set status = 'approved' where id = 'aadf7a4d-05f3-49b5-bbba-574678fc4a91';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '059d0575-d3a2-4ff5-b25e-f36486cc339f', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '059d0575-d3a2-4ff5-b25e-f36486cc339f');
update goal_solutions set status = 'approved' where id = '059d0575-d3a2-4ff5-b25e-f36486cc339f';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "Block Cooldowns"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'e7537197-a108-4fbe-a1de-c36e6015a4ad', id from tags where name in ('Block Cooldowns')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'e7537197-a108-4fbe-a1de-c36e6015a4ad');
update goal_solutions set status = 'approved' where id = 'e7537197-a108-4fbe-a1de-c36e6015a4ad';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '478d9ab1-ecaa-42dc-89d9-40a04b25e294', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '478d9ab1-ecaa-42dc-89d9-40a04b25e294');
update goal_solutions set status = 'approved' where id = '478d9ab1-ecaa-42dc-89d9-40a04b25e294';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'be94169f-ed20-4436-94b5-6b6963bc6a98', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'be94169f-ed20-4436-94b5-6b6963bc6a98');
update goal_solutions set status = 'approved' where id = 'be94169f-ed20-4436-94b5-6b6963bc6a98';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '409e21a9-ba5e-4e47-8c18-f20fc1c0759d', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '409e21a9-ba5e-4e47-8c18-f20fc1c0759d');
update goal_solutions set status = 'approved' where id = '409e21a9-ba5e-4e47-8c18-f20fc1c0759d';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "Block Cooldowns"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '275db523-737f-4033-97b8-ed782dc44c0c', id from tags where name in ('Block Cooldowns')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '275db523-737f-4033-97b8-ed782dc44c0c');
update goal_solutions set status = 'approved' where id = '275db523-737f-4033-97b8-ed782dc44c0c';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ac7fdef5-7d04-4823-ade9-da3be6c63850', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ac7fdef5-7d04-4823-ade9-da3be6c63850');
update goal_solutions set status = 'approved' where id = 'ac7fdef5-7d04-4823-ade9-da3be6c63850';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '20af0c57-ebff-463b-97c2-ad32339d635b', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '20af0c57-ebff-463b-97c2-ad32339d635b');
update goal_solutions set status = 'approved' where id = '20af0c57-ebff-463b-97c2-ad32339d635b';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'b700b86d-0ecf-4d7c-a847-f8d8ca3d2f6d', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'b700b86d-0ecf-4d7c-a847-f8d8ca3d2f6d');
update goal_solutions set status = 'approved' where id = 'b700b86d-0ecf-4d7c-a847-f8d8ca3d2f6d';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "Block Cooldowns"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '791ccfe7-96e1-470e-9c20-e753b7817d7d', id from tags where name in ('Block Cooldowns')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '791ccfe7-96e1-470e-9c20-e753b7817d7d');
update goal_solutions set status = 'approved' where id = '791ccfe7-96e1-470e-9c20-e753b7817d7d';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '27b0fa45-027d-486a-8af9-3a84ad5acba6', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '27b0fa45-027d-486a-8af9-3a84ad5acba6');
update goal_solutions set status = 'approved' where id = '27b0fa45-027d-486a-8af9-3a84ad5acba6';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '87aa2b86-18f1-4b5b-8418-2854f91c9066', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '87aa2b86-18f1-4b5b-8418-2854f91c9066');
update goal_solutions set status = 'approved' where id = '87aa2b86-18f1-4b5b-8418-2854f91c9066';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '658b5bf3-53bc-4868-a3c9-5858d95013b5', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '658b5bf3-53bc-4868-a3c9-5858d95013b5');
update goal_solutions set status = 'approved' where id = '658b5bf3-53bc-4868-a3c9-5858d95013b5';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "Block Cooldowns"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ec176de1-6858-4cfc-9404-d6f5a386069d', id from tags where name in ('Block Cooldowns')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ec176de1-6858-4cfc-9404-d6f5a386069d');
update goal_solutions set status = 'approved' where id = 'ec176de1-6858-4cfc-9404-d6f5a386069d';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'f6360c65-b583-42f6-8ab0-a432baf4e09d', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'f6360c65-b583-42f6-8ab0-a432baf4e09d');
update goal_solutions set status = 'approved' where id = 'f6360c65-b583-42f6-8ab0-a432baf4e09d';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'dd6a53dc-3604-400b-a0ff-b9d0659f63ed', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'dd6a53dc-3604-400b-a0ff-b9d0659f63ed');
update goal_solutions set status = 'approved' where id = 'dd6a53dc-3604-400b-a0ff-b9d0659f63ed';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ad67807d-9e09-487b-a6f3-cbd4ae71a891', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ad67807d-9e09-487b-a6f3-cbd4ae71a891');
update goal_solutions set status = 'approved' where id = 'ad67807d-9e09-487b-a6f3-cbd4ae71a891';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "Block Cooldowns"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '842a2b61-00d5-49bc-b29e-d6069940f749', id from tags where name in ('Block Cooldowns')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '842a2b61-00d5-49bc-b29e-d6069940f749');
update goal_solutions set status = 'approved' where id = '842a2b61-00d5-49bc-b29e-d6069940f749';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions (5 × 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '6b1183ca-a624-409c-a2bb-97866cfe373c', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '6b1183ca-a624-409c-a2bb-97866cfe373c');
update goal_solutions set status = 'approved' where id = '6b1183ca-a624-409c-a2bb-97866cfe373c';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Ally Attack"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '2b6c1a75-fb2d-49a9-a476-8474df3de099', id from tags where name in ('Multi-Hit A1', 'Ally Attack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '2b6c1a75-fb2d-49a9-a476-8474df3de099');
update goal_solutions set status = 'approved' where id = '2b6c1a75-fb2d-49a9-a476-8474df3de099';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'a78c1274-3cf2-4368-bf0b-f66f7be0967a', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'a78c1274-3cf2-4368-bf0b-f66f7be0967a');
update goal_solutions set status = 'approved' where id = 'a78c1274-3cf2-4368-bf0b-f66f7be0967a';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '0bfdbb19-94e5-492c-9c17-9301e490549d', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '0bfdbb19-94e5-492c-9c17-9301e490549d');
update goal_solutions set status = 'approved' where id = '0bfdbb19-94e5-492c-9c17-9301e490549d';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '0b629499-3b49-40ec-9f5e-8a7d528080fc', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '0b629499-3b49-40ec-9f5e-8a7d528080fc');
update goal_solutions set status = 'approved' where id = '0b629499-3b49-40ec-9f5e-8a7d528080fc';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Increase SPD buff (team-wide)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'fa5350f6-7256-4883-8331-cb578d336a06', id from tags where name in ('Increase Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'fa5350f6-7256-4883-8331-cb578d336a06');
update goal_solutions set status = 'approved' where id = 'fa5350f6-7256-4883-8331-cb578d336a06';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Cleanse (removes SPD debuff)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'b922cffd-bc3a-4b27-9c73-89baec353f42', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'b922cffd-bc3a-4b27-9c73-89baec353f42');
update goal_solutions set status = 'approved' where id = 'b922cffd-bc3a-4b27-9c73-89baec353f42';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions (5 × 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'd5ef1ac2-96d6-4f8c-bbfe-dcc952788b61', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'd5ef1ac2-96d6-4f8c-bbfe-dcc952788b61');
update goal_solutions set status = 'approved' where id = 'd5ef1ac2-96d6-4f8c-bbfe-dcc952788b61';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Ally Attack"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '95bcd297-6dee-4291-a58f-032b5ea6539c', id from tags where name in ('Multi-Hit A1', 'Ally Attack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '95bcd297-6dee-4291-a58f-032b5ea6539c');
update goal_solutions set status = 'approved' where id = '95bcd297-6dee-4291-a58f-032b5ea6539c';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '39031c06-a6a4-4b6a-8929-e92385baf01d', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '39031c06-a6a4-4b6a-8929-e92385baf01d');
update goal_solutions set status = 'approved' where id = '39031c06-a6a4-4b6a-8929-e92385baf01d';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ae8c76b3-2264-44fc-9199-9f35edcb881b', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ae8c76b3-2264-44fc-9199-9f35edcb881b');
update goal_solutions set status = 'approved' where id = 'ae8c76b3-2264-44fc-9199-9f35edcb881b';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '996cf6b5-6444-48c4-b855-9f4ab63acd5f', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '996cf6b5-6444-48c4-b855-9f4ab63acd5f');
update goal_solutions set status = 'approved' where id = '996cf6b5-6444-48c4-b855-9f4ab63acd5f';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Increase SPD buff (team-wide)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '61158165-baff-4c45-9c03-6f87f91e0983', id from tags where name in ('Increase Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '61158165-baff-4c45-9c03-6f87f91e0983');
update goal_solutions set status = 'approved' where id = '61158165-baff-4c45-9c03-6f87f91e0983';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Cleanse (removes SPD debuff)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '7f3849de-0720-4b31-8846-ada92a7812f2', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '7f3849de-0720-4b31-8846-ada92a7812f2');
update goal_solutions set status = 'approved' where id = '7f3849de-0720-4b31-8846-ada92a7812f2';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions (5 × 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'd46c9f8c-9e31-4b99-aeed-ff9ac156c1ab', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'd46c9f8c-9e31-4b99-aeed-ff9ac156c1ab');
update goal_solutions set status = 'approved' where id = 'd46c9f8c-9e31-4b99-aeed-ff9ac156c1ab';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Ally Attack"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '66b791ae-50b4-471c-b1d9-bcc09fb2f8e0', id from tags where name in ('Multi-Hit A1', 'Ally Attack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '66b791ae-50b4-471c-b1d9-bcc09fb2f8e0');
update goal_solutions set status = 'approved' where id = '66b791ae-50b4-471c-b1d9-bcc09fb2f8e0';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '7ed13181-1326-4c22-9240-b2910f339315', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '7ed13181-1326-4c22-9240-b2910f339315');
update goal_solutions set status = 'approved' where id = '7ed13181-1326-4c22-9240-b2910f339315';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '83c6da45-ffe2-47ec-844c-84464278eff9', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '83c6da45-ffe2-47ec-844c-84464278eff9');
update goal_solutions set status = 'approved' where id = '83c6da45-ffe2-47ec-844c-84464278eff9';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'd4ee28f2-83bd-4af0-ab3f-cfd1175e68c8', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'd4ee28f2-83bd-4af0-ab3f-cfd1175e68c8');
update goal_solutions set status = 'approved' where id = 'd4ee28f2-83bd-4af0-ab3f-cfd1175e68c8';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Increase SPD buff (team-wide)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'bf745798-7590-46e8-bf27-6194659453c2', id from tags where name in ('Increase Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'bf745798-7590-46e8-bf27-6194659453c2');
update goal_solutions set status = 'approved' where id = 'bf745798-7590-46e8-bf27-6194659453c2';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Cleanse (removes SPD debuff)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '372e4969-2717-430e-a11f-f4a1424f4762', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '372e4969-2717-430e-a11f-f4a1424f4762');
update goal_solutions set status = 'approved' where id = '372e4969-2717-430e-a11f-f4a1424f4762';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions (5 × 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'f652ab30-23f2-41fa-9b62-45ef4906ffa7', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'f652ab30-23f2-41fa-9b62-45ef4906ffa7');
update goal_solutions set status = 'approved' where id = 'f652ab30-23f2-41fa-9b62-45ef4906ffa7';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Ally Attack"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '95987f3a-497e-4037-b513-246ef1e2900f', id from tags where name in ('Multi-Hit A1', 'Ally Attack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '95987f3a-497e-4037-b513-246ef1e2900f');
update goal_solutions set status = 'approved' where id = '95987f3a-497e-4037-b513-246ef1e2900f';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'a04e4007-b2ac-4f0d-8b73-66e0d9677782', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'a04e4007-b2ac-4f0d-8b73-66e0d9677782');
update goal_solutions set status = 'approved' where id = 'a04e4007-b2ac-4f0d-8b73-66e0d9677782';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '7042a6d9-1d07-44ab-84de-05e406f6fe5c', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '7042a6d9-1d07-44ab-84de-05e406f6fe5c');
update goal_solutions set status = 'approved' where id = '7042a6d9-1d07-44ab-84de-05e406f6fe5c';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'd1fc8e70-4fc2-47a4-9924-e6d171d3eb92', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'd1fc8e70-4fc2-47a4-9924-e6d171d3eb92');
update goal_solutions set status = 'approved' where id = 'd1fc8e70-4fc2-47a4-9924-e6d171d3eb92';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Increase SPD buff (team-wide)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'f479fa0f-7f6c-46fb-b9a1-da39160ce99e', id from tags where name in ('Increase Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'f479fa0f-7f6c-46fb-b9a1-da39160ce99e');
update goal_solutions set status = 'approved' where id = 'f479fa0f-7f6c-46fb-b9a1-da39160ce99e';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Cleanse (removes SPD debuff)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '97dc6650-732c-4f03-a878-2ba799812edd', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '97dc6650-732c-4f03-a878-2ba799812edd');
update goal_solutions set status = 'approved' where id = '97dc6650-732c-4f03-a878-2ba799812edd';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions (5 × 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '90bbbef1-da7c-4f80-b4a2-e2dd8963a263', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '90bbbef1-da7c-4f80-b4a2-e2dd8963a263');
update goal_solutions set status = 'approved' where id = '90bbbef1-da7c-4f80-b4a2-e2dd8963a263';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Ally Attack"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'e357ce3d-6f66-41c6-b960-07499b631c23', id from tags where name in ('Multi-Hit A1', 'Ally Attack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'e357ce3d-6f66-41c6-b960-07499b631c23');
update goal_solutions set status = 'approved' where id = 'e357ce3d-6f66-41c6-b960-07499b631c23';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '32c85d1a-e9f2-4ef3-a7fd-f71bd2592e7a', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '32c85d1a-e9f2-4ef3-a7fd-f71bd2592e7a');
update goal_solutions set status = 'approved' where id = '32c85d1a-e9f2-4ef3-a7fd-f71bd2592e7a';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '80c63249-1dbb-4a4f-b915-f42d332bc119', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '80c63249-1dbb-4a4f-b915-f42d332bc119');
update goal_solutions set status = 'approved' where id = '80c63249-1dbb-4a4f-b915-f42d332bc119';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '20f18e21-a3aa-4728-a16b-6a6bfa2cf6b1', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '20f18e21-a3aa-4728-a16b-6a6bfa2cf6b1');
update goal_solutions set status = 'approved' where id = '20f18e21-a3aa-4728-a16b-6a6bfa2cf6b1';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Increase SPD buff (team-wide)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '8d7701a7-ebd8-4e5a-8feb-4a9ab11ded54', id from tags where name in ('Increase Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '8d7701a7-ebd8-4e5a-8feb-4a9ab11ded54');
update goal_solutions set status = 'approved' where id = '8d7701a7-ebd8-4e5a-8feb-4a9ab11ded54';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Cleanse (removes SPD debuff)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '28d27bd5-686a-4ffc-9e4b-e3ed2c36a499', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '28d27bd5-686a-4ffc-9e4b-e3ed2c36a499');
update goal_solutions set status = 'approved' where id = '28d27bd5-686a-4ffc-9e4b-e3ed2c36a499';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions (5 × 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'dfd481a5-4f59-40e8-8355-004f2181359a', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'dfd481a5-4f59-40e8-8355-004f2181359a');
update goal_solutions set status = 'approved' where id = 'dfd481a5-4f59-40e8-8355-004f2181359a';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Ally Attack"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'fb4b75a2-53c7-429e-91ea-87c29853848d', id from tags where name in ('Multi-Hit A1', 'Ally Attack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'fb4b75a2-53c7-429e-91ea-87c29853848d');
update goal_solutions set status = 'approved' where id = 'fb4b75a2-53c7-429e-91ea-87c29853848d';

-- Break the shield every round before Fyro takes his turn — failure caus | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '10560ba2-873e-49e9-8e50-68c6b98d4abf', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '10560ba2-873e-49e9-8e50-68c6b98d4abf');
update goal_solutions set status = 'approved' where id = '10560ba2-873e-49e9-8e50-68c6b98d4abf';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '049cc412-f9d8-4821-b391-1f12a4233000', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '049cc412-f9d8-4821-b391-1f12a4233000');
update goal_solutions set status = 'approved' where id = '049cc412-f9d8-4821-b391-1f12a4233000';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '0751b549-8810-437c-8343-c38325ad37c4', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '0751b549-8810-437c-8343-c38325ad37c4');
update goal_solutions set status = 'approved' where id = '0751b549-8810-437c-8343-c38325ad37c4';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Increase SPD buff (team-wide)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '4d4bcb6c-8211-4b0e-8f69-892839008d3a', id from tags where name in ('Increase Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '4d4bcb6c-8211-4b0e-8f69-892839008d3a');
update goal_solutions set status = 'approved' where id = '4d4bcb6c-8211-4b0e-8f69-892839008d3a';

-- Counter Dazzling Flames SPD debuff — without an SPD buffer your team l | "Cleanse (removes SPD debuff)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'b0c5c68c-65e0-4819-9435-92c3f5eafce1', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'b0c5c68c-65e0-4819-9435-92c3f5eafce1');
update goal_solutions set status = 'approved' where id = 'b0c5c68c-65e0-4819-9435-92c3f5eafce1';

-- Kill both minions before the boss phase — alive minions during Frigid  | "AoE Damage + Decrease DEF"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '09927234-bf67-40de-8711-8b909678e07a', id from tags where name in ('AoE Damage', 'Decrease Defense')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '09927234-bf67-40de-8711-8b909678e07a');
update goal_solutions set status = 'approved' where id = '09927234-bf67-40de-8711-8b909678e07a';

-- Kill both minions before the boss phase — alive minions during Frigid  | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '5451458c-8ca3-47a7-8db4-369b34489d0d', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '5451458c-8ca3-47a7-8db4-369b34489d0d');
update goal_solutions set status = 'approved' where id = '5451458c-8ca3-47a7-8db4-369b34489d0d';

-- Kill both minions before the boss phase — alive minions during Frigid  | "AoE Damage + Decrease DEF"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'a0ea1008-48d4-442b-a5f0-f6467c94d855', id from tags where name in ('AoE Damage', 'Decrease Defense')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'a0ea1008-48d4-442b-a5f0-f6467c94d855');
update goal_solutions set status = 'approved' where id = 'a0ea1008-48d4-442b-a5f0-f6467c94d855';

-- Kill both minions before the boss phase — alive minions during Frigid  | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '51ee7760-110a-463b-9921-1d2fea9a5771', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '51ee7760-110a-463b-9921-1d2fea9a5771');
update goal_solutions set status = 'approved' where id = '51ee7760-110a-463b-9921-1d2fea9a5771';

-- Kill both minions before the boss phase — alive minions during Frigid  | "AoE Damage + Decrease DEF"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '4d177672-9a9b-44e1-9865-35d98f4e5311', id from tags where name in ('AoE Damage', 'Decrease Defense')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '4d177672-9a9b-44e1-9865-35d98f4e5311');
update goal_solutions set status = 'approved' where id = '4d177672-9a9b-44e1-9865-35d98f4e5311';

-- Kill both minions before the boss phase — alive minions during Frigid  | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'b5dfee51-93a6-4e3c-bccd-ff5728d8f59a', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'b5dfee51-93a6-4e3c-bccd-ff5728d8f59a');
update goal_solutions set status = 'approved' where id = 'b5dfee51-93a6-4e3c-bccd-ff5728d8f59a';

-- Kill both minions before the boss phase — alive minions during Frigid  | "AoE Damage + Decrease DEF"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '85f6aecd-f505-43bb-adf1-741e467abfe8', id from tags where name in ('AoE Damage', 'Decrease Defense')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '85f6aecd-f505-43bb-adf1-741e467abfe8');
update goal_solutions set status = 'approved' where id = '85f6aecd-f505-43bb-adf1-741e467abfe8';

-- Kill both minions before the boss phase — alive minions during Frigid  | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '92025dba-b773-44a1-ae67-c5b430b43f27', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '92025dba-b773-44a1-ae67-c5b430b43f27');
update goal_solutions set status = 'approved' where id = '92025dba-b773-44a1-ae67-c5b430b43f27';

-- Kill both minions before the boss phase — alive minions during Frigid  | "AoE Damage + Decrease DEF"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '1f185566-d042-4289-8b91-44e822ca54d7', id from tags where name in ('AoE Damage', 'Decrease Defense')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '1f185566-d042-4289-8b91-44e822ca54d7');
update goal_solutions set status = 'approved' where id = '1f185566-d042-4289-8b91-44e822ca54d7';

-- Kill both minions before the boss phase — alive minions during Frigid  | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '28a943a6-e501-4c83-b987-62513f9e0e62', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '28a943a6-e501-4c83-b987-62513f9e0e62');
update goal_solutions set status = 'approved' where id = '28a943a6-e501-4c83-b987-62513f9e0e62';

-- Kill both minions before the boss phase — alive minions during Frigid  | "AoE Damage + Decrease DEF"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ae26fc23-97a3-40c7-85b9-3825c1b03930', id from tags where name in ('AoE Damage', 'Decrease Defense')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ae26fc23-97a3-40c7-85b9-3825c1b03930');
update goal_solutions set status = 'approved' where id = 'ae26fc23-97a3-40c7-85b9-3825c1b03930';

-- Kill both minions before the boss phase — alive minions during Frigid  | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '0511150d-6379-48c9-a506-1f5c74cc806d', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '0511150d-6379-48c9-a506-1f5c74cc806d');
update goal_solutions set status = 'approved' where id = '0511150d-6379-48c9-a506-1f5c74cc806d';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Poison stacking"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'b60de5b8-177c-4823-a3bb-d2d8ec3408fb', id from tags where name in ('Poison')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'b60de5b8-177c-4823-a3bb-d2d8ec3408fb');
update goal_solutions set status = 'approved' where id = 'b60de5b8-177c-4823-a3bb-d2d8ec3408fb';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "HP Burn"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'e13e2427-1780-4d86-b3b8-8512b295a127', id from tags where name in ('HP Burn')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'e13e2427-1780-4d86-b3b8-8512b295a127');
update goal_solutions set status = 'approved' where id = 'e13e2427-1780-4d86-b3b8-8512b295a127';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Block Revive + burst damage"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '3c7bedea-914f-4718-9ba5-0c0f57a11c1b', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '3c7bedea-914f-4718-9ba5-0c0f57a11c1b');
update goal_solutions set status = 'approved' where id = '3c7bedea-914f-4718-9ba5-0c0f57a11c1b';

-- Keep minions dead or Block Revive active — alive minions during Frigid | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '11d7e5fb-249f-497d-88ad-1d658b6e9489', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '11d7e5fb-249f-497d-88ad-1d658b6e9489');
update goal_solutions set status = 'approved' where id = '11d7e5fb-249f-497d-88ad-1d658b6e9489';

-- Resist or cleanse Numbing Chill — 50% Decrease ACC for 2 turns cuts de | "Cleanse"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '6cdcee02-2a63-4722-8d63-ba79d8582de6', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '6cdcee02-2a63-4722-8d63-ba79d8582de6');
update goal_solutions set status = 'approved' where id = '6cdcee02-2a63-4722-8d63-ba79d8582de6';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Poison stacking"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '6d57f649-d074-40cf-a163-c3b0f9767cdd', id from tags where name in ('Poison')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '6d57f649-d074-40cf-a163-c3b0f9767cdd');
update goal_solutions set status = 'approved' where id = '6d57f649-d074-40cf-a163-c3b0f9767cdd';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "HP Burn"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '6dfeac53-58ef-41e7-a74a-546388202e51', id from tags where name in ('HP Burn')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '6dfeac53-58ef-41e7-a74a-546388202e51');
update goal_solutions set status = 'approved' where id = '6dfeac53-58ef-41e7-a74a-546388202e51';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Block Revive + burst damage"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '0ee0343c-9052-4e8f-bac2-b38de1f16686', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '0ee0343c-9052-4e8f-bac2-b38de1f16686');
update goal_solutions set status = 'approved' where id = '0ee0343c-9052-4e8f-bac2-b38de1f16686';

-- Keep minions dead or Block Revive active — alive minions during Frigid | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '83bb19df-8466-4627-9baf-f2799a8efa56', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '83bb19df-8466-4627-9baf-f2799a8efa56');
update goal_solutions set status = 'approved' where id = '83bb19df-8466-4627-9baf-f2799a8efa56';

-- Resist or cleanse Numbing Chill — 50% Decrease ACC for 2 turns cuts de | "Cleanse"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '7675f648-0b1e-46ff-b946-cfb9ad1ac3ac', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '7675f648-0b1e-46ff-b946-cfb9ad1ac3ac');
update goal_solutions set status = 'approved' where id = '7675f648-0b1e-46ff-b946-cfb9ad1ac3ac';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Poison stacking"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'd3a6883a-c4fd-4e69-8231-eb067574807d', id from tags where name in ('Poison')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'd3a6883a-c4fd-4e69-8231-eb067574807d');
update goal_solutions set status = 'approved' where id = 'd3a6883a-c4fd-4e69-8231-eb067574807d';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "HP Burn"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'fc23e25e-0094-4974-aa73-2e161e84435c', id from tags where name in ('HP Burn')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'fc23e25e-0094-4974-aa73-2e161e84435c');
update goal_solutions set status = 'approved' where id = 'fc23e25e-0094-4974-aa73-2e161e84435c';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Block Revive + burst damage"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '7c869c80-a26f-46b2-b87e-6032367ccfa5', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '7c869c80-a26f-46b2-b87e-6032367ccfa5');
update goal_solutions set status = 'approved' where id = '7c869c80-a26f-46b2-b87e-6032367ccfa5';

-- Keep minions dead or Block Revive active — alive minions during Frigid | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '4d263db8-0d49-46e5-b8af-e0e6aa6ae5fa', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '4d263db8-0d49-46e5-b8af-e0e6aa6ae5fa');
update goal_solutions set status = 'approved' where id = '4d263db8-0d49-46e5-b8af-e0e6aa6ae5fa';

-- Resist or cleanse Numbing Chill — 50% Decrease ACC for 2 turns cuts de | "Cleanse"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'c5152c7d-db44-43bf-985d-4bf32aaeef65', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'c5152c7d-db44-43bf-985d-4bf32aaeef65');
update goal_solutions set status = 'approved' where id = 'c5152c7d-db44-43bf-985d-4bf32aaeef65';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Poison stacking"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '1a613b50-009b-484b-ae0a-9b841f2e3ab1', id from tags where name in ('Poison')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '1a613b50-009b-484b-ae0a-9b841f2e3ab1');
update goal_solutions set status = 'approved' where id = '1a613b50-009b-484b-ae0a-9b841f2e3ab1';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "HP Burn"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ca2d505d-9386-4c20-9c27-a02935c30e5c', id from tags where name in ('HP Burn')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ca2d505d-9386-4c20-9c27-a02935c30e5c');
update goal_solutions set status = 'approved' where id = 'ca2d505d-9386-4c20-9c27-a02935c30e5c';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Block Revive + burst damage"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '76a780ae-4bb7-42fb-b0a4-b3fe58f12236', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '76a780ae-4bb7-42fb-b0a4-b3fe58f12236');
update goal_solutions set status = 'approved' where id = '76a780ae-4bb7-42fb-b0a4-b3fe58f12236';

-- Keep minions dead or Block Revive active — alive minions during Frigid | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'cd5076e6-eef8-4771-bc0e-c26d2950f820', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'cd5076e6-eef8-4771-bc0e-c26d2950f820');
update goal_solutions set status = 'approved' where id = 'cd5076e6-eef8-4771-bc0e-c26d2950f820';

-- Resist or cleanse Numbing Chill — 50% Decrease ACC for 2 turns cuts de | "Cleanse"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '5dfa3a48-bf2c-4866-9c1d-7da9119e2982', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '5dfa3a48-bf2c-4866-9c1d-7da9119e2982');
update goal_solutions set status = 'approved' where id = '5dfa3a48-bf2c-4866-9c1d-7da9119e2982';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Poison stacking"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '7c33db62-b056-46ff-abdf-0205f546b787', id from tags where name in ('Poison')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '7c33db62-b056-46ff-abdf-0205f546b787');
update goal_solutions set status = 'approved' where id = '7c33db62-b056-46ff-abdf-0205f546b787';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "HP Burn"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'd5f749c0-1db7-4d43-ac57-38d24ee50458', id from tags where name in ('HP Burn')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'd5f749c0-1db7-4d43-ac57-38d24ee50458');
update goal_solutions set status = 'approved' where id = 'd5f749c0-1db7-4d43-ac57-38d24ee50458';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Block Revive + burst damage"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '96ea8d0b-eaf4-49c2-99ac-95a5fa0b9466', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '96ea8d0b-eaf4-49c2-99ac-95a5fa0b9466');
update goal_solutions set status = 'approved' where id = '96ea8d0b-eaf4-49c2-99ac-95a5fa0b9466';

-- Keep minions dead or Block Revive active — alive minions during Frigid | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '2d670c3c-ac9a-41d2-8430-1493dc97de29', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '2d670c3c-ac9a-41d2-8430-1493dc97de29');
update goal_solutions set status = 'approved' where id = '2d670c3c-ac9a-41d2-8430-1493dc97de29';

-- Resist or cleanse Numbing Chill — 50% Decrease ACC for 2 turns cuts de | "Cleanse"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '425f4a67-2003-4a68-a426-16ca3dada350', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '425f4a67-2003-4a68-a426-16ca3dada350');
update goal_solutions set status = 'approved' where id = '425f4a67-2003-4a68-a426-16ca3dada350';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Poison stacking"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ec290ff4-01e1-492c-91fe-0414d596bb7c', id from tags where name in ('Poison')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ec290ff4-01e1-492c-91fe-0414d596bb7c');
update goal_solutions set status = 'approved' where id = 'ec290ff4-01e1-492c-91fe-0414d596bb7c';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "HP Burn"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'f05a689f-eeb9-4a49-881a-9fea426727f8', id from tags where name in ('HP Burn')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'f05a689f-eeb9-4a49-881a-9fea426727f8');
update goal_solutions set status = 'approved' where id = 'f05a689f-eeb9-4a49-881a-9fea426727f8';

-- Avoid triggering Frigid Vengeance with burst damage — use Poison or HP | "Block Revive + burst damage"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'e2e74448-3283-482f-ae02-cdbf20637893', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'e2e74448-3283-482f-ae02-cdbf20637893');
update goal_solutions set status = 'approved' where id = 'e2e74448-3283-482f-ae02-cdbf20637893';

-- Keep minions dead or Block Revive active — alive minions during Frigid | "Block Revive"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'd7cce4e5-2444-4394-921c-512f4ebb206c', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'd7cce4e5-2444-4394-921c-512f4ebb206c');
update goal_solutions set status = 'approved' where id = 'd7cce4e5-2444-4394-921c-512f4ebb206c';

-- Resist or cleanse Numbing Chill — 50% Decrease ACC for 2 turns cuts de | "Cleanse"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '6e9a5a34-a2ee-4ddb-a2bd-8963e1fa517c', id from tags where name in ('Cleanse')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '6e9a5a34-a2ee-4ddb-a2bd-8963e1fa517c');
update goal_solutions set status = 'approved' where id = '6e9a5a34-a2ee-4ddb-a2bd-8963e1fa517c';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '5a1a6842-fe00-4627-961e-0bfb907b7cd2', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '5a1a6842-fe00-4627-961e-0bfb907b7cd2');
update goal_solutions set status = 'approved' where id = '5a1a6842-fe00-4627-961e-0bfb907b7cd2';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '3eed6e5d-ecf0-418d-a456-ace1a1b15078', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '3eed6e5d-ecf0-418d-a456-ace1a1b15078');
update goal_solutions set status = 'approved' where id = '3eed6e5d-ecf0-418d-a456-ace1a1b15078';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'a271d3d6-cfdb-4e15-a35a-dca819b5b038', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'a271d3d6-cfdb-4e15-a35a-dca819b5b038');
update goal_solutions set status = 'approved' where id = 'a271d3d6-cfdb-4e15-a35a-dca819b5b038';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '459431e7-2226-4810-b0b4-b15ec83872c1', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '459431e7-2226-4810-b0b4-b15ec83872c1');
update goal_solutions set status = 'approved' where id = '459431e7-2226-4810-b0b4-b15ec83872c1';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '454e8f09-cae5-4eb6-93d5-37af66e72bb0', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '454e8f09-cae5-4eb6-93d5-37af66e72bb0');
update goal_solutions set status = 'approved' where id = '454e8f09-cae5-4eb6-93d5-37af66e72bb0';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '96c923fd-0de4-4b3b-b892-08d753940c2f', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '96c923fd-0de4-4b3b-b892-08d753940c2f');
update goal_solutions set status = 'approved' where id = '96c923fd-0de4-4b3b-b892-08d753940c2f';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '107df04e-5d40-41ea-9786-ded5516af833', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '107df04e-5d40-41ea-9786-ded5516af833');
update goal_solutions set status = 'approved' where id = '107df04e-5d40-41ea-9786-ded5516af833';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '1664dfd1-3db8-4019-9de1-5036a04bbd8d', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '1664dfd1-3db8-4019-9de1-5036a04bbd8d');
update goal_solutions set status = 'approved' where id = '1664dfd1-3db8-4019-9de1-5036a04bbd8d';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '630dbe80-c09f-4b65-8a27-5fc7b37b3658', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '630dbe80-c09f-4b65-8a27-5fc7b37b3658');
update goal_solutions set status = 'approved' where id = '630dbe80-c09f-4b65-8a27-5fc7b37b3658';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '36e398b9-fed2-4bdf-a479-836809bf2685', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '36e398b9-fed2-4bdf-a479-836809bf2685');
update goal_solutions set status = 'approved' where id = '36e398b9-fed2-4bdf-a479-836809bf2685';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '080b1c97-8b0e-417e-9086-431c6372ec74', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '080b1c97-8b0e-417e-9086-431c6372ec74');
update goal_solutions set status = 'approved' where id = '080b1c97-8b0e-417e-9086-431c6372ec74';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '7f8199fe-e77f-4ada-b5c9-f4fab40fb4b1', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '7f8199fe-e77f-4ada-b5c9-f4fab40fb4b1');
update goal_solutions set status = 'approved' where id = '7f8199fe-e77f-4ada-b5c9-f4fab40fb4b1';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '3998c473-b1bd-4559-9557-d26fde2d527f', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '3998c473-b1bd-4559-9557-d26fde2d527f');
update goal_solutions set status = 'approved' where id = '3998c473-b1bd-4559-9557-d26fde2d527f';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '3527b9cc-5897-49f2-b5b7-101f9375d09f', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '3527b9cc-5897-49f2-b5b7-101f9375d09f');
update goal_solutions set status = 'approved' where id = '3527b9cc-5897-49f2-b5b7-101f9375d09f';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '83943908-84eb-40f5-a888-a2bdf6aae227', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '83943908-84eb-40f5-a888-a2bdf6aae227');
update goal_solutions set status = 'approved' where id = '83943908-84eb-40f5-a888-a2bdf6aae227';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions (5 x 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '73eb62b0-d534-4e08-a310-491d90b803fd', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '73eb62b0-d534-4e08-a310-491d90b803fd');
update goal_solutions set status = 'approved' where id = '73eb62b0-d534-4e08-a310-491d90b803fd';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '322a81aa-e3bc-4581-b2c2-c4621b19d13e', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '322a81aa-e3bc-4581-b2c2-c4621b19d13e');
update goal_solutions set status = 'approved' where id = '322a81aa-e3bc-4581-b2c2-c4621b19d13e';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'bd1faf05-b8e0-41d8-afa1-d7dee75e9ab6', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'bd1faf05-b8e0-41d8-afa1-d7dee75e9ab6');
update goal_solutions set status = 'approved' where id = 'bd1faf05-b8e0-41d8-afa1-d7dee75e9ab6';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '30bc13cb-474f-424a-a3ce-6f3b2835b5d8', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '30bc13cb-474f-424a-a3ce-6f3b2835b5d8');
update goal_solutions set status = 'approved' where id = '30bc13cb-474f-424a-a3ce-6f3b2835b5d8';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '4642b512-1bb3-43d9-a777-897808b380d0', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '4642b512-1bb3-43d9-a777-897808b380d0');
update goal_solutions set status = 'approved' where id = '4642b512-1bb3-43d9-a777-897808b380d0';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions (5 x 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'a43376a3-8450-4a2d-b476-ef16b567543c', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'a43376a3-8450-4a2d-b476-ef16b567543c');
update goal_solutions set status = 'approved' where id = 'a43376a3-8450-4a2d-b476-ef16b567543c';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '53507e00-2fb6-4f90-8fa1-41847c34c980', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '53507e00-2fb6-4f90-8fa1-41847c34c980');
update goal_solutions set status = 'approved' where id = '53507e00-2fb6-4f90-8fa1-41847c34c980';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions (5 x 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '4349e45e-abb4-424c-aeeb-026a65267931', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '4349e45e-abb4-424c-aeeb-026a65267931');
update goal_solutions set status = 'approved' where id = '4349e45e-abb4-424c-aeeb-026a65267931';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '2ac4a6cc-a79a-4b2a-bb97-1be7129f8164', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '2ac4a6cc-a79a-4b2a-bb97-1be7129f8164');
update goal_solutions set status = 'approved' where id = '2ac4a6cc-a79a-4b2a-bb97-1be7129f8164';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'b3243660-c604-417a-bc08-9e80de3e2a0a', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'b3243660-c604-417a-bc08-9e80de3e2a0a');
update goal_solutions set status = 'approved' where id = 'b3243660-c604-417a-bc08-9e80de3e2a0a';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Stun"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'cba668a3-cbf0-41a0-b4f3-16897d02b005', id from tags where name in ('AoE Stun')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'cba668a3-cbf0-41a0-b4f3-16897d02b005');
update goal_solutions set status = 'approved' where id = 'cba668a3-cbf0-41a0-b4f3-16897d02b005';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Freeze"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'a9000a4a-ab06-463b-9059-9d0b4f1559bc', id from tags where name in ('AoE Freeze')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'a9000a4a-ab06-463b-9059-9d0b4f1559bc');
update goal_solutions set status = 'approved' where id = 'a9000a4a-ab06-463b-9059-9d0b4f1559bc';

-- Clear the wave before dangerous minion skills activate — use AoE CC to | "AoE Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'cc43fca3-1989-4f8e-8535-f5b8728403f2', id from tags where name in ('AoE Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'cc43fca3-1989-4f8e-8535-f5b8728403f2');
update goal_solutions set status = 'approved' where id = 'cc43fca3-1989-4f8e-8535-f5b8728403f2';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions (5 x 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '8829a679-696e-40a6-842f-5e622ee30a60', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '8829a679-696e-40a6-842f-5e622ee30a60');
update goal_solutions set status = 'approved' where id = '8829a679-696e-40a6-842f-5e622ee30a60';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'a2248f13-85d8-453c-8a55-e0ec7f20d488', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'a2248f13-85d8-453c-8a55-e0ec7f20d488');
update goal_solutions set status = 'approved' where id = 'a2248f13-85d8-453c-8a55-e0ec7f20d488';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '00406434-6f15-41a6-9f3b-b56354f1af98', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '00406434-6f15-41a6-9f3b-b56354f1af98');
update goal_solutions set status = 'approved' where id = '00406434-6f15-41a6-9f3b-b56354f1af98';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions (5 x 2+ hits = 10+)"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '5b421b9a-2eb0-47d7-897e-a9d9a616daf7', id from tags where name in ('Multi-Hit A1')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '5b421b9a-2eb0-47d7-897e-a9d9a616daf7');
update goal_solutions set status = 'approved' where id = '5b421b9a-2eb0-47d7-897e-a9d9a616daf7';

-- Break the shield every round before Fyro takes his turn — same 10-hit  | "Multi-Hit A1 champions + Counterattack buff"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'ebfa1aa0-2355-4a24-a17a-2899c6ef9b86', id from tags where name in ('Multi-Hit A1', 'Counterattack')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'ebfa1aa0-2355-4a24-a17a-2899c6ef9b86');
update goal_solutions set status = 'approved' where id = 'ebfa1aa0-2355-4a24-a17a-2899c6ef9b86';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'f13b1061-3db5-4ef2-8faf-5d2f8e3c3435', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'f13b1061-3db5-4ef2-8faf-5d2f8e3c3435');
update goal_solutions set status = 'approved' where id = 'f13b1061-3db5-4ef2-8faf-5d2f8e3c3435';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'f1c2841b-1232-4a74-a83e-6fac9bb1c783', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'f1c2841b-1232-4a74-a83e-6fac9bb1c783');
update goal_solutions set status = 'approved' where id = 'f1c2841b-1232-4a74-a83e-6fac9bb1c783';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '53980171-6259-4ad3-a589-d8c19014fa23', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '53980171-6259-4ad3-a589-d8c19014fa23');
update goal_solutions set status = 'approved' where id = '53980171-6259-4ad3-a589-d8c19014fa23';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '58cc0de1-a811-4f22-965a-4bd2ea272172', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '58cc0de1-a811-4f22-965a-4bd2ea272172');
update goal_solutions set status = 'approved' where id = '58cc0de1-a811-4f22-965a-4bd2ea272172';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter + Decrease SPD"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '4f65cc32-5672-4952-b574-ef0c7a1065d1', id from tags where name in ('Decrease Turn Meter', 'Decrease Speed')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '4f65cc32-5672-4952-b574-ef0c7a1065d1');
update goal_solutions set status = 'approved' where id = '4f65cc32-5672-4952-b574-ef0c7a1065d1';

-- Apply Decrease DEF and Weaken once shield is down to maximize damage i | "Decrease Turn Meter only"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '76e8f278-dd36-43ee-8b5d-1a7eeb774b74', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '76e8f278-dd36-43ee-8b5d-1a7eeb774b74');
update goal_solutions set status = 'approved' where id = '76e8f278-dd36-43ee-8b5d-1a7eeb774b74';

-- Control Fyro''s Turn Meter after the shield breaks — keep him in the vu | "Decrease Turn Meter"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '65430ef0-76d0-4086-8427-980af13c9096', id from tags where name in ('Decrease Turn Meter')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '65430ef0-76d0-4086-8427-980af13c9096');
update goal_solutions set status = 'approved' where id = '65430ef0-76d0-4086-8427-980af13c9096';

-- At stage 14: treat Frigid Vengeance with the same caution as stage 15- | "Poison stacking"
insert into goal_solution_tags (goal_solution_id, tag_id)
select 'f33dc8d5-ce7d-473b-a161-d9257e4ee494', id from tags where name in ('Poison')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = 'f33dc8d5-ce7d-473b-a161-d9257e4ee494');
update goal_solutions set status = 'approved' where id = 'f33dc8d5-ce7d-473b-a161-d9257e4ee494';

-- At stage 14: treat Frigid Vengeance with the same caution as stage 15- | "Block Revive + careful minion management"
insert into goal_solution_tags (goal_solution_id, tag_id)
select '397c04ee-63e2-4874-969c-d502a4ee57f5', id from tags where name in ('Block Revive')
  and id not in (select tag_id from goal_solution_tags where goal_solution_id = '397c04ee-63e2-4874-969c-d502a4ee57f5');
update goal_solutions set status = 'approved' where id = '397c04ee-63e2-4874-969c-d502a4ee57f5';
