-- ============================================================================
-- 2026-08-07 — FLAGGED NAME-ONLY corruption fix (7 champions) — DRAFT, NOT YET APPLIED
--
-- The 7 ALL_WRONG champions the batch seed (2026-08-07_namefix_batch_ayumilove.sql) could NOT
-- auto-fix: DB skill count != AyumiLove count. Root cause: the bad-bulk seed 104 OMITTED a skill
-- row for several champions (mostly the passive), so the name diff saw fewer DB rows than reality.
--
--   5 missing a row -> UPDATE the 3 actives + INSERT the missing 4th (Passive, or A4 for Rakka's
--                      active "Creep"). Chani/Lady Eresh/Lonatharil/Scion (passive), Rakka (A4).
--   Karato          -> 4 straight UPDATEs (had all 4 rows; only names were wrong).
--   Demytha         -> UPDATE 3 actives; her A4 has NO AyumiLove source (page lists 3 skills+aura,
--                      no passive) -> left UNCHANGED and flagged for Tier-1 (see FLAGGED below).
--
-- skill_id = worksheet C-ID prefix + slot (from existing rows). INSERTs idempotent on skill_id.
-- verification_status=proposed (HUMAN REVIEW). Source AyumiLove (Tier-2). Old names in review_notes.
-- Worksheet writeback owed on approve. Apply via tools/apply-seed-pooler.mjs AFTER review.
-- ============================================================================
begin;

-- Chani  (DB 3 / AY 4)  prefix=C000307  id=febd8fca-e94c-4a4d-8005-01c1b0a9c542
update champion_skills set skill_name='Insidious Arrow', skill_summary='Attacks 1 enemy. Has a 40% chance of placing a 25% [Poison Sensitivity] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Jaguar''s Bite" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='febd8fca-e94c-4a4d-8005-01c1b0a9c542' and slot='A1';
update champion_skills set skill_name='Soul Fire', skill_summary='Places a 50% [Increase ACC] buff and a 50% [Increase ATK] buff on this Champion for 2 turns, then attacks 1 enemy. Places a [HP Burn] debuff for 2 turns if this attack is critical.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Jungle Haze" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='febd8fca-e94c-4a4d-8005-01c1b0a9c542' and slot='A2';
update champion_skills set skill_name='Shower of Misery', skill_summary='Attacks all enemies. Has a 50% chance of increasing the duration of all debuffs by 1 turn', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Envenomed Arrows" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='febd8fca-e94c-4a4d-8005-01c1b0a9c542' and slot='A3';
insert into champion_skills (champion_id, skill_id, slot, form, skill_name, skill_summary, cooldown_base, cooldown_booked, damage_multiplier, multiplier_type, ascension_required, verification_status, source, review_notes)
  values ('febd8fca-e94c-4a4d-8005-01c1b0a9c542', 'C000307-Passive', 'Passive', null, 'Sureshot', 'Immune to [Decrease ACC] debuffs. Increases this Champion''s C.RATE by 0.05% for every point of ACC they have.', null, null, null, null, 3, 'proposed', 'AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', 'MISSING skill row added from AyumiLove (DB had no Passive; bad-bulk seed 104 omitted it). Needs Tier-1 confirmation.')
  on conflict (skill_id) do update set skill_name=excluded.skill_name, skill_summary=excluded.skill_summary, cooldown_base=excluded.cooldown_base, ascension_required=excluded.ascension_required, source=excluded.source, verification_status=excluded.verification_status, review_notes=excluded.review_notes;

-- Lady Eresh  (DB 3 / AY 4)  prefix=C000405  id=0923ef1d-6596-45f5-abfb-e33270ce8d15
update champion_skills set skill_name='Meticulous Adversary', skill_summary='Attacks 1 enemy 2 times. Each hit has a 25% chance of placing a 25% Weaken debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Soul Scythe" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='0923ef1d-6596-45f5-abfb-e33270ce8d15' and slot='A1';
update champion_skills set skill_name='Blur of Knives', skill_summary='Attacks all enemies. Has a 20% chance of granting an Extra Turn. If an Extra Turn is not granted, fills this Champion''s Turn Meter by 10% for each living enemy instead.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Soul Swap" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='0923ef1d-6596-45f5-abfb-e33270ce8d15' and slot='A2';
update champion_skills set skill_name='Deathrite Evocation', skill_summary='Places a 50% [Increase ATK] buff and a 30% [Increase C.DMG] buff on this Champion for 3 turns, then grants an Extra Turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Soul Bond" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='0923ef1d-6596-45f5-abfb-e33270ce8d15' and slot='A3';
insert into champion_skills (champion_id, skill_id, slot, form, skill_name, skill_summary, cooldown_base, cooldown_booked, damage_multiplier, multiplier_type, ascension_required, verification_status, source, review_notes)
  values ('0923ef1d-6596-45f5-abfb-e33270ce8d15', 'C000405-Passive', 'Passive', null, 'Slip Between', 'Places a [Perfect Veil] buff on this Champion for 2 turns whenever their HP drops below 50%', null, null, null, null, 3, 'proposed', 'AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', 'MISSING skill row added from AyumiLove (DB had no Passive; bad-bulk seed 104 omitted it). Needs Tier-1 confirmation.')
  on conflict (skill_id) do update set skill_name=excluded.skill_name, skill_summary=excluded.skill_summary, cooldown_base=excluded.cooldown_base, ascension_required=excluded.ascension_required, source=excluded.source, verification_status=excluded.verification_status, review_notes=excluded.review_notes;

-- Lonatharil  (DB 3 / AY 4)  prefix=C000718  id=86d9c534-e507-4437-a733-349140710f13
update champion_skills set skill_name='Gallantry', skill_summary='Attacks 1 enemy. Decreases the target''s MAX HP by 30% of the damage inflicted. Places a [Shield] buff equal to 10% of this Champion''s MAX HP for 2 turns on the ally with the lowest HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Shattering Blow" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='86d9c534-e507-4437-a733-349140710f13' and slot='A1';
update champion_skills set skill_name='Flicker Barrier', skill_summary='Attacks all enemies. Places a [Shield] buff on all allies for 3 turns equal to 20% of this Champion''s MAX HP. If there are any dead allies, place a [Shield] buff on all allies for 3 turns equal to 30% of this Champion''s MAX HP instead. This buff cannot be removed, stolen, transferred, spread, or have its duration increased or decreased by enemies or allies.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Aegis of the Fallen" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='86d9c534-e507-4437-a733-349140710f13' and slot='A2';
update champion_skills set skill_name='Finest Hour', skill_summary='Places a 30% [Increase C.DMG] buff on all allies for 2 turns, then teams up with all allies to attack a single enemy.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Coordinated Assault" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='86d9c534-e507-4437-a733-349140710f13' and slot='A3';
insert into champion_skills (champion_id, skill_id, slot, form, skill_name, skill_summary, cooldown_base, cooldown_booked, damage_multiplier, multiplier_type, ascension_required, verification_status, source, review_notes)
  values ('86d9c534-e507-4437-a733-349140710f13', 'C000718-Passive', 'Passive', null, 'Piercer', 'Inflicts 20% more damage against targets under [Shield] buffs.', null, null, null, null, 3, 'proposed', 'AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', 'MISSING skill row added from AyumiLove (DB had no Passive; bad-bulk seed 104 omitted it). Needs Tier-1 confirmation.')
  on conflict (skill_id) do update set skill_name=excluded.skill_name, skill_summary=excluded.skill_summary, cooldown_base=excluded.cooldown_base, ascension_required=excluded.ascension_required, source=excluded.source, verification_status=excluded.verification_status, review_notes=excluded.review_notes;

-- Rakka  (DB 3 / AY 4)  prefix=C000785  id=6e37034e-9325-4042-880f-3b5e9416d5db
update champion_skills set skill_name='Ichor of Life', skill_summary='Attacks 1 enemy. Heals the ally with the lowest HP by 10% of this Champion''s MAX HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Viletide Strike" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='6e37034e-9325-4042-880f-3b5e9416d5db' and slot='A1';
update champion_skills set skill_name='Oozing Blessing', skill_summary='Removes all debuffs from all allies, then places a 50% [Increase ATK] buff and a [Shield] buff equal to 25% of this Champion''s MAX HP on all allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Viletide Support" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='6e37034e-9325-4042-880f-3b5e9416d5db' and slot='A2';
update champion_skills set skill_name='Plasm Rebirth', skill_summary='Revives all dead allies with 50% HP and 50% Turn Meter, then places a [Block Debuffs] buff on all allies for 2 turns. Will place the [Block Debuffs] buff even if there are no dead allies.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Viletide Momentum" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='6e37034e-9325-4042-880f-3b5e9416d5db' and slot='A3';
insert into champion_skills (champion_id, skill_id, slot, form, skill_name, skill_summary, cooldown_base, cooldown_booked, damage_multiplier, multiplier_type, ascension_required, verification_status, source, review_notes)
  values ('6e37034e-9325-4042-880f-3b5e9416d5db', 'C000785-A4', 'A4', null, 'Creep', '[Active Effect] At the start of each turn, fills the turn meters of all allies by 10% [Passive Effect] At the start of each turn, places a 15% [Continuous Heal] buff on the ally with the lowest HP for 2 turns. Will not place the [Continuous Heal] buff on this Champion.', '3', null, null, null, 0, 'proposed', 'AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', 'MISSING skill row added from AyumiLove (DB had no A4; bad-bulk seed 104 omitted it). Needs Tier-1 confirmation.')
  on conflict (skill_id) do update set skill_name=excluded.skill_name, skill_summary=excluded.skill_summary, cooldown_base=excluded.cooldown_base, ascension_required=excluded.ascension_required, source=excluded.source, verification_status=excluded.verification_status, review_notes=excluded.review_notes;

-- Scion  (DB 3 / AY 4)  prefix=C000475  id=6bbab46c-4aef-44d6-8da8-e056bd2d373a
update champion_skills set skill_name='Nightmare Khopesh', skill_summary='Attacks 1 enemy. Has a 20% chance of placing a [Block Active Skills] debuff for 1 turn.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Cursed Strike" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='6bbab46c-4aef-44d6-8da8-e056bd2d373a' and slot='A1';
update champion_skills set skill_name='Evil Seed', skill_summary='Attacks 1 enemy. Places a [Block Buffs] debuff and a 100% [Heal Reduction] debuff for 2 turns. Will ignore any [Shield] buffs.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Bane" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='6bbab46c-4aef-44d6-8da8-e056bd2d373a' and slot='A2';
update champion_skills set skill_name='Crawling Chaos', skill_summary='Removes all debuffs from this Champion, then attacks all enemies. Places a 50% [Increase ATK] buff and a 30% [Increase C.DMG] buff on this champion for 1 turn after attacking.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Hellfire Wave" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='6bbab46c-4aef-44d6-8da8-e056bd2d373a' and slot='A3';
insert into champion_skills (champion_id, skill_id, slot, form, skill_name, skill_summary, cooldown_base, cooldown_booked, damage_multiplier, multiplier_type, ascension_required, verification_status, source, review_notes)
  values ('6bbab46c-4aef-44d6-8da8-e056bd2d373a', 'C000475-Passive', 'Passive', null, 'Incarnate', 'Enemies under [Block Active Skills], [Block Buffs] and [Heal Reduction] debuffs cannot decrease this Champion''s Turn Meter.', null, null, null, null, 3, 'proposed', 'AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', 'MISSING skill row added from AyumiLove (DB had no Passive; bad-bulk seed 104 omitted it). Needs Tier-1 confirmation.')
  on conflict (skill_id) do update set skill_name=excluded.skill_name, skill_summary=excluded.skill_summary, cooldown_base=excluded.cooldown_base, ascension_required=excluded.ascension_required, source=excluded.source, verification_status=excluded.verification_status, review_notes=excluded.review_notes;

-- Karato  (DB 4 / AY 4)  prefix=C000686  id=c8f61c77-9474-47fb-82bc-bb13a27faf21
update champion_skills set skill_name='Three Visitations', skill_summary='Attacks 1 enemy 3 times. Each hit has a 20% chance of placing a 25% [Weaken] debuff for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Kitsune''s Blades" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='c8f61c77-9474-47fb-82bc-bb13a27faf21' and slot='A1';
update champion_skills set skill_name='Bedevil', skill_summary='Attacks 1 enemy. Places a [Stun] debuff for 2 turns. Grants an Extra turn and resets the cooldown of this skill if Yumeko is on the same team and this skill kills an enemy.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Fox''s Cunning" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='c8f61c77-9474-47fb-82bc-bb13a27faf21' and slot='A2';
update champion_skills set skill_name='Suppression Ward', skill_summary='Attacks all enemies. Has an 80% chance of placing a [Block Active Skills] debuff for 2 turns. This debuff cannot be resisted if Yumeko is on the same team.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Soulscourge" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='c8f61c77-9474-47fb-82bc-bb13a27faf21' and slot='A3';
update champion_skills set skill_name='Stoicism', skill_summary='Damage inflicted by this Champion cannot be decreased by enemy passive skills or masteries, except by the Passive skills of Bosses. Damage inflicted by this Champion cannot be increased by either this Champion''s masteries or ally passive skills. Whenever Yumeko dies, instantly grants a turn to this Champion and resets the cooldowns of each of this Champion''s skills.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Soul Reaper" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='c8f61c77-9474-47fb-82bc-bb13a27faf21' and slot='Passive';

-- Demytha  (DB 4 / AY 3)  prefix=C000325  id=2f4ec323-cb69-4223-9b98-b4049a6a0fde
update champion_skills set skill_name='Fires of Old', skill_summary='Attacks 1 enemy 2 times. Places a [Shield] buff for 2 turns, equal to 10% of this Champion''s MAX HP, on the ally with the lowest HP.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Spirit Siphon" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='2f4ec323-cb69-4223-9b98-b4049a6a0fde' and slot='A1';
update champion_skills set skill_name='Light of the Deep', skill_summary='Increases the duration of ally buffs by 1 turn, then decreases the duration of all ally debuffs by 1 turn. Also heals all allies by 2.5% of their MAX HP. Heals by a further 2.5% MAX HP for each turn added to or removed from the duration of buffs and debuffs by this skill.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Miracle Heal" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='2f4ec323-cb69-4223-9b98-b4049a6a0fde' and slot='A2';
update champion_skills set skill_name='Channel the Bloodline', skill_summary='Places a [Block Damage] buff on all allies for 1 turn, and a 15% [Continuous Heal] buff on allies for 2 turns.', source='AyumiLove (human-read factual skill text) 2026-08-07 — name-corruption fix, bad-bulk audit', verification_status='proposed', review_notes='Name-only corruption fix: prior name "Hallowed Protector" (worksheet Skills tab 2026-07-11 bulk, invented). Name+summary from AyumiLove.' where champion_id='2f4ec323-cb69-4223-9b98-b4049a6a0fde' and slot='A3';

commit;

-- FLAGGED (left unchanged, need Tier-1 in-game capture):
--   Demytha A4 "Rite of Transference" — no AyumiLove source (page lists 3 skills); left unchanged, needs Tier-1
