-- 28 — champion_aliases data (generated by tools/gen-champion-aliases.mjs).
-- alias → canonical champion, for resolving name-keyed TEXT sources. Idempotent
-- (ON CONFLICT DO NOTHING on the unique lower(alias) index). Regenerate after adding
-- champions. Sources: truncation (seed-27 removals) + shortform. 135 aliases.

insert into champion_aliases (champion_id, alias, source)
select id, 'Lethelin', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Ambassador Lethelin' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Pinthroy', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Archbishop Pinthroy' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Hellmut', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Archmage Hellmut' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Golem', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Armored Golem' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Satha', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Ba Satha' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Wrestler', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Beast Wrestler' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, '''Un', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Big ''Un' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Temila', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Captain Temila' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Councilor', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Catacomb Councilor' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Yasmin', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Chancellor Yasmin' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Smasher', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Coffin Smasher' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Collector', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Corpse Collector' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Cadaver', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Corpulent Cadaver' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Corruptor', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Corvis the Corruptor' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Corvis', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Corvis the Corruptor' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Lix', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Countess Lix' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Helm', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Crimson Helm' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Blue', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Criodan the Blue' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Criodan', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Criodan the Blue' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Witch', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Crypt Witch' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Graal', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Crypt-King Graal' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Armstrong', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Deacon Armstrong' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Sinner', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Defiled Sinner' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Bloodtwin', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Drexthar Bloodtwin' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Drexthar', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Drexthar Bloodtwin' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Lilitu', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Duchess Lilitu' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Skarg', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Elder Skarg' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Auditore', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Ezio Auditore' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Fahrakin', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Fahrakin the Fat' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Fat', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Fahrakin the Fat' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Cleric', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Fang Cleric' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Bard', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Fodbor the Bard' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Fodbor', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Fodbor the Bard' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Folan', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Folan Silverhart' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Silverhart', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Folan Silverhart' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Pallas', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Glorious Pallas' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Gnishak', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Gnishak Verminlord' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Verminlord', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Gnishak Verminlord' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Aniri', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Godseeker Aniri' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Reaper', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Golden Reaper' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Jarl', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Grizzled Jarl' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Jack', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Harvest Jack' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Slinger', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Hatchet Slinger' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Khatun', 'shortform' from champions
where game_id='raid_shadow_legends' and name='High Khatun' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Nomad', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Hill Nomad' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Spawn', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Hound Spawn' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Baroness', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Infernal Baroness' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Shamael', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Inquisitor Shamael' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Brago', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Iron Brago' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Wolfhart', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Jorad Wolfhart' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Gallcobar', 'shortform' from champions
where game_id='raid_shadow_legends' and name='King Gallcobar' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Garog', 'shortform' from champions
where game_id='raid_shadow_legends' and name='King Garog' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Errant', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Knight Errant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Annabelle', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lady Annabelle' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Eresh', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lady Eresh' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Etessa', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lady Etessa' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Kimi', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lady Kimi' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Mikage', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lady Mikage' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Ireth', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lady of Ireth' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Quilen', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lady Quilen' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Chosen', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lanakis the Chosen' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Lanakis', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Lanakis the Chosen' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Annie', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Little Miss Annie' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Torrux', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Longsword Torrux' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Champfort', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lord Champfort' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Shazar', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lord Shazar' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Legionary', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Lordly Legionary' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Serris', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Madame Serris' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Gallant', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Marius the Gallant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Marius', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Marius the Gallant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Butcher', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Master Butcher' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Diviner', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Mavara the Web Diviner' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Mavara', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Mavara the Web Diviner' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Monster', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Miscreated Monster' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Bronzelock', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Morag Bronzelock' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Morag', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Morag Bronzelock' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Cybele', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Mother Cybele' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Superior', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Mother Superior' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'King', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Mountain King' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Hand', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Mystic Hand' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Narma', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Narma the Returned' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Returned', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Narma the Returned' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Thaar', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Nekmo Thaar' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Brawler', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Occult Brawler' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Keeper', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Pain Keeper' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Pelops', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Pelops the Victor' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Victor', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Pelops the Victor' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'One', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Pitiless One' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Fireheart', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Polar Fireheart' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Kymar', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Prince Kymar' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Crowned', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Quargan the Crowned' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Quargan', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Quargan the Crowned' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Hearts', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Queen of Hearts' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Archer', 'shortform' from champions
where game_id='raid_shadow_legends' and name='R. N. Archer' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Sergeant', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Rearguard Sergeant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Drath', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Rector Drath' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Tender', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Reliquary Tender' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Bold', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Richtoff the Bold' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Richtoff', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Richtoff the Bold' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Breaker', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Rock Breaker' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Huntsman', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Royal Huntsman' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Dazdurk', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Runekeeper Dazdurk' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Warder', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Runic Warder' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Distant', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Sabrael the Distant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Sabrael', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Sabrael the Distant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Protector', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Sanctum Protector' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Drakes', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Scyl of the Drakes' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Scyl', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Scyl of the Drakes' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Scyl of', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Scyl of the Drakes' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Artimage', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Sir Artimage' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Nicholas', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Sir Nicholas' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Thug', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Snorting Thug' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Dragonbane', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Staltus Dragonbane' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Staltus', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Staltus Dragonbane' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Marshal', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Steadfast Marshal' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Beast', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Stitched Beast' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Axeman', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Stout Axeman' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Wukong', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Sun Wukong' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Katonn', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Suzerain Katonn' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Savant', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Teodor the Savant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Teodor', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Teodor the Savant' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Foulbeard', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Tholin Foulbeard' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Tholin', 'truncation' from champions
where game_id='raid_shadow_legends' and name='Tholin Foulbeard' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Lord', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Tomb Lord' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Titan', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Towering Titan' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Ixlimor', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Tyrant Ixlimor' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Deathknight', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Ultimate Deathknight' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Enchantress', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Umbral Enchantress' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Brogni', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Underpriest Brogni' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Icecrusher', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Ursine Icecrusher' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Ironhide', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Ursine Ironhide' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Ovelis', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Vizier Ovelis' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Mother', 'shortform' from champions
where game_id='raid_shadow_legends' and name='War Mother' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Silken', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Wyrennon the Silken' on conflict do nothing;
insert into champion_aliases (champion_id, alias, source)
select id, 'Wyrennon', 'shortform' from champions
where game_id='raid_shadow_legends' and name='Wyrennon the Silken' on conflict do nothing;
