-- ============================================================================
-- 70 — Rebuild champions.affinity from the validated Champions-tab roster.
--
-- The DB affinity column was ~26.8% accurate vs raid.guide (≈ random for 4
-- affinities) — effectively non-data. The Champions tab is 99.9% accurate vs
-- raid.guide (676/677) and won every in-game spot-check. This sets affinity to
-- the Champions-tab value for every mismatched row. raid.guide independently
-- corroborates 477 of the 610 corrections; the rest are Champions-tab-only
-- (that source's error rate is ~0.1%). Gaius the Gleeful HELD (raid.guide=Magic
-- vs Champions tab/DB=Force — needs in-game verification, not touched here).
-- Idempotent: only updates rows whose affinity still differs.
-- Sources: Champions-tab roster + raid.guide affinity pull (2026-07-07).
-- ============================================================================

update champions c set affinity = v.aff
from (values
  ('Abbess', 'Force'),
  ('Abyssal', 'Spirit'),
  ('Acelin', 'Spirit'),
  ('Acolyte', 'Force'),
  ('Acrizia', 'Void'),
  ('Adriel', 'Magic'),
  ('Aeila', 'Void'),
  ('Aeshma', 'Magic'),
  ('Ailil', 'Void'),
  ('Aina', 'Magic'),
  ('Akemtum', 'Void'),
  ('Alaz', 'Force'),
  ('Aleksandr', 'Magic'),
  ('Alika', 'Force'),
  ('Alsgor', 'Force'),
  ('Altan', 'Magic'),
  ('Alure', 'Magic'),
  ('Amoch', 'Magic'),
  ('Anax', 'Spirit'),
  ('Anchorite', 'Spirit'),
  ('Androc', 'Spirit'),
  ('Andryssia', 'Void'),
  ('Angar', 'Void'),
  ('Anointed', 'Force'),
  ('Aothar', 'Force'),
  ('Aox', 'Force'),
  ('Apothecary', 'Magic'),
  ('April', 'Magic'),
  ('Arachoa', 'Force'),
  ('Aragaz', 'Force'),
  ('Arashi', 'Spirit'),
  ('Aratheia', 'Void'),
  ('Arbais', 'Force'),
  ('Arbalester', 'Void'),
  ('Arcanist', 'Force'),
  ('Archbishop Pinthroy', 'Spirit'),
  ('Arix', 'Magic'),
  ('Arndulf', 'Magic'),
  ('Arne', 'Magic'),
  ('Arnorn', 'Void'),
  ('Artak', 'Magic'),
  ('Ashwalker', 'Void'),
  ('Assassin', 'Magic'),
  ('Astralith', 'Spirit'),
  ('Atur', 'Magic'),
  ('Avenger', 'Magic'),
  ('Avir', 'Magic'),
  ('Azure', 'Void'),
  ('Ba Satha', 'Magic'),
  ('Bad-el-Kazar', 'Force'),
  ('Baerd', 'Magic'),
  ('Baerdal', 'Void'),
  ('Balar', 'Spirit'),
  ('Balthus', 'Spirit'),
  ('Banshee', 'Magic'),
  ('Baron', 'Void'),
  ('Baroth', 'Force'),
  ('Basher', 'Void'),
  ('Basilisk', 'Force'),
  ('Basim', 'Force'),
  ('Battlesage', 'Void'),
  ('Bayek', 'Void'),
  ('Beast Wrestler', 'Force'),
  ('Belanor', 'Void'),
  ('Belletar', 'Void'),
  ('Bellower', 'Void'),
  ('Belz', 'Spirit'),
  ('Bergoth', 'Spirit'),
  ('Berserker', 'Spirit'),
  ('Bivald', 'Spirit'),
  ('Black Knight', 'Force'),
  ('Bladerider', 'Magic'),
  ('Blind Seer', 'Void'),
  ('Bloodbraid', 'Spirit'),
  ('Bloodhorn', 'Void'),
  ('Bloodpainter', 'Force'),
  ('Bogwalker', 'Force'),
  ('Bolint', 'Force'),
  ('Boltsmith', 'Force'),
  ('Bone Knight', 'Spirit'),
  ('Bonekeeper', 'Force'),
  ('Boragar', 'Force'),
  ('Bovos', 'Spirit'),
  ('Broadmaw', 'Void'),
  ('Broodlord', 'Force'),
  ('Bulwark', 'Void'),
  ('Bystophus', 'Force'),
  ('Cagebound', 'Void'),
  ('Cagebreaker', 'Spirit'),
  ('Candleguard', 'Magic'),
  ('Candraphon', 'Force'),
  ('Canoness', 'Magic'),
  ('Caoilte', 'Magic'),
  ('Captain Temila', 'Magic'),
  ('Cardiel', 'Void'),
  ('Cardinal', 'Void'),
  ('Carlinia', 'Spirit'),
  ('Castigator', 'Magic'),
  ('Catacomb Councilor', 'Magic'),
  ('Cecilia', 'Void'),
  ('Ceez', 'Force'),
  ('Centurion', 'Void'),
  ('Chaagur', 'Void'),
  ('Chalco', 'Void'),
  ('Chancellor Yasmin', 'Force'),
  ('Chani', 'Magic'),
  ('Channeler', 'Spirit'),
  ('Chaplain', 'Force'),
  ('Cheshire', 'Spirit'),
  ('Chevalier', 'Void'),
  ('Chonoru', 'Spirit'),
  ('Chopper', 'Magic'),
  ('Cillian', 'Magic'),
  ('Cleopterix', 'Spirit'),
  ('Coffin Smasher', 'Magic'),
  ('Coldheart', 'Void'),
  ('Conellia', 'Magic'),
  ('Confessor', 'Void'),
  ('Conquerer', 'Spirit'),
  ('Corpse Collector', 'Force'),
  ('Corvis the Corruptor', 'Magic'),
  ('Crimson Helm', 'Spirit'),
  ('Crimson Slayer', 'Spirit'),
  ('Crohnam', 'Magic'),
  ('Crossbowman', 'Magic'),
  ('Cruetraxa', 'Void'),
  ('Crypt Witch', 'Magic'),
  ('Cudgeler', 'Magic'),
  ('Cupidus', 'Spirit'),
  ('Dagger', 'Void'),
  ('Danag', 'Magic'),
  ('Dark Athel', 'Magic'),
  ('Dark Kael', 'Magic'),
  ('Daywalker', 'Void'),
  ('Deathchanter', 'Magic'),
  ('Deathless', 'Spirit'),
  ('Defiled Sinner', 'Force'),
  ('Delaaja', 'Spirit'),
  ('Deliana', 'Force'),
  ('Delver', 'Spirit'),
  ('Demytha', 'Void'),
  ('Dhukk', 'Magic'),
  ('Diamant', 'Void'),
  ('Dilgol', 'Void'),
  ('Djamarsa', 'Force'),
  ('Dolor', 'Force'),
  ('Doompriest', 'Force'),
  ('Dracomorph', 'Magic'),
  ('Draconis', 'Void'),
  ('Drokgul', 'Spirit'),
  ('Dyana', 'Void'),
  ('Elder Skarg', 'Force'),
  ('Elegaius', 'Magic'),
  ('Elenaril', 'Magic'),
  ('Embrys', 'Force'),
  ('Emic', 'Void'),
  ('Endalia', 'Magic'),
  ('Eolfrig', 'Spirit'),
  ('Erinyes', 'Force'),
  ('Errol', 'Force'),
  ('Esme', 'Force'),
  ('Ethlen', 'Void'),
  ('Eviscerator', 'Void'),
  ('Excruciator', 'Magic'),
  ('Executioner', 'Magic'),
  ('Exemplar', 'Void'),
  ('Fanatic', 'Void'),
  ('Fayne', 'Spirit'),
  ('Fellhound', 'Void'),
  ('Fenax', 'Spirit'),
  ('Fenshi', 'Force'),
  ('Firrol', 'Spirit'),
  ('Fjorad', 'Spirit'),
  ('Flailer', 'Magic'),
  ('Flesh-Tearer', 'Magic'),
  ('Flesheater', 'Spirit'),
  ('Fleshmonger', 'Magic'),
  ('Foli', 'Magic'),
  ('Fortus', 'Void'),
  ('Freyja', 'Force'),
  ('Frolni', 'Magic'),
  ('Fu-Shan', 'Force'),
  ('Furystoker', 'Spirit'),
  ('Fylja', 'Magic'),
  ('Gaellut', 'Void'),
  ('Gala', 'Void'),
  ('Galapo', 'Magic'),
  ('Galek', 'Magic'),
  ('Galkut', 'Spirit'),
  ('Gamuran', 'Spirit'),
  ('Gaspard', 'Void'),
  ('Gator', 'Magic'),
  ('Geargrinder', 'Void'),
  ('Genbo', 'Void'),
  ('Gerhard', 'Magic'),
  ('Ghomm', 'Void'),
  ('Ghostborn', 'Spirit'),
  ('Giath', 'Magic'),
  ('Ginro', 'Void'),
  ('Gizmak', 'Magic'),
  ('Gladewulf', 'Void'),
  ('Glaicad', 'Force'),
  ('Gliseah', 'Force'),
  ('Gloril', 'Spirit'),
  ('Gnarlhorn', 'Spirit'),
  ('Gnarox', 'Magic'),
  ('Gnut', 'Spirit'),
  ('Godseeker Aniri', 'Void'),
  ('Goffred', 'Magic'),
  ('Golden Reaper', 'Void'),
  ('Goremask', 'Force'),
  ('Gorgorab', 'Magic'),
  ('Gory', 'Spirit'),
  ('Graazur', 'Void'),
  ('Grandmaster', 'Magic'),
  ('Granyt', 'Spirit'),
  ('Grappler', 'Spirit'),
  ('Gretel', 'Force'),
  ('Grizzled Jarl', 'Magic'),
  ('Grohak', 'Magic'),
  ('Grugtha', 'Magic'),
  ('Grumbler', 'Magic'),
  ('Guardian', 'Spirit'),
  ('Gurgoh', 'Void'),
  ('Guurda', 'Force'),
  ('Gwyndolin', 'Force'),
  ('Gwynneth', 'Magic'),
  ('Haarken', 'Void'),
  ('Hakkorhn', 'Magic'),
  ('Hansel', 'Magic'),
  ('Harima', 'Force'),
  ('Harrier', 'Void'),
  ('Haruspex', 'Void'),
  ('Harvester', 'Void'),
  ('He-Man', 'Magic'),
  ('Headsman', 'Spirit'),
  ('Hegemon', 'Void'),
  ('Heiress', 'Force'),
  ('Helicath', 'Spirit'),
  ('Helior', 'Force'),
  ('Hellfang', 'Spirit'),
  ('Hellfreak', 'Spirit'),
  ('Hellgazer', 'Spirit'),
  ('Hephraak', 'Magic'),
  ('Hexia', 'Force'),
  ('Hexweaver', 'Spirit'),
  ('Hilda', 'Force'),
  ('Hilvi', 'Force'),
  ('Hoforees', 'Force'),
  ('Hollow', 'Void'),
  ('Hoskarul', 'Spirit'),
  ('Hound Spawn', 'Force'),
  ('Huntress', 'Void'),
  ('Hurler', 'Force'),
  ('Hurndig', 'Magic'),
  ('Husk', 'Force'),
  ('Hyria', 'Spirit'),
  ('Ifrit', 'Void'),
  ('Ilysinya', 'Force'),
  ('Infernal Baroness', 'Force'),
  ('Ingid', 'Spirit'),
  ('Inithwe', 'Void'),
  ('Inquisitor Shamael', 'Void'),
  ('Interceptor', 'Void'),
  ('Iron Brago', 'Spirit'),
  ('Ishiyama', 'Spirit'),
  ('Ithos', 'Void'),
  ('Itinerant', 'Force'),
  ('Jarang', 'Magic'),
  ('Jareg', 'Magic'),
  ('Jetni', 'Spirit'),
  ('Jinglehunter', 'Spirit'),
  ('Jingwon', 'Void'),
  ('Jintoro', 'Magic'),
  ('Jizoh', 'Spirit'),
  ('Judge', 'Magic'),
  ('Judicator', 'Spirit'),
  ('Jurojin', 'Spirit'),
  ('Justiciar', 'Void'),
  ('Kaja', 'Spirit'),
  ('Kallia', 'Force'),
  ('Kalvalax', 'Spirit'),
  ('Kantra', 'Force'),
  ('Karam', 'Force'),
  ('Karato', 'Spirit'),
  ('Karilon', 'Void'),
  ('Karnage', 'Spirit'),
  ('Kawn', 'Void'),
  ('Keberon', 'Force'),
  ('Keeyra', 'Spirit'),
  ('Kellan', 'Magic'),
  ('Khafru', 'Void'),
  ('Khoronar', 'Void'),
  ('Kinagashi', 'Spirit'),
  ('King Garog', 'Force'),
  ('Klaazag', 'Void'),
  ('Klodd', 'Magic'),
  ('Knave', 'Force'),
  ('Knight-Errant', 'Spirit'),
  ('Komidus', 'Magic'),
  ('Konstantin', 'Void'),
  ('Korugar', 'Force'),
  ('Kosk', 'Force'),
  ('Kreela', 'Magic'),
  ('Kroz', 'Spirit'),
  ('Kunoichi', 'Force'),
  ('Kurosa', 'Force'),
  ('Kurzad', 'Void'),
  ('Kyoku', 'Spirit'),
  ('Kytis', 'Spirit'),
  ('Lady Annabelle', 'Spirit'),
  ('Lady Eresh', 'Force'),
  ('Lady Etessa', 'Force'),
  ('Lady Kimi', 'Magic'),
  ('Lady Mikage', 'Force'),
  ('Lady Quilen', 'Force'),
  ('Lady of Ireth', 'Spirit'),
  ('Leminisi', 'Force'),
  ('Leorius', 'Void'),
  ('Liburga', 'Void'),
  ('Lich', 'Force'),
  ('Lifetaker', 'Magic'),
  ('Lightsworn', 'Void'),
  ('Locwain', 'Magic'),
  ('Lodric', 'Spirit'),
  ('Lonatharil', 'Force'),
  ('Longbeard', 'Magic'),
  ('Lord Champfort', 'Magic'),
  ('Lordly Legionary', 'Magic'),
  ('Lua', 'Void'),
  ('Lugan', 'Spirit'),
  ('Luria', 'Spirit'),
  ('Luthiea', 'Force'),
  ('Lydia', 'Void'),
  ('Lyssandra', 'Spirit'),
  ('Maddak', 'Magic'),
  ('Madman', 'Spirit'),
  ('Magister', 'Force'),
  ('Magnarr', 'Spirit'),
  ('Malbranche', 'Void'),
  ('Malkith', 'Spirit'),
  ('Maneater', 'Void'),
  ('Maranix', 'Force'),
  ('Marauder', 'Spirit'),
  ('Margrave', 'Force'),
  ('Marichka', 'Void'),
  ('Marked', 'Magic'),
  ('Marksman', 'Spirit'),
  ('Martyr', 'Spirit'),
  ('Masamoto', 'Spirit'),
  ('Master Butcher', 'Spirit'),
  ('Mathias', 'Force'),
  ('Maulie', 'Spirit'),
  ('Mausoleum Mage', 'Force'),
  ('Melga', 'Spirit'),
  ('Merouka', 'Magic'),
  ('Metalshaper', 'Spirit'),
  ('Mezomel', 'Spirit'),
  ('Michinaki', 'Magic'),
  ('Minaya', 'Force'),
  ('Missionary', 'Force'),
  ('Mistress', 'Spirit'),
  ('Mithrala', 'Void'),
  ('Modo', 'Force'),
  ('Mordecai', 'Force'),
  ('Morrigaine', 'Magic'),
  ('Mortu-Macaab', 'Spirit'),
  ('Mother Cybele', 'Force'),
  ('Mother Superior', 'Spirit'),
  ('Mycolus', 'Void'),
  ('Myrmidon', 'Magic'),
  ('Mystic Hand', 'Force'),
  ('Nais', 'Magic'),
  ('Nari', 'Force'),
  ('Nazana', 'Force'),
  ('Necrohunter', 'Magic'),
  ('Nekhret', 'Void'),
  ('Nekmo Thaar', 'Spirit'),
  ('Nell', 'Magic'),
  ('Nethril', 'Spirit'),
  ('Niamhe', 'Void'),
  ('Nobel', 'Force'),
  ('Noct', 'Magic'),
  ('Nogdar', 'Spirit'),
  ('Nogoryo', 'Magic'),
  ('Noldua', 'Force'),
  ('Norog', 'Magic'),
  ('Oathbound', 'Force'),
  ('Oboro', 'Void'),
  ('Occult Brawler', 'Spirit'),
  ('Odachi', 'Force'),
  ('Odin', 'Void'),
  ('Oella', 'Magic'),
  ('Osgrun', 'Magic'),
  ('Ox', 'Void'),
  ('Pain Keeper', 'Void'),
  ('Painsmith', 'Void'),
  ('Pann', 'Force'),
  ('Pestilus', 'Spirit'),
  ('Peydma', 'Void'),
  ('Pheidi', 'Void'),
  ('Phemo', 'Magic'),
  ('Pitiless One', 'Magic'),
  ('Polara', 'Force'),
  ('Pounder', 'Magic'),
  ('Preserver', 'Force'),
  ('Prosecutor', 'Spirit'),
  ('Prundar', 'Void'),
  ('Psylar', 'Void'),
  ('Purgator', 'Magic'),
  ('Pythion', 'Force'),
  ('Pyxniel', 'Magic'),
  ('Quaestor', 'Force'),
  ('Quargan the Crowned', 'Spirit'),
  ('Queen of Hearts', 'Void'),
  ('Quintus', 'Void'),
  ('Ragash', 'Spirit'),
  ('Ragemonger', 'Void'),
  ('Raglin', 'Void'),
  ('Raider', 'Spirit'),
  ('Rakka', 'Void'),
  ('Ramantu', 'Void'),
  ('Razelvarg', 'Magic'),
  ('Rearguard Sergeant', 'Force'),
  ('Rector Drath', 'Force'),
  ('Reinbeast', 'Force'),
  ('Relickeeper', 'Force'),
  ('Reliquary Tender', 'Void'),
  ('Renegade', 'Void'),
  ('Renouncer', 'Force'),
  ('Retainer', 'Void'),
  ('Rhaia', 'Void'),
  ('Rian', 'Force'),
  ('Riho', 'Void'),
  ('Ripper', 'Force'),
  ('Ripperfist', 'Void'),
  ('Riscarm', 'Spirit'),
  ('Robar', 'Force'),
  ('Rock Breaker', 'Spirit'),
  ('Rockbeast', 'Void'),
  ('Roric', 'Spirit'),
  ('Rotos', 'Magic'),
  ('Rotting Mage', 'Spirit'),
  ('Rowan', 'Void'),
  ('Roxam', 'Magic'),
  ('Royal Guard', 'Magic'),
  ('Royal Huntsman', 'Spirit'),
  ('Ruel', 'Spirit'),
  ('Ruella', 'Spirit'),
  ('Ruffstone', 'Force'),
  ('Rugnor', 'Void'),
  ('Runekeeper Dazdurk', 'Void'),
  ('Samar', 'Spirit'),
  ('Samson', 'Spirit'),
  ('Sanguinia', 'Magic'),
  ('Scabrius', 'Magic'),
  ('Scion', 'Magic'),
  ('Scrapper', 'Void'),
  ('Searsha', 'Force'),
  ('Seducer', 'Void'),
  ('Seeker', 'Magic'),
  ('Selinia', 'Void'),
  ('Seneschal', 'Force'),
  ('Senna', 'Void'),
  ('Septimus', 'Spirit'),
  ('Sepulcher Sentinel', 'Force'),
  ('Shaman', 'Force'),
  ('Shamrock', 'Spirit'),
  ('Shatterbones', 'Force'),
  ('Shemnath', 'Magic'),
  ('Shu-Zhen', 'Void'),
  ('Sicia', 'Force'),
  ('Siegebreaker', 'Spirit'),
  ('Siegehulk', 'Magic'),
  ('Siegfrund', 'Magic'),
  ('Sigmund', 'Magic'),
  ('Silvain', 'Void'),
  ('Siphi', 'Void'),
  ('Sir Nicholas', 'Void'),
  ('Skathix', 'Void'),
  ('Skeletor', 'Spirit'),
  ('Skeuramis', 'Magic'),
  ('Skimfos', 'Void'),
  ('Skink', 'Magic'),
  ('Skirmisher', 'Void'),
  ('Skorid', 'Magic'),
  ('Skullcrusher', 'Force'),
  ('Skytouched Shaman', 'Void'),
  ('Slasher', 'Spirit'),
  ('Slitherbrute', 'Magic'),
  ('Slixus', 'Void'),
  ('Snorting Thug', 'Force'),
  ('Solanar', 'Void'),
  ('Sorceress', 'Force'),
  ('Souldrinker', 'Force'),
  ('Spikehead', 'Magic'),
  ('Spymaster', 'Force'),
  ('Steadfast Marshal', 'Void'),
  ('Stitched Beast', 'Void'),
  ('Stokk', 'Spirit'),
  ('Stout Axeman', 'Magic'),
  ('Suiren', 'Force'),
  ('Sulfuryion', 'Void'),
  ('Sun Wukong', 'Spirit'),
  ('Supreme Athel', 'Void'),
  ('Supreme Elhain', 'Void'),
  ('Supreme Galek', 'Void'),
  ('Supreme Kael', 'Void'),
  ('Suzerain Katonn', 'Spirit'),
  ('Sydax', 'Spirit'),
  ('Tagoar', 'Magic'),
  ('Tainix', 'Force'),
  ('Talenna', 'Spirit'),
  ('Taras', 'Void'),
  ('Tarshon', 'Spirit'),
  ('Taurus', 'Magic'),
  ('Taya', 'Void'),
  ('Tayrel', 'Magic'),
  ('Teela', 'Magic'),
  ('Tekteon', 'Void'),
  ('Templar', 'Spirit'),
  ('Temptress', 'Magic'),
  ('Terrorbeast', 'Spirit'),
  ('Teryx', 'Void'),
  ('Tetsuya', 'Magic'),
  ('Teumesia', 'Void'),
  ('Thea', 'Force'),
  ('Thenasil', 'Force'),
  ('Theodosia', 'Force'),
  ('Theresc', 'Force'),
  ('Thor', 'Magic'),
  ('Thorn', 'Void'),
  ('Thylessia', 'Force'),
  ('Tigersoul', 'Spirit'),
  ('Titus', 'Void'),
  ('Togron', 'Void'),
  ('Tolf', 'Void'),
  ('Tomb Lord', 'Spirit'),
  ('Toragi', 'Magic'),
  ('Tormin', 'Void'),
  ('Torturehelm', 'Force'),
  ('Toshiro', 'Magic'),
  ('Totem', 'Spirit'),
  ('Towering Titan', 'Void'),
  ('Tramaria', 'Void'),
  ('Treefeller', 'Force'),
  ('Truath', 'Magic'),
  ('Trunda', 'Magic'),
  ('Tuhak', 'Void'),
  ('Turvold', 'Void'),
  ('Twinclaw', 'Force'),
  ('Tyrant Ixlimor', 'Magic'),
  ('Ugir', 'Spirit'),
  ('Ultan', 'Spirit'),
  ('Ultimate Galek', 'Magic'),
  ('Urost', 'Void'),
  ('Ursala', 'Void'),
  ('Ursine Icecrusher', 'Force'),
  ('Ursuga', 'Void'),
  ('Urticata', 'Spirit'),
  ('Vagabond', 'Spirit'),
  ('Valerie', 'Magic'),
  ('Valkanen', 'Void'),
  ('Valla', 'Spirit'),
  ('Vanguard', 'Void'),
  ('Varkos', 'Force'),
  ('Varl', 'Spirit'),
  ('Vasal', 'Force'),
  ('Venalicia', 'Force'),
  ('Venomage', 'Magic'),
  ('Venus', 'Void'),
  ('Vergis', 'Spirit'),
  ('Veteran', 'Void'),
  ('Vildrax', 'Magic'),
  ('Visix', 'Void'),
  ('Vitrius', 'Void'),
  ('Vizug', 'Magic'),
  ('Vogoth', 'Spirit'),
  ('Vulkanos', 'Force'),
  ('Walking Tomb Dreng', 'Spirit'),
  ('Wanderer', 'Spirit'),
  ('War Mother', 'Magic'),
  ('Warcaster', 'Void'),
  ('Warchief', 'Force'),
  ('Warden', 'Spirit'),
  ('Warlord', 'Void'),
  ('Warmaiden', 'Force'),
  ('Weregren', 'Void'),
  ('Whisper', 'Void'),
  ('Witness', 'Magic'),
  ('Woad-Painted', 'Spirit'),
  ('Wretch', 'Force'),
  ('Wuji', 'Force'),
  ('Wythir', 'Force'),
  ('Wyvernbane', 'Spirit'),
  ('Xena', 'Force'),
  ('Xenomorph', 'Magic'),
  ('Yaga', 'Force'),
  ('Yakarl', 'Void'),
  ('Yannica', 'Spirit'),
  ('Yelagirna', 'Spirit'),
  ('Yncensa', 'Void'),
  ('Yoshi', 'Force'),
  ('Yukimasa', 'Force'),
  ('Yumeko', 'Void'),
  ('Yuzan', 'Void'),
  ('Zargala', 'Force'),
  ('Zavia', 'Force'),
  ('Zelotah', 'Spirit'),
  ('Zii', 'Force')
) as v(name, aff)
where c.game_id = 'raid_shadow_legends' and c.name = v.name and c.affinity <> v.aff;
