-- Reconciled role updates, keyed to actual champions.name.
-- Composition: exact + unique prefix + unique suffix matches. Ambiguous/gaps excluded.
-- Includes seed INSERT for Gracchos Turn-drake (idempotent) so this file runs standalone, INSERT before UPDATE.
--
-- Renumbered 46 -> 94 during the 2026-07-09 branch reconciliation (origin/main already
-- owned seed 46). Three names updated to canonical to match this session's rename/merge
-- seeds, which run BEFORE this file: 'Incarnate'->'The Incarnate' (seed 89),
-- 'Polara'->'Polara Fireheart' (seed 87 merge), 'Jotunn'->'Jotun' (seed 86). Roles
-- unchanged. If this file is ever reordered ahead of 86-89, revert those three names.

insert into champions (name, faction, affinity, rarity, role, source_citation)
values ('Gracchos Turn-drake', 'Demonspawn', 'Force', 'Legendary', 'HP',
        'RAID Master Database v4.0 (master roster spreadsheet); seeded to resolve role-update name gap (spreadsheet: Gracchos Turn Drake)')
on conflict (name) do nothing;

update champions set role = 'Defense' where name = 'Alaz';
update champions set role = 'Defense' where name = 'Anaxia';
update champions set role = 'Defense' where name = 'Androc';
update champions set role = 'Attack' where name = 'Aphidus';
update champions set role = 'Support' where name = 'Arachoa';
update champions set role = 'Support' where name = 'Arbais';
update champions set role = 'Attack' where name = 'Arne';
update champions set role = 'HP' where name = 'Ash''nar';
update champions set role = 'Attack' where name = 'Abbess';
update champions set role = 'Defense' where name = 'Acelin';
update champions set role = 'Attack' where name = 'Acrizia';
update champions set role = 'Support' where name = 'Blacktusk';
update champions set role = 'Attack' where name = 'Ailil';
update champions set role = 'Attack' where name = 'Aleksandr';
update champions set role = 'HP' where name = 'Alsgor';
update champions set role = 'Defense' where name = 'Altan';
update champions set role = 'Support' where name = 'Amoch';
update champions set role = 'HP' where name = 'Angar';
update champions set role = 'Support' where name = 'April';
update champions set role = 'HP' where name = 'Aragaz';
update champions set role = 'HP' where name = 'Arashi';
update champions set role = 'Attack' where name = 'Aratheia';
update champions set role = 'Support' where name = 'Arbiter';
update champions set role = 'Support' where name = 'Archbishop Pinthroy';
update champions set role = 'HP' where name = 'Arix';
update champions set role = 'Support' where name = 'Armanz';
update champions set role = 'Attack' where name = 'Arnorn';
update champions set role = 'HP' where name = 'Artak';
update champions set role = 'Attack' where name = 'Astralith';
update champions set role = 'Attack' where name = 'Astralon';
update champions set role = 'Support' where name = 'Lamasu';
update champions set role = 'Support' where name = 'Achak';
update champions set role = 'Support' where name = 'Adriel';
update champions set role = 'Support' where name = 'Aeila';
update champions set role = 'Attack' where name = 'Aeshma';
update champions set role = 'Attack' where name = 'Aina';
update champions set role = 'Attack' where name = 'Akemtum';
update champions set role = 'Defense' where name = 'Akoth';
update champions set role = 'Attack' where name = 'Alaric';
update champions set role = 'Attack' where name = 'Alika';
update champions set role = 'Attack' where name = 'Alure';
update champions set role = 'Support' where name = 'Ambassador Lethelin';
update champions set role = 'Attack' where name = 'Anax';
update champions set role = 'Support' where name = 'Anchorite';
update champions set role = 'Defense' where name = 'Andryssia';
update champions set role = 'Attack' where name = 'Aothar';
update champions set role = 'Support' where name = 'Aox';
update champions set role = 'Support' where name = 'Archmage Hellmut';
update champions set role = 'Attack' where name = 'Armina';
update champions set role = 'Defense' where name = 'Arndulf';
update champions set role = 'Attack' where name = 'Arwydd';
update champions set role = 'HP' where name = 'Atur';
update champions set role = 'HP' where name = 'Azure';
update champions set role = 'Support' where name = 'Abyssal';
update champions set role = 'Support' where name = 'Acolyte';
update champions set role = 'Attack' where name = 'Adjudicator';
update champions set role = 'Defense' where name = 'Amarantine Skeleton';
update champions set role = 'Support' where name = 'Anointed';
update champions set role = 'Support' where name = 'Apothecary';
update champions set role = 'Attack' where name = 'Arbalester';
update champions set role = 'Support' where name = 'Arcanist';
update champions set role = 'Attack' where name = 'Ashwalker';
update champions set role = 'Attack' where name = 'Assassin';
update champions set role = 'Attack' where name = 'Athel';
update champions set role = 'Attack' where name = 'Avenger';
update champions set role = 'Support' where name = 'Avir';
update champions set role = 'Support' where name = 'Banshee';
update champions set role = 'Attack' where name = 'Beast Wrestler';
update champions set role = 'Support' where name = 'Bellower';
update champions set role = 'Attack' where name = 'Berserker';
update champions set role = 'Attack' where name = 'Bladerider';
update champions set role = 'HP' where name = 'Bloodbraid';
update champions set role = 'HP' where name = 'Bloodhorn';
update champions set role = 'HP' where name = 'Bloodmask';
update champions set role = 'Attack' where name = 'Bloodpainter';
update champions set role = 'Defense' where name = 'Bogwalker';
update champions set role = 'Attack' where name = 'Boltsmith';
update champions set role = 'Attack' where name = 'Bombardier';
update champions set role = 'Attack' where name = 'Bone Knight';
update champions set role = 'Defense' where name = 'Flannan';
update champions set role = 'HP' where name = 'Lasair';
update champions set role = 'Defense' where name = 'Bulwark';
update champions set role = 'Defense' where name = 'Cagebound';
update champions set role = 'Attack' where name = 'Candleguard';
update champions set role = 'HP' where name = 'Castigator';
update champions set role = 'HP' where name = 'Cataphract';
update champions set role = 'Defense' where name = 'Centurion';
update champions set role = 'Support' where name = 'Channeler';
update champions set role = 'Support' where name = 'Chaplain';
update champions set role = 'Defense' where name = 'Chevalier';
update champions set role = 'Attack' where name = 'Chopper';
update champions set role = 'HP' where name = 'Coffin Smasher';
update champions set role = 'Attack' where name = 'Coldheart';
update champions set role = 'Attack' where name = 'Confessor';
update champions set role = 'Attack' where name = 'Conquerer';
update champions set role = 'HP' where name = 'Corpulent Cadaver';
update champions set role = 'Attack' where name = 'Courtier';
update champions set role = 'HP' where name = 'Pegason';
update champions set role = 'Attack' where name = 'Crimson Slayer';
update champions set role = 'Attack' where name = 'Crossbowman';
update champions set role = 'Attack' where name = 'Cudgeler';
update champions set role = 'Attack' where name = 'Dagger';
update champions set role = 'HP' where name = 'Daywalker';
update champions set role = 'HP' where name = 'Deathchanter';
update champions set role = 'Defense' where name = 'Denid';
update champions set role = 'Support' where name = 'Diabolist';
update champions set role = 'Attack' where name = 'Dilgol';
update champions set role = 'Support' where name = 'Dolor';
update champions set role = 'HP' where name = 'Doomscreech';
update champions set role = 'HP' where name = 'Draconis';
update champions set role = 'Attack' where name = 'Bloatwraith';
update champions set role = 'Attack' where name = 'Dunestrider';
update champions set role = 'Defense' where name = 'Elder';
update champions set role = 'Attack' where name = 'Elhain';
update champions set role = 'Attack' where name = 'Eviscerator';
update champions set role = 'Defense' where name = 'Executioner';
update champions set role = 'Support' where name = 'Fanatic';
update champions set role = 'Defense' where name = 'Fellhound';
update champions set role = 'Attack' where name = 'Fencer';
update champions set role = 'Defense' where name = 'Flailer';
update champions set role = 'Support' where name = 'Flesheater';
update champions set role = 'Attack' where name = 'Fleshmonger';
update champions set role = 'Attack' where name = 'Flinger';
update champions set role = 'Defense' where name = 'Goon';
update champions set role = 'Attack' where name = 'Frozen Banshee';
update champions set role = 'Support' where name = 'Furystoker';
update champions set role = 'Attack' where name = 'Galek';
update champions set role = 'Support' where name = 'Gator';
update champions set role = 'HP' where name = 'Geargrinder';
update champions set role = 'Attack' where name = 'Ghoulish Ranger';
update champions set role = 'Defense' where name = 'Gladewulf';
update champions set role = 'Attack' where name = 'Gladiator';
update champions set role = 'Support' where name = 'Cithrel';
update champions set role = 'Attack' where name = 'Gloril';
update champions set role = 'HP' where name = 'Gnarlhorn';
update champions set role = 'Attack' where name = 'Goremask';
update champions set role = 'HP' where name = 'Grandmaster';
update champions set role = 'Defense' where name = 'Grappler';
update champions set role = 'Attack' where name = 'Gravechill';
update champions set role = 'Defense' where name = 'Graybeard';
update champions set role = 'Support' where name = 'Grinner';
update champions set role = 'HP' where name = 'Grumbler';
update champions set role = 'HP' where name = 'Guardian';
update champions set role = 'Attack' where name = 'Halberdier';
update champions set role = 'Attack' where name = 'Harrier';
update champions set role = 'Support' where name = 'Haruspex';
update champions set role = 'Attack' where name = 'Harvester';
update champions set role = 'Attack' where name = 'Hatchet Slinger';
update champions set role = 'Attack' where name = 'Headsman';
update champions set role = 'Attack' where name = 'Heiress';
update champions set role = 'Support' where name = 'Hellborn';
update champions set role = 'Attack' where name = 'Hellfang';
update champions set role = 'Attack' where name = 'Hellfreak';
update champions set role = 'Support' where name = 'Hexweaver';
update champions set role = 'Support' where name = 'Boorn';
update champions set role = 'Support' where name = 'Hill Nomad';
update champions set role = 'Attack' where name = 'Hollow';
update champions set role = 'Defense' where name = 'Honor Guard';
update champions set role = 'Support' where name = 'Hospitaller';
update champions set role = 'Attack' where name = 'Hound Spawn';
update champions set role = 'Attack' where name = 'Huntress';
update champions set role = 'Attack' where name = 'Hurler';
update champions set role = 'Attack' where name = 'Hyria';
update champions set role = 'HP' where name = 'Ifrit';
update champions set role = 'Support' where name = 'Ingid';
update champions set role = 'Defense' where name = 'Interceptor';
update champions set role = 'HP' where name = 'Ironclad';
update champions set role = 'Attack' where name = 'Itinerant';
update champions set role = 'Attack' where name = 'Judge';
update champions set role = 'Attack' where name = 'Judicator';
update champions set role = 'Defense' where name = 'Justiciar';
update champions set role = 'Attack' where name = 'Kael';
update champions set role = 'Attack' where name = 'Kurzad';
update champions set role = 'HP' where name = 'Lamellar';
update champions set role = 'Support' where name = 'Lamibur';
update champions set role = 'Attack' where name = 'Lifetaker';
update champions set role = 'Attack' where name = 'Riab';
update champions set role = 'Defense' where name = 'Longsword Torrux';
update champions set role = 'Attack' where name = 'Lumberer';
update champions set role = 'Attack' where name = 'Madman';
update champions set role = 'Support' where name = 'Magister';
update champions set role = 'Attack' where name = 'Magmablood';
update champions set role = 'Attack' where name = 'Magus';
update champions set role = 'Attack' where name = 'Maiden';
update champions set role = 'Attack' where name = 'Malbranche';
update champions set role = 'HP' where name = 'Marauder';
update champions set role = 'HP' where name = 'Margrave';
update champions set role = 'Support' where name = 'Marked';
update champions set role = 'Defense' where name = 'Marquess';
update champions set role = 'Defense' where name = 'Marquis';
update champions set role = 'Support' where name = 'Master Butcher';
update champions set role = 'HP' where name = 'Tolog';
update champions set role = 'Support' where name = 'Medicus';
update champions set role = 'Support' where name = 'Metalshaper';
update champions set role = 'Attack' where name = 'Misericord';
update champions set role = 'Support' where name = 'Mother Superior';
update champions set role = 'HP' where name = 'Muckstalker';
update champions set role = 'Support' where name = 'Mycolus';
update champions set role = 'Defense' where name = 'Myrmidon';
update champions set role = 'Support' where name = 'Mystic Hand';
update champions set role = 'Defense' where name = 'Odachi';
update champions set role = 'Attack' where name = 'Jailer';
update champions set role = 'Attack' where name = 'Ordinator';
update champions set role = 'Attack' where name = 'Ox';
update champions set role = 'HP' where name = 'Pain Keeper';
update champions set role = 'Attack' where name = 'Painsmith';
update champions set role = 'Attack' where name = 'Panthera';
update champions set role = 'Defense' where name = 'Paragon';
update champions set role = 'Attack' where name = 'Cait';
update champions set role = 'Defense' where name = 'Penitent';
update champions set role = 'Attack' where name = 'Perforator';
update champions set role = 'Attack' where name = 'Petrifya';
update champions set role = 'Attack' where name = 'Pigsticker';
update champions set role = 'Defense' where name = 'Pounder';
update champions set role = 'Defense' where name = 'Preserver';
update champions set role = 'Attack' where name = 'Prosecutor';
update champions set role = 'Attack' where name = 'Purgator';
update champions set role = 'Attack' where name = 'Quaestor';
update champions set role = 'Attack' where name = 'Ragemonger';
update champions set role = 'Attack' where name = 'Raider';
update champions set role = 'Defense' where name = 'Taneko';
update champions set role = 'Support' where name = 'Reliquary Tender';
update champions set role = 'Support' where name = 'Renegade';
update champions set role = 'Attack' where name = 'Renouncer';
update champions set role = 'Defense' where name = 'Retainer';
update champions set role = 'Attack' where name = 'Ripperfist';
update champions set role = 'Defense' where name = 'Riscarm';
update champions set role = 'HP' where name = 'Rockbeast';
update champions set role = 'Attack' where name = 'Rocktooth';
update champions set role = 'Support' where name = 'Rotting Mage';
update champions set role = 'Attack' where name = 'Ruffstone';
update champions set role = 'HP' where name = 'Runic Warder';
update champions set role = 'Defense' where name = 'Sanctum Protector';
update champions set role = 'Attack' where name = 'Scrapper';
update champions set role = 'Defense' where name = 'Seducer';
update champions set role = 'Attack' where name = 'Selinia';
update champions set role = 'Defense' where name = 'Tirlac';
update champions set role = 'Attack' where name = 'Siegebreaker';
update champions set role = 'Attack' where name = 'Silvain';
update champions set role = 'Attack' where name = 'Skink';
update champions set role = 'Attack' where name = 'Skirmisher';
update champions set role = 'Attack' where name = 'Skullsworn';
update champions set role = 'Attack' where name = 'Slasher';
update champions set role = 'Attack' where name = 'Slayer';
update champions set role = 'Attack' where name = 'Slitherbrute';
update champions set role = 'Attack' where name = 'Solaris';
update champions set role = 'Attack' where name = 'Sorceress';
update champions set role = 'Attack' where name = 'Soulbond Bowyer';
update champions set role = 'Attack' where name = 'Spikehead';
update champions set role = 'Support' where name = 'Spirithost';
update champions set role = 'HP' where name = 'Spymaster';
update champions set role = 'HP' where name = 'Steadfast Marshal';
update champions set role = 'Attack' where name = 'Steel Bowyer';
update champions set role = 'Attack' where name = 'Stitched Beast';
update champions set role = 'HP' where name = 'Stout Axeman';
update champions set role = 'Attack' where name = 'Sunken Sentinel';
update champions set role = 'Defense' where name = 'Templar';
update champions set role = 'Attack' where name = 'Temptress';
update champions set role = 'Defense' where name = 'Teryx';
update champions set role = 'Support' where name = 'Theurgist';
update champions set role = 'Attack' where name = 'Tigersoul';
update champions set role = 'Attack' where name = 'Tormentor';
update champions set role = 'Support' where name = 'Totem';
update champions set role = 'Attack' where name = 'Treefeller';
update champions set role = 'Support' where name = 'Knott';
update champions set role = 'Defense' where name = 'Colwyn';
update champions set role = 'Attack' where name = 'Trugorr';
update champions set role = 'Attack' where name = 'Twinclaw';
update champions set role = 'Support' where name = 'Vagabond';
update champions set role = 'Support' where name = 'Valerie';
update champions set role = 'Defense' where name = 'Vanguard';
update champions set role = 'Defense' where name = 'Veteran';
update champions set role = 'Support' where name = 'Wagonbane';
update champions set role = 'Attack' where name = 'Wanderer';
update champions set role = 'Attack' where name = 'Warmaiden';
update champions set role = 'Support' where name = 'Warpriest';
update champions set role = 'Support' where name = 'Witness';
update champions set role = 'Attack' where name = 'Wretch';
update champions set role = 'Attack' where name = 'Wyvernbane';
update champions set role = 'Attack' where name = 'Baerdal';
update champions set role = 'Defense' where name = 'Balthus';
update champions set role = 'HP' where name = 'Baroth';
update champions set role = 'Attack' where name = 'Basher';
update champions set role = 'Attack' where name = 'Basilisk';
update champions set role = 'Support' where name = 'Battlesage';
update champions set role = 'HP' where name = 'Bergoth';
update champions set role = 'Attack' where name = 'Bloodfeather';
update champions set role = 'Attack' where name = 'Bonekeeper';
update champions set role = 'Support' where name = 'Bovos';
update champions set role = 'HP' where name = 'Bowf';
update champions set role = 'Support' where name = 'Broadmaw';
update champions set role = 'Defense' where name = 'Broodlord';
update champions set role = 'Defense' where name = 'Burangiri';
update champions set role = 'Attack' where name = 'Bushi';
update champions set role = 'Attack' where name = 'Cagebreaker';
update champions set role = 'Defense' where name = 'Canoness';
update champions set role = 'HP' where name = 'Captain Temila';
update champions set role = 'Support' where name = 'Cardinal';
update champions set role = 'Support' where name = 'Carlinia';
update champions set role = 'Attack' where name = 'Catacomb Councilor';
update champions set role = 'Attack' where name = 'Ceez';
update champions set role = 'Support' where name = 'Chancellor Yasmin';
update champions set role = 'Attack' where name = 'Chani';
update champions set role = 'Attack' where name = 'Chonoru';
update champions set role = 'Support' where name = 'Conellia';
update champions set role = 'Attack' where name = 'Cormac';
update champions set role = 'Support' where name = 'Corpse Collector';
update champions set role = 'Defense' where name = 'Crimson Helm';
update champions set role = 'Support' where name = 'Criodan the Blue';
update champions set role = 'Attack' where name = 'Crypt Witch';
update champions set role = 'Attack' where name = 'Dark Athel';
update champions set role = 'Attack' where name = 'Dark Elhain';
update champions set role = 'Attack' where name = 'Dark Kael';
update champions set role = 'Support' where name = 'Sabitha';
update champions set role = 'Support' where name = 'Deacon Armstrong';
update champions set role = 'Defense' where name = 'Deathless';
update champions set role = 'Defense' where name = 'Nagis';
update champions set role = 'Attack' where name = 'Defiled Sinner';
update champions set role = 'HP' where name = 'Delaaja';
update champions set role = 'Attack' where name = 'Delver';
update champions set role = 'Support' where name = 'Demytha';
update champions set role = 'Defense' where name = 'Dhukk';
update champions set role = 'Attack' where name = 'Dirandil';
update champions set role = 'Support' where name = 'Djamarsa';
update champions set role = 'Support' where name = 'Doompriest';
update champions set role = 'Attack' where name = 'Drake';
update champions set role = 'HP' where name = 'Duedan';
update champions set role = 'Support' where name = 'Duhr';
update champions set role = 'Attack' where name = 'Dyana';
update champions set role = 'Attack' where name = 'Enda';
update champions set role = 'HP' where name = 'Endalia';
update champions set role = 'Support' where name = 'Eolfrig';
update champions set role = 'Attack' where name = 'Erinyes';
update champions set role = 'Attack' where name = 'Ethlen';
update champions set role = 'Attack' where name = 'Excruciator';
update champions set role = 'Attack' where name = 'Exemplar';
update champions set role = 'Attack' where name = 'Faceless';
update champions set role = 'Attack' where name = 'Fahrakin the Fat';
update champions set role = 'Support' where name = 'Fang Cleric';
update champions set role = 'Attack' where name = 'Fayne';
update champions set role = 'Attack' where name = 'Fenax';
update champions set role = 'Attack' where name = 'Fenshi';
update champions set role = 'Support' where name = 'Flesh-Tearer';
update champions set role = 'Attack' where name = 'Fodbor the Bard';
update champions set role = 'Defense' where name = 'Fren''zi';
update champions set role = 'Support' where name = 'Frostbringer';
update champions set role = 'Attack' where name = 'Fylja';
update champions set role = 'Attack' where name = 'Isbeil';
update champions set role = 'Attack' where name = 'Gala';
update champions set role = 'Support' where name = 'Galapo';
update champions set role = 'Attack' where name = 'Galkut';
update champions set role = 'Attack' where name = 'Genbo';
update champions set role = 'Attack' where name = 'Geomancer';
update champions set role = 'Attack' where name = 'Gerhard';
update champions set role = 'Support' where name = 'Ghomm';
update champions set role = 'Defense' where name = 'Ghrush';
update champions set role = 'Defense' where name = 'Giscard';
update champions set role = 'Defense' where name = 'Gnarox';
update champions set role = 'Defense' where name = 'Godseeker Aniri';
update champions set role = 'Support' where name = 'Golden Reaper';
update champions set role = 'Support' where name = 'Gorgorab';
update champions set role = 'Attack' where name = 'Gorlos';
update champions set role = 'Attack' where name = 'Gory';
update champions set role = 'Defense' where name = 'Grimskin';
update champions set role = 'Defense' where name = 'Grizzled Jarl';
update champions set role = 'Support' where name = 'Grunch';
update champions set role = 'Attack' where name = 'Gwynneth';
update champions set role = 'Attack' where name = 'Haarken';
update champions set role = 'Attack' where name = 'Hellgazer';
update champions set role = 'Attack' where name = 'Hexia';
update champions set role = 'Support' where name = 'High Khatun';
update champions set role = 'Attack' where name = 'Hilda';
update champions set role = 'Support' where name = 'Hoforees';
update champions set role = 'HP' where name = 'Hope';
update champions set role = 'Attack' where name = 'Hordin';
update champions set role = 'Defense' where name = 'Hoskarul';
update champions set role = 'Defense' where name = 'Hotatsu';
update champions set role = 'HP' where name = 'Husk';
update champions set role = 'HP' where name = 'Ilysinya';
update champions set role = 'Defense' where name = 'Infernal Baroness';
update champions set role = 'Attack' where name = 'Inquisitor Shamael';
update champions set role = 'Attack' where name = 'Jarang';
update champions set role = 'HP' where name = 'Jareg';
update champions set role = 'Attack' where name = 'Jinglehunter';
update champions set role = 'Defense' where name = 'Jizoh';
update champions set role = 'Attack' where name = 'Juliana';
update champions set role = 'HP' where name = 'Jurojin';
update champions set role = 'Defense' where name = 'Kaiden';
update champions set role = 'Attack' where name = 'Kallia';
update champions set role = 'Attack' where name = 'Karam';
update champions set role = 'Attack' where name = 'Kellan';
update champions set role = 'Defense' where name = 'Khafru';
update champions set role = 'Support' where name = 'Kinagashi';
update champions set role = 'HP' where name = 'Klodd';
update champions set role = 'Attack' where name = 'Knight-Errant';
update champions set role = 'HP' where name = 'Krakarth';
update champions set role = 'Defense' where name = 'Kunoichi';
update champions set role = 'Attack' where name = 'Kytis';
update champions set role = 'Support' where name = 'Lady Annabelle';
update champions set role = 'Attack' where name = 'Lady Eresh';
update champions set role = 'Attack' where name = 'Lady Etessa';
update champions set role = 'Attack' where name = 'Lady Quilen';
update champions set role = 'Support' where name = 'Liburga';
update champions set role = 'Defense' where name = 'Lich';
update champions set role = 'Defense' where name = 'Lightsworn';
update champions set role = 'Attack' where name = 'Siendra';
update champions set role = 'Attack' where name = 'Galatea';
update champions set role = 'Attack' where name = 'Locwain';
update champions set role = 'HP' where name = 'Lodric';
update champions set role = 'Attack' where name = 'Lordly Legionary';
update champions set role = 'Attack' where name = 'Lorn';
update champions set role = 'Attack' where name = 'Lua';
update champions set role = 'Attack' where name = 'Luria';
update champions set role = 'Attack' where name = 'Luthiea';
update champions set role = 'Support' where name = 'Madame Serris';
update champions set role = 'Attack' where name = 'Maddak';
update champions set role = 'Attack' where name = 'Maeve';
update champions set role = 'HP' where name = 'Magnarr';
update champions set role = 'Support' where name = 'Malkith';
update champions set role = 'HP' where name = 'Maneater';
update champions set role = 'Attack' where name = 'Marksman';
update champions set role = 'Defense' where name = 'Masamoto';
update champions set role = 'Attack' where name = 'Fearmonger';
update champions set role = 'Support' where name = 'Mausoleum Mage';
update champions set role = 'HP' where name = 'Melga';
update champions set role = 'Defense' where name = 'Merouka';
update champions set role = 'HP' where name = 'Miscreated Monster';
update champions set role = 'HP' where name = 'Missionary';
update champions set role = 'Support' where name = 'Mistress';
update champions set role = 'Attack' where name = 'Daithi';
update champions set role = 'Defense' where name = 'Morag Bronzelock';
update champions set role = 'Support' where name = 'Mordecai';
update champions set role = 'HP' where name = 'Myciliac Priest Orn';
update champions set role = 'HP' where name = 'Nazana';
update champions set role = 'Attack' where name = 'Necrohunter';
update champions set role = 'Attack' where name = 'Neldor';
update champions set role = 'Attack' where name = 'Nogoryo';
update champions set role = 'Defense' where name = 'Oathbound';
update champions set role = 'Attack' where name = 'Oboro';
update champions set role = 'HP' where name = 'Occult Brawler';
update champions set role = 'Support' where name = 'Ghrukkus';
update champions set role = 'Support' where name = 'Jorrg';
update champions set role = 'Support' where name = 'Ostrox';
update champions set role = 'Attack' where name = 'Pann';
update champions set role = 'Support' where name = 'Pestilus';
update champions set role = 'Defense' where name = 'Peydma';
update champions set role = 'Defense' where name = 'Pharsalas';
update champions set role = 'Attack' where name = 'Phranox';
update champions set role = 'Attack' where name = 'Pitiless One';
update champions set role = 'Defense' where name = 'Prundar';
update champions set role = 'Support' where name = 'Psylar';
update champions set role = 'Support' where name = 'Quargan the Crowned';
update champions set role = 'Defense' where name = 'Rearguard Sergeant';
update champions set role = 'Support' where name = 'Rector Drath';
update champions set role = 'Defense' where name = 'Reinbeast';
update champions set role = 'Attack' where name = 'Relickeeper';
update champions set role = 'Support' where name = 'Rian';
update champions set role = 'Attack' where name = 'Ripper';
update champions set role = 'Defense' where name = 'Rock Breaker';
update champions set role = 'Defense' where name = 'Romero';
update champions set role = 'Attack' where name = 'Rowan';
update champions set role = 'Attack' where name = 'Royal Guard';
update champions set role = 'Attack' where name = 'Ruella';
update champions set role = 'Attack' where name = 'Rugnor';
update champions set role = 'Support' where name = 'Runekeeper Dazdurk';
update champions set role = 'Support' where name = 'Sachi';
update champions set role = 'Defense' where name = 'Survivor';
update champions set role = 'Support' where name = 'Sanguinia';
update champions set role = 'Attack' where name = 'Scabrius';
update champions set role = 'Attack' where name = 'Scion';
update champions set role = 'Defense' where name = 'Seeker';
update champions set role = 'Support' where name = 'Seer';
update champions set role = 'Defense' where name = 'Seneschal';
update champions set role = 'Defense' where name = 'Sepulcher Sentinel';
update champions set role = 'Support' where name = 'Shaman';
update champions set role = 'Attack' where name = 'Shatterbones';
update champions set role = 'Attack' where name = 'Siegehulk';
update champions set role = 'HP' where name = 'Signy';
update champions set role = 'Support' where name = 'Sikara';
update champions set role = 'Support' where name = 'Sinesha';
update champions set role = 'Attack' where name = 'Sir Artimage';
update champions set role = 'Support' where name = 'Skathix';
update champions set role = 'HP' where name = 'Skeuramis';
update champions set role = 'Attack' where name = 'Skimfos';
update champions set role = 'Attack' where name = 'Skraank';
update champions set role = 'Attack' where name = 'Skullcrown';
update champions set role = 'Defense' where name = 'Skullcrusher';
update champions set role = 'Support' where name = 'Skytouched Shaman';
update champions set role = 'Attack' where name = 'Slixus';
update champions set role = 'HP' where name = 'Snorting Thug';
update champions set role = 'Attack' where name = 'Souldrinker';
update champions set role = 'Support' where name = 'Spider';
update champions set role = 'Support' where name = 'Stag Knight';
update champions set role = 'Support' where name = 'Steelskull';
update champions set role = 'Attack' where name = 'Thisbe';
update champions set role = 'Attack' where name = 'Suiren';
update champions set role = 'Attack' where name = 'Suwai';
update champions set role = 'Support' where name = 'Tagoar';
update champions set role = 'Support' where name = 'Tainix';
update champions set role = 'Attack' where name = 'Tallia';
update champions set role = 'Defense' where name = 'Tarshon';
update champions set role = 'Attack' where name = 'Taurus';
update champions set role = 'Attack' where name = 'Taya';
update champions set role = 'Defense' where name = 'Tayrel';
update champions set role = 'HP' where name = 'Terrorbeast';
update champions set role = 'Defense' where name = 'Teshada';
update champions set role = 'Support' where name = 'Thenasil';
update champions set role = 'Attack' where name = 'Theresc';
update champions set role = 'Defense' where name = 'Thorn';
update champions set role = 'Attack' where name = 'Thylessia';
update champions set role = 'Support' where name = 'Dexikos';
update champions set role = 'HP' where name = 'Tolf';
update champions set role = 'Support' where name = 'Tomoe';
update champions set role = 'HP' where name = 'Toragi';
update champions set role = 'HP' where name = 'Torturehelm';
update champions set role = 'HP' where name = 'Towering Titan';
update champions set role = 'Defense' where name = 'Trumborr';
update champions set role = 'Attack' where name = 'Ultimate Galek';
update champions set role = 'Defense' where name = 'Umbral Enchantress';
update champions set role = 'Attack' where name = 'Umetogi';
update champions set role = 'Support' where name = 'Urogrim';
update champions set role = 'Support' where name = 'Ursala';
update champions set role = 'Defense' where name = 'Ursine Icecrusher';
update champions set role = 'Defense' where name = 'Ursine Ironhide';
update champions set role = 'Attack' where name = 'Urticata';
update champions set role = 'Support' where name = 'Uugo';
update champions set role = 'Defense' where name = 'Valla';
update champions set role = 'Support' where name = 'Venomage';
update champions set role = 'Defense' where name = 'Vergis';
update champions set role = 'Support' where name = 'Vildrax';
update champions set role = 'Support' where name = 'Visionary';
update champions set role = 'HP' where name = 'Vogoth';
update champions set role = 'HP' where name = 'Vrask';
update champions set role = 'Support' where name = 'Warcaster';
update champions set role = 'Defense' where name = 'Warden';
update champions set role = 'Attack' where name = 'Weregren';
update champions set role = 'Attack' where name = 'Whisper';
update champions set role = 'Defense' where name = 'Nia';
update champions set role = 'HP' where name = 'Woad-Painted';
update champions set role = 'Attack' where name = 'Wuji';
update champions set role = 'HP' where name = 'Wuzgar';
update champions set role = 'Support' where name = 'Wyrennon the Silken';
update champions set role = 'Attack' where name = 'Wysteri';
update champions set role = 'Attack' where name = 'Yaga';
update champions set role = 'Attack' where name = 'Yelagirna';
update champions set role = 'HP' where name = 'Yuzan';
update champions set role = 'Attack' where name = 'Zargala';
update champions set role = 'Support' where name = 'Zelotah';
update champions set role = 'Attack' where name = 'Zii';
update champions set role = 'HP' where name = 'Ba Satha';
update champions set role = 'Support' where name = 'Bad-el-Kazar';
update champions set role = 'Defense' where name = 'Baerd';
update champions set role = 'Attack' where name = 'Balar';
update champions set role = 'Support' where name = 'Bambus';
update champions set role = 'Attack' where name = 'Baron';
update champions set role = 'Attack' where name = 'Roanas';
update champions set role = 'Attack' where name = 'Basim';
update champions set role = 'Defense' where name = 'Bayek';
update champions set role = 'Attack' where name = 'Belanor';
update champions set role = 'HP' where name = 'Belz';
update champions set role = 'Attack' where name = 'Big ''Un';
update champions set role = 'HP' where name = 'Black Knight';
update champions set role = 'Attack' where name = 'Caldor';
update champions set role = 'Support' where name = 'Blind Seer';
update champions set role = 'Defense' where name = 'Blizaar';
update champions set role = 'Attack' where name = 'Bloodgorged';
update champions set role = 'HP' where name = 'Bolint';
update champions set role = 'Attack' where name = 'Brakus';
update champions set role = 'Defense' where name = 'Jeroboam';
update champions set role = 'Attack' where name = 'Bystophus';
update champions set role = 'Attack' where name = 'Candraphon';
update champions set role = 'Attack' where name = 'Caoilte';
update champions set role = 'Support' where name = 'Cardiel';
update champions set role = 'Attack' where name = 'Chaagur';
update champions set role = 'Attack' where name = 'Chalco';
update champions set role = 'Attack' where name = 'Cheshire';
update champions set role = 'Support' where name = 'Adelyn';
update champions set role = 'Attack' where name = 'Cillian';
update champions set role = 'HP' where name = 'Claidna';
update champions set role = 'Attack' where name = 'Cleopterix';
update champions set role = 'Defense' where name = 'Corvis the Corruptor';
update champions set role = 'Attack' where name = 'Countess Lix';
update champions set role = 'Support' where name = 'Craklin';
update champions set role = 'Attack' where name = 'Crohnam';
update champions set role = 'Defense' where name = 'Cromax';
update champions set role = 'Attack' where name = 'Cruetraxa';
update champions set role = 'Support' where name = 'Crypt-King Graal';
update champions set role = 'Attack' where name = 'Cupidus';
update champions set role = 'Attack' where name = 'Danag';
update champions set role = 'HP' where name = 'Deliana';
update champions set role = 'Support' where name = 'Diamant';
update champions set role = 'Attack' where name = 'Dracomorph';
update champions set role = 'Defense' where name = 'Drexthar Bloodtwin';
update champions set role = 'Support' where name = 'Drokgul';
update champions set role = 'Support' where name = 'Duchess Lilitu';
update champions set role = 'Support' where name = 'Zaharis';
update champions set role = 'Defense' where name = 'Greggor';
update champions set role = 'Attack' where name = 'Edward';
update champions set role = 'Attack' where name = 'Elder Skarg';
update champions set role = 'Support' where name = 'Elegaius';
update champions set role = 'Attack' where name = 'Elenaril';
update champions set role = 'Support' where name = 'Elva';
update champions set role = 'HP' where name = 'Emic';
update champions set role = 'Support' where name = 'Eostrid';
update champions set role = 'Attack' where name = 'Errol';
update champions set role = 'Support' where name = 'Esme';
update champions set role = 'Attack' where name = 'Ezio Auditore';
update champions set role = 'Attack' where name = 'Falmond';
update champions set role = 'Defense' where name = 'Firrol';
update champions set role = 'Attack' where name = 'Tuskkor';
update champions set role = 'Attack' where name = 'Folan Silverhart';
update champions set role = 'Attack' where name = 'Foli';
update champions set role = 'Defense' where name = 'Fortus';
update champions set role = 'Defense' where name = 'Freyja';
update champions set role = 'Attack' where name = 'Fu-Shan';
update champions set role = 'Support' where name = 'Fyna';
update champions set role = 'HP' where name = 'Gaellut';
update champions set role = 'Attack' where name = 'Gaius';
update champions set role = 'Support' where name = 'Gamuran';
update champions set role = 'Defense' where name = 'Gaspard';
update champions set role = 'Attack' where name = 'Genzin';
update champions set role = 'Attack' where name = 'Georgid';
update champions set role = 'Support' where name = 'Ghostborn';
update champions set role = 'Defense' where name = 'Giath';
update champions set role = 'Defense' where name = 'Ginro';
update champions set role = 'Support' where name = 'Glaicad';
update champions set role = 'Defense' where name = 'Gliseah';
update champions set role = 'Support' where name = 'Glorious Pallas';
update champions set role = 'Attack' where name = 'Gnishak Verminlord';
update champions set role = 'Defense' where name = 'Gnut';
update champions set role = 'Defense' where name = 'Goffred';
update champions set role = 'Support' where name = 'Gomlok';
update champions set role = 'Defense' where name = 'Graazur';
update champions set role = 'Support' where name = 'Padraig';
update champions set role = 'HP' where name = 'Granyt';
update champions set role = 'Support' where name = 'Loriaca';
update champions set role = 'Defense' where name = 'Ruarc';
update champions set role = 'Attack' where name = 'Gretel';
update champions set role = 'Attack' where name = 'Grohak';
update champions set role = 'HP' where name = 'Gronjarr';
update champions set role = 'Attack' where name = 'Grugtha';
update champions set role = 'Attack' where name = 'Gurgoh';
update champions set role = 'Support' where name = 'Gurptuk';
update champions set role = 'Support' where name = 'Guurda';
update champions set role = 'Attack' where name = 'Gwyndolin';
update champions set role = 'HP' where name = 'Hakkorhn';
update champions set role = 'Attack' where name = 'Hansel';
update champions set role = 'Defense' where name = 'Harima';
update champions set role = 'HP' where name = 'Harvest Jack';
update champions set role = 'Attack' where name = 'He-Man';
update champions set role = 'Attack' where name = 'Hegemon';
update champions set role = 'Defense' where name = 'Helicath';
update champions set role = 'Defense' where name = 'Helior';
update champions set role = 'Attack' where name = 'Hephraak';
update champions set role = 'Support' where name = 'Prysma';
update champions set role = 'Support' where name = 'Maud';
update champions set role = 'Support' where name = 'Hilvi';
update champions set role = 'Attack' where name = 'Holsring';
update champions set role = 'Attack' where name = 'Hurndig';
update champions set role = 'Defense' where name = 'Ignatius';
update champions set role = 'Attack' where name = 'Inithwe';
update champions set role = 'Defense' where name = 'Iron Brago';
update champions set role = 'HP' where name = 'Ishiyama';
update champions set role = 'Attack' where name = 'Ithos';
update champions set role = 'Support' where name = 'Artor';
update champions set role = 'Attack' where name = 'Jagg';
update champions set role = 'Attack' where name = 'Jetni';
update champions set role = 'HP' where name = 'Jingwon';
update champions set role = 'Attack' where name = 'Jintoro';
update champions set role = 'Support' where name = 'Kaja';
update champions set role = 'Attack' where name = 'Kalvalax';
update champions set role = 'Defense' where name = 'Kantra';
update champions set role = 'Attack' where name = 'Karato';
update champions set role = 'Support' where name = 'Karilon';
update champions set role = 'Attack' where name = 'Kassandra';
update champions set role = 'Defense' where name = 'Kawn';
update champions set role = 'Attack' where name = 'Keberon';
update champions set role = 'Defense' where name = 'Keeyra';
update champions set role = 'HP' where name = 'Khoronar';
update champions set role = 'Support' where name = 'King Gallcobar';
update champions set role = 'Attack' where name = 'King Garog';
update champions set role = 'Defense' where name = 'Klaazag';
update champions set role = 'HP' where name = 'Knave';
update champions set role = 'HP' where name = 'Knosson';
update champions set role = 'Attack' where name = 'Konstantin';
update champions set role = 'HP' where name = 'Korugar';
update champions set role = 'Attack' where name = 'Kosk';
update champions set role = 'Support' where name = 'Kreela';
update champions set role = 'Defense' where name = 'Krisk';
update champions set role = 'HP' where name = 'Krok''mar';
update champions set role = 'Attack' where name = 'Kro''khad';
update champions set role = 'Attack' where name = 'Kroz';
update champions set role = 'Defense' where name = 'Kyoku';
update champions set role = 'Support' where name = 'Lady Kimi';
update champions set role = 'Support' where name = 'Noelle';
update champions set role = 'Support' where name = 'Lady of Ireth';
update champions set role = 'Support' where name = 'Lanakis the Chosen';
update champions set role = 'Attack' where name = 'Teox';
update champions set role = 'Attack' where name = 'Leminisi';
update champions set role = 'Attack' where name = 'Leorius';
update champions set role = 'Attack' where name = 'Little Miss Annie';
update champions set role = 'Support' where name = 'Loki';
update champions set role = 'HP' where name = 'Lonatharil';
update champions set role = 'Attack' where name = 'Longbeard';
update champions set role = 'HP' where name = 'Lord Champfort';
update champions set role = 'Support' where name = 'Fabian';
update champions set role = 'Attack' where name = 'Lord Shazar';
update champions set role = 'Defense' where name = 'K''Leth';
update champions set role = 'HP' where name = 'Lugan';
update champions set role = 'Support' where name = 'Lydia';
update champions set role = 'Defense' where name = 'Lysanthir';
update champions set role = 'Support' where name = 'Lyssandra';
update champions set role = 'Attack' where name = 'Ma''Shalled';
update champions set role = 'Support' where name = 'Hatter';
update champions set role = 'Attack' where name = 'Maranix';
update champions set role = 'Support' where name = 'Marichka';
update champions set role = 'Defense' where name = 'Marius the Gallant';
update champions set role = 'Defense' where name = 'Martyr';
update champions set role = 'HP' where name = 'Masahiro';
update champions set role = 'HP' where name = 'Mathias';
update champions set role = 'HP' where name = 'Zarguna';
update champions set role = 'Support' where name = 'Maulie';
update champions set role = 'Support' where name = 'Mavara the Web Diviner';
update champions set role = 'Attack' where name = 'Michelangelo';
update champions set role = 'Defense' where name = 'Michinaki';
update champions set role = 'Support' where name = 'Ukko';
update champions set role = 'Support' where name = 'Minaya';
update champions set role = 'Support' where name = 'Mithrala';
update champions set role = 'Attack' where name = 'Modo';
update champions set role = 'Support' where name = 'Morrigaine';
update champions set role = 'HP' where name = 'Mortu-Macaab';
update champions set role = 'Support' where name = 'Mother Cybele';
update champions set role = 'Attack' where name = 'Mountain King';
update champions set role = 'Defense' where name = 'Nari';
update champions set role = 'Support' where name = 'Narma the Returned';
update champions set role = 'Defense' where name = 'Nekhret';
update champions set role = 'Support' where name = 'Nekmo Thaar';
update champions set role = 'Attack' where name = 'Nethril';
update champions set role = 'Defense' where name = 'Niamhe';
update champions set role = 'Attack' where name = 'Ninja';
update champions set role = 'Attack' where name = 'Nobel';
update champions set role = 'HP' where name = 'Noct';
update champions set role = 'Attack' where name = 'Nogdar';
update champions set role = 'Support' where name = 'Noldua';
update champions set role = 'Defense' where name = 'Norog';
update champions set role = 'Support' where name = 'Odin';
update champions set role = 'Support' where name = 'Oella';
update champions set role = 'Attack' where name = 'Ieyasu';
update champions set role = 'HP' where name = 'Opardin';
update champions set role = 'Support' where name = 'Osgrun';
update champions set role = 'HP' where name = 'Shy''ek';
update champions set role = 'Support' where name = 'Pelagus';
update champions set role = 'HP' where name = 'Pelops the Victor';
update champions set role = 'Support' where name = 'Pheidi';
update champions set role = 'Defense' where name = 'Phemo';
update champions set role = 'Support' where name = 'Augustin';
update champions set role = 'Support' where name = 'Praeva';
update champions set role = 'HP' where name = 'Predator';
update champions set role = 'Support' where name = 'Prince Kymar';
update champions set role = 'Support' where name = 'Pythion';
update champions set role = 'Support' where name = 'Pyxniel';
update champions set role = 'Attack' where name = 'Eva';
update champions set role = 'Support' where name = 'Queen of Hearts';
update champions set role = 'Attack' where name = 'Quintus';
update champions set role = 'Attack' where name = 'Rae';
update champions set role = 'HP' where name = 'Raf-Matab';
update champions set role = 'Defense' where name = 'Ragash';
update champions set role = 'Support' where name = 'Raglin';
update champions set role = 'Support' where name = 'Rakka';
update champions set role = 'Attack' where name = 'Ramantu';
update champions set role = 'Attack' where name = 'Razelvarg';
update champions set role = 'Attack' where name = 'Rhaia';
update champions set role = 'Defense' where name = 'Rhazin';
update champions set role = 'Attack' where name = 'Richtoff the Bold';
update champions set role = 'Support' where name = 'Riho';
update champions set role = 'Attack' where name = 'Robar';
update champions set role = 'Attack' where name = 'Ronda';
update champions set role = 'Attack' where name = 'Roric';
update champions set role = 'HP' where name = 'Roshcard';
update champions set role = 'Attack' where name = 'Rotos';
update champions set role = 'Attack' where name = 'Roxam';
update champions set role = 'Attack' where name = 'Royal Huntsman';
update champions set role = 'Attack' where name = 'Ruel';
update champions set role = 'Attack' where name = 'Saito';
update champions set role = 'HP' where name = 'Samar';
update champions set role = 'HP' where name = 'Samson';
update champions set role = 'Attack' where name = 'Maria';
update champions set role = 'Defense' where name = 'Scyl of the Drakes';
update champions set role = 'Support' where name = 'Searsha';
update champions set role = 'Support' where name = 'Senna';
update champions set role = 'Attack' where name = 'Septimus';
update champions set role = 'Support' where name = 'Sethallia';
update champions set role = 'Support' where name = 'Shamrock';
update champions set role = 'Attack' where name = 'Shemnath';
update champions set role = 'Support' where name = 'Shirimani';
update champions set role = 'HP' where name = 'Shredder';
update champions set role = 'Support' where name = 'Shu-Zhen';
update champions set role = 'Attack' where name = 'Sicia';
update champions set role = 'Defense' where name = 'Sigmund';
update champions set role = 'Support' where name = 'Siphi';
update champions set role = 'HP' where name = 'Sir Nicholas';
update champions set role = 'Support' where name = 'Skartorsis';
update champions set role = 'Support' where name = 'Skeletor';
update champions set role = 'Attack' where name = 'Skorid';
update champions set role = 'Defense' where name = 'Var-Gall';
update champions set role = 'HP' where name = 'Sniktraak';
update champions set role = 'Attack' where name = 'Solanar';
update champions set role = 'Defense' where name = 'Soulless';
update champions set role = 'Defense' where name = 'Staltus Dragonbane';
update champions set role = 'Support' where name = 'Stokk';
update champions set role = 'Defense' where name = 'Hekaton';
update champions set role = 'Defense' where name = 'Islin';
update champions set role = 'Support' where name = 'Sulfuryion';
update champions set role = 'Attack' where name = 'Sun Wukong';
update champions set role = 'Attack' where name = 'Supreme Athel';
update champions set role = 'Attack' where name = 'Supreme Elhain';
update champions set role = 'Attack' where name = 'Supreme Galek';
update champions set role = 'Attack' where name = 'Supreme Kael';
update champions set role = 'Attack' where name = 'Suzerain Katonn';
update champions set role = 'Attack' where name = 'Zyclic';
update champions set role = 'Support' where name = 'Sydax';
update champions set role = 'Support' where name = 'Talenna';
update champions set role = 'HP' where name = 'Taras';
update champions set role = 'Attack' where name = 'Tatsu';
update champions set role = 'Defense' where name = 'Tatura';
update champions set role = 'Support' where name = 'Teela';
update champions set role = 'HP' where name = 'Tekteon';
update champions set role = 'Support' where name = 'Teodor the Savant';
update champions set role = 'Attack' where name = 'Tetsuya';
update champions set role = 'Attack' where name = 'Teumesia';
update champions set role = 'Defense' where name = 'The Incarnate';
update champions set role = 'Attack' where name = 'Thea';
update champions set role = 'Attack' where name = 'Tholin Foulbeard';
update champions set role = 'Attack' where name = 'Thor';
update champions set role = 'HP' where name = 'Timit';
update champions set role = 'Defense' where name = 'Titus';
update champions set role = 'Support' where name = 'Togron';
update champions set role = 'Support' where name = 'Tomb Lord';
update champions set role = 'Defense' where name = 'Tormin';
update champions set role = 'Support' where name = 'Tramaria';
update champions set role = 'Defense' where name = 'Herakletes';
update champions set role = 'HP' where name = 'Truath';
update champions set role = 'Attack' where name = 'Trunda';
update champions set role = 'Support' where name = 'Tuhanarak';
update champions set role = 'Attack' where name = 'Turvold';
update champions set role = 'HP' where name = 'Tyrant Ixlimor';
update champions set role = 'HP' where name = 'Ugir';
update champions set role = 'Attack' where name = 'Ultan';
update champions set role = 'Defense' where name = 'Ultimate Deathknight';
update champions set role = 'Support' where name = 'Underpriest Brogni';
update champions set role = 'HP' where name = 'Urost';
update champions set role = 'HP' where name = 'Ursuga';
update champions set role = 'Attack' where name = 'Uzol';
update champions set role = 'Attack' where name = 'Valkanen';
update champions set role = 'Defense' where name = 'Valkyrie';
update champions set role = 'Attack' where name = 'Varkos';
update champions set role = 'Attack' where name = 'Varl';
update champions set role = 'HP' where name = 'Vasal';
update champions set role = 'Defense' where name = 'Wixwell';
update champions set role = 'Support' where name = 'Venalicia';
update champions set role = 'Support' where name = 'Venus';
update champions set role = 'Support' where name = 'Vergumkaar';
update champions set role = 'HP' where name = 'Versulf';
update champions set role = 'Attack' where name = 'Vestele';
update champions set role = 'Defense' where name = 'Visix';
update champions set role = 'Attack' where name = 'Vizier Ovelis';
update champions set role = 'HP' where name = 'Vizug';
update champions set role = 'Attack' where name = 'Vlad';
update champions set role = 'Defense' where name = 'Vulkanos';
update champions set role = 'HP' where name = 'Walking Tomb Dreng';
update champions set role = 'Attack' where name = 'Othorion';
update champions set role = 'Attack' where name = 'War Mother';
update champions set role = 'Defense' where name = 'Warchief';
update champions set role = 'Support' where name = 'Warlord';
update champions set role = 'HP' where name = 'Narses';
update champions set role = 'Support' where name = 'Ankora';
update champions set role = 'Defense' where name = 'Wurlim';
update champions set role = 'Support' where name = 'Wythir';
update champions set role = 'Attack' where name = 'Xena';
update champions set role = 'Attack' where name = 'Xenomorph';
update champions set role = 'Support' where name = 'Xiloco';
update champions set role = 'Attack' where name = 'Yakarl';
update champions set role = 'Attack' where name = 'Yannica';
update champions set role = 'Support' where name = 'Yncensa';
update champions set role = 'Support' where name = 'Yoshi';
update champions set role = 'Attack' where name = 'Yukimasa';
update champions set role = 'Support' where name = 'Yumeko';
update champions set role = 'Attack' where name = 'Zavia';
update champions set role = 'Attack' where name = 'Mina';
update champions set role = 'Attack' where name = 'Cinda';
update champions set role = 'Support' where name = 'Embrys';
update champions set role = 'Support' where name = 'Fjorad';
update champions set role = 'HP' where name = 'Frolni';
update champions set role = 'Attack' where name = 'Galleus';
update champions set role = 'HP' where name = 'Gharol';
update champions set role = 'Support' where name = 'Gizmak';
update champions set role = 'Support' where name = 'Lazarius';
update champions set role = 'Attack' where name = 'Joan';
update champions set role = 'Attack' where name = 'Karnage';
update champions set role = 'Support' where name = 'Komidus';
update champions set role = 'Support' where name = 'Kurosa';
update champions set role = 'Support' where name = 'Lady Mikage';
update champions set role = 'Attack' where name = 'Mezomel';
update champions set role = 'Attack' where name = 'Nais';
update champions set role = 'Support' where name = 'Nell';
update champions set role = 'Support' where name = 'Krixia';
update champions set role = 'Attack' where name = 'Polara Fireheart';
update champions set role = 'Support' where name = 'Sabrael the Distant';
update champions set role = 'Attack' where name = 'Siegfrund';
update champions set role = 'Support' where name = 'Galathir';
update champions set role = 'Attack' where name = 'Calamitus';
update champions set role = 'Support' where name = 'Theodosia';
update champions set role = 'Attack' where name = 'Toshiro';
update champions set role = 'HP' where name = 'Jotun';
update champions set role = 'HP' where name = 'Gracchos Turn-drake';
