/**
 * Tag Agent — batch-tags untagged RSL champions from the Fandom wiki.
 *
 * Usage:
 *   node tools/tag-agent.js
 *   node tools/tag-agent.js --rarity Epic
 *   node tools/tag-agent.js --name "Michelangelo"
 *   node tools/tag-agent.js --limit 20
 *
 * Outputs: tools/output/tags_<timestamp>.sql  (ready to paste into Supabase)
 *
 * Env vars needed (same as the app):
 *   ANTHROPIC_API_KEY
 *   SUPABASE_URL
 *   SUPABASE_SERVICE_KEY
 */

import Anthropic                    from '@anthropic-ai/sdk';
import { createClient }             from '@supabase/supabase-js';
import { writeFileSync, mkdirSync } from 'fs';
import { parseArgs }                from 'util';

// ── Config ─────────────────────────────────────────────────────────────────

const DELAY_MS    = 500;    // pause between batches
const BATCH_SIZE  = 10;     // champions per Claude call (no wiki fetching needed)

// ── CLI args ───────────────────────────────────────────────────────────────

const { values: args } = parseArgs({
  options: {
    rarity: { type: 'string' },
    name:   { type: 'string' },
    limit:  { type: 'string' },
  },
  strict: false,
});

// ── Clients ────────────────────────────────────────────────────────────────

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const supabase  = createClient(
  (process.env.SUPABASE_URL ?? '').replace(/\/rest\/v1\/?$/, ''),
  process.env.SUPABASE_SERVICE_KEY,
  { global: { fetch } }
);

// ── Supabase helpers ───────────────────────────────────────────────────────

async function getUntaggedChampions() {
  let query = supabase
    .from('champions')
    .select(`id, name, rarity, champion_tags(id, status)`)
    .order('name');

  if (args.name)   query = query.ilike('name', args.name);
  if (args.rarity) query = query.eq('rarity', args.rarity);

  const { data, error } = await query;
  if (error) throw new Error(`Supabase error: ${error.message}`);

  // Keep only champions with no approved tags
  const untagged = data.filter(c =>
    !c.champion_tags.some(t => t.status === 'approved')
  );

  const limit = args.limit ? parseInt(args.limit) : Infinity;
  return untagged.slice(0, limit);
}

async function getAllTags() {
  const { data, error } = await supabase.from('tags').select('id, name, description');
  if (error) throw new Error(`Tags error: ${error.message}`);
  return data;
}

// ── Claude tagger (uses built-in RSL knowledge, no wiki fetching) ──────────

async function tagChampions(champions, allTags) {
  const tagList   = allTags.map(t => `- "${t.name}": ${t.description}`).join('\n');
  const nameList  = champions.map(c => `${c.name} (${c.rarity})`).join('\n');

  const prompt = `You are building a tag database for Raid: Shadow Legends champions.

AVAILABLE TAGS (use ONLY these exact names — do not invent new ones):
${tagList}

For each champion listed below, use your knowledge of their abilities to assign the correct tags.
Only assign a tag if the champion has a skill that clearly applies it.
Be conservative — if unsure, leave it out. All results are marked "proposed" and will be reviewed by a human.

CHAMPIONS TO TAG:
${nameList}

Respond with a JSON array:
[
  {
    "name": "Champion Name",
    "tags": ["Tag Name 1", "Tag Name 2"],
    "notes": "one line explaining which skill(s) justify the tags"
  }
]

Respond with ONLY the JSON array, no other text.`;

  let response;
  try {
    response = await anthropic.messages.create({
      model:      'claude-sonnet-4-6',
      max_tokens: 4096,
      messages:   [{ role: 'user', content: prompt }],
    });
  } catch (e) {
    console.error('  ❌ Claude API error:', e.message);
    return [];
  }

  const text = response.content.find(b => b.type === 'text')?.text ?? '[]';

  try {
    const jsonMatch = text.match(/\[[\s\S]*\]/);
    return JSON.parse(jsonMatch?.[0] ?? '[]');
  } catch {
    console.error('  ⚠ Could not parse Claude response:', text.slice(0, 300));
    return [];
  }
}

// ── SQL generator ──────────────────────────────────────────────────────────

function buildSQL(results, allTags) {
  const tagMap = new Map(allTags.map(t => [t.name, t.id]));
  const lines  = [];

  lines.push('-- Generated by tag-agent.js');
  lines.push('-- Status: proposed — review before approving');
  lines.push('-- Run the approval query after review:');
  lines.push('--   UPDATE champion_tags SET status=\'approved\' WHERE status=\'proposed\' AND id IN (...)');
  lines.push('');

  for (const { championId, championName, rarity, tags, notes } of results) {
    if (!tags.length) {
      lines.push(`-- ${championName} (${rarity}): no tags identified`);
      continue;
    }

    lines.push(`-- ${championName} (${rarity})`);
    if (notes) lines.push(`-- Notes: ${notes}`);

    for (const tagName of tags) {
      const tagId = tagMap.get(tagName);
      if (!tagId) {
        lines.push(`-- UNKNOWN TAG skipped: "${tagName}"`);
        continue;
      }
      lines.push(
        `INSERT INTO champion_tags (champion_id, tag_id, status, source_type) ` +
        `VALUES ('${championId}', '${tagId}', 'proposed', 'human_observation') ON CONFLICT DO NOTHING;`
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  console.log('🔍 Fetching untagged champions from Supabase…');
  const [champions, allTags] = await Promise.all([getUntaggedChampions(), getAllTags()]);

  if (!champions.length) {
    console.log('✅ No untagged champions found!');
    return;
  }

  console.log(`Found ${champions.length} untagged champions. Tags available: ${allTags.length}`);
  if (args.rarity) console.log(`  Filtering by rarity: ${args.rarity}`);

  const allResults = [];

  // Process in batches
  for (let i = 0; i < champions.length; i += BATCH_SIZE) {
    const chunk = champions.slice(i, i + BATCH_SIZE);
    console.log(`\nBatch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(champions.length / BATCH_SIZE)}: ${chunk.map(c => c.name).join(', ')}`);

    process.stdout.write(`  🤖 Asking Claude to tag ${chunk.length} champions… `);
    const tagged = await tagChampions(chunk, allTags);
    console.log('✓');

    for (const champion of chunk) {
      const found = tagged.find(t => t.name.toLowerCase() === champion.name.toLowerCase());
      allResults.push({
        championId:   champion.id,
        championName: champion.name,
        rarity:       champion.rarity,
        tags:         found?.tags  ?? [],
        notes:        found?.notes ?? '',
      });
    }

    if (i + BATCH_SIZE < champions.length) {
      await new Promise(r => setTimeout(r, DELAY_MS));
    }
  }

  // Write SQL output
  mkdirSync('tools/output', { recursive: true });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const outFile   = `tools/output/tags_${timestamp}.sql`;
  const sql       = buildSQL(allResults, allTags);
  writeFileSync(outFile, sql, 'utf8');

  // Summary
  const total    = allResults.length;
  const tagged   = allResults.filter(r => r.tags.length > 0).length;
  const untagged = total - tagged;

  console.log(`\n✅ Done!`);
  console.log(`   Champions processed : ${total}`);
  console.log(`   Successfully tagged : ${tagged}`);
  console.log(`   No tags found       : ${untagged}`);
  console.log(`   Output written to   : ${outFile}`);
  console.log('\nNext steps:');
  console.log('  1. Review the SQL file');
  console.log('  2. Paste into Supabase SQL editor and run');
  console.log('  3. Spot-check proposed tags then approve the ones that look right');
}

main().catch(e => { console.error('Fatal:', e.message, e.stack); process.exit(1); });
